import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
import {successorState,luxuryCatalogue,outdoorEvents} from './src/lifeExpansion.js';
import {formatMoney} from './src/money.js';
import {defaultWill,validateWill,inheritEstate} from './src/estate.js';
assert.equal(formatMoney(99_999_999),'$99,999,999');
assert.equal(formatMoney(100_000_000),'$100m');
assert.equal(formatMoney(1_000_000_000),'$1b');
assert.equal(formatMoney(1_000_000_000_000),'$1t');
assert.equal(formatMoney(-1_500_000_000),'-$1.5b');
const estateGame={age:45,alive:true,children:[{id:'a',name:'A',age:10},{id:'b',name:'B',age:12},{id:'c',name:'C',age:18}]};
const will=defaultWill(estateGame);
assert.equal(validateWill(will,estateGame),'');
assert.equal(will.beneficiaries.reduce((sum,p)=>sum+p.percent,0),100);
assert.ok(validateWill(will,{...estateGame,age:17}));
assert.ok(validateWill({...will,beneficiaries:[{id:'a',percent:50}]},estateGame));
assert.equal(inheritEstate({...estateGame,will},{id:'a'},100_000_000).bankBalance,34_000_000);
assert.equal(inheritEstate({...estateGame,will},{id:'excluded'},100_000_000).bankBalance,0);
assert.equal(inheritEstate({...estateGame,will},{id:'a'},-5000).bankBalance,0);
assert.deepEqual(inheritEstate(estateGame,{id:'a'},100_000_000),{});
const inherited={sterilized:true,politicalOffice:'Governor',criminalRecord:['offense'],creatorProfile:{followers:5000},companies:[{id:'family-company'}]};
const child={id:'child-42',age:12,name:'Taylor'};
const next=successorState(inherited,child);
assert.equal(next.sterilized,false);assert.deepEqual(next.criminalRecord,[]);assert.equal(next.politicalOffice,null);assert.equal(next.avatarSeed,child.id);assert.deepEqual(next.companies,inherited.companies);assert.notEqual(next.companies[0],inherited.companies[0]);
assert.equal(new Set(luxuryCatalogue.map(x=>x.id)).size,luxuryCatalogue.length);assert.equal(Object.keys(outdoorEvents).length,6);assert.ok(luxuryCatalogue.some(x=>x.kind==='Hypercar'));assert.ok(luxuryCatalogue.some(x=>x.kind==='Castle'));
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{
 const social=(await server.ssrLoadModule('/src/SocialMedia.jsx')).default;
 const politics=(await server.ssrLoadModule('/src/PoliticalCareer.jsx')).default;
 const health=(await server.ssrLoadModule('/src/HealthCenterScreen.jsx')).default;
 const Career=(await server.ssrLoadModule('/src/CareerSystems.jsx')).default;
 const WillPlanner=(await server.ssrLoadModule('/src/WillPlanner.jsx')).default;
 const portraits=await server.ssrLoadModule('/src/RelationshipPortrait.jsx');
 const statistics=await server.ssrLoadModule('/src/FullStatsScreen.jsx');
 assert.equal(statistics.statPercent(0),0);assert.equal(statistics.statPercent(150),100);assert.equal(statistics.statPercent(-5),0);assert.equal(statistics.statPercent(undefined),null);
 const meters=renderToStaticMarkup(React.createElement(statistics.CharacterStatBars,{stats:{happiness:0,health:75,smarts:100,looks:50}}));
 assert.equal((meters.match(/role="progressbar"/g)||[]).length,4);assert.match(meters,/aria-valuenow="0"/);assert.doesNotMatch(meters,/undefined|NaN/);
 const App=(await server.ssrLoadModule('/src/App.jsx')).default;
 const appHtml=renderToStaticMarkup(React.createElement(App));
 assert.match(appHtml,/nav-occupation/);assert.match(appHtml,/Unemployed/);
 const game={name:'Alex',age:35,year:2026,alive:true,gender:'Man',money:1e7,bankBalance:0,stats:{smarts:85,health:80,looks:70},socialAccounts:{},companies:[],log:[]};
 const props={game,setGame:()=>{},onMoney:()=>{},moneyAvailable:game.money};
 const fullStatsHtml=renderToStaticMarkup(React.createElement(statistics.default,{game}));
 for(const label of ['Career &amp; reputation','Money &amp; assets','Retirement &amp; legacy','Social media','Insurance &amp; legal history'])assert.ok(fullStatsHtml.includes(label));
 const rows=statistics.fullStatGroups(game).flatMap(group=>group.rows);
 assert.ok(rows.length>50);assert.equal(rows.find(row=>row.label==='Cash').value,'$10,000,000');assert.equal(rows.find(row=>row.label==='Career reputation').value,'Not recorded');
 const careerHtml=renderToStaticMarkup(React.createElement(Career,{...props,money:game.money}));
 assert.match(careerHtml,/>Politics</);assert.match(careerHtml,/>Social Media</);assert.doesNotMatch(careerHtml,/Creator Studio/);
 const willHtml=renderToStaticMarkup(React.createElement(WillPlanner,{game:estateGame,setGame:()=>{},netWorth:1e9,onClose:()=>{}}));
 assert.match(willHtml,/\$1b/);assert.match(willHtml,/Split equally/);assert.match(willHtml,/Sign &amp; save will/);
 assert.match(renderToStaticMarkup(React.createElement(social,props)),/Join PhotoShare/);
 assert.match(renderToStaticMarkup(React.createElement(politics,props)),/Run for City Councillor/);
 assert.match(renderToStaticMarkup(React.createElement(health,props)),/Vasectomy/);
 assert.match(renderToStaticMarkup(React.createElement(health,props)),/Liposuction/);
 const account={handle:'alex',followers:10000,posts:[],reputation:80,earnings:50,privacy:'Public'};
 assert.match(renderToStaticMarkup(React.createElement(social,{...props,game:{...game,socialAccounts:{PhotoShare:account}}})),/Publish post/);
 const person={id:'stable-person',name:'Taylor',gender:'Girl',ethnicity:'Black'};
 assert.equal(renderToStaticMarkup(React.createElement(portraits.PersonPortrait,{person})),renderToStaticMarkup(React.createElement(portraits.PersonPortrait,{person:{...person,role:'Partner'}})));
 console.log('PASS: succession state, luxury catalogue, six outdoor activities, social accounts, politics, surgeries, and stable portraits.');
}finally{await server.close();}
