import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
import {normalizeLife,advanceLifeSystems,economyQuote,trainSkill} from './src/lifeSystems.js';
import {normalizeRealism,weeklySchedule,setSchedule,setRoutine,advanceRealism,relationshipAction,chooseCare,moveHome,buyStarterHome,repairHome,housingQuote,treatPersistent,prepareInterview,completeInterview,workAction,resolveRealEvent,generationRealism,prepareChildChoices,exertActivity,recordConsequence,surgeryRecovery} from './src/realism.js';
import {planningNetWorth,advanceFuturePlanning,buyInsurance} from './src/futurePlanning.js';

const base=normalizeRealism(normalizeLife({name:'Alex',year:2026,age:35,alive:true,country:'United States',money:100000,bankBalance:50000,stats:{health:85,happiness:75,smarts:70,looks:60},job:'Software Developer',salary:80000,careerYears:2,educationStatus:'not-enrolled',family:{parents:[{id:'mother',name:'Mother',role:'Parent',age:72,health:65,closeness:70,alive:true}],siblings:[]},children:[],friends:[{id:'friend',name:'Morgan',role:'Friend',closeness:70,alive:true}],partner:{id:'partner',name:'Taylor',role:'Partner',closeness:70,trust:65,alive:true},assets:[],loans:[],log:[]}));
const snapshot=JSON.stringify(base);
assert.equal(weeklySchedule(base).values.Work,40);assert.equal(weeklySchedule(setRoutine(base,'work','part-time')).values.Work,24);assert.equal(weeklySchedule(setRoutine(base,'work','leave')).values.Work,0);assert.equal(setSchedule(base,'sleep',20).realism.schedule.sleep,10);assert.equal(setSchedule(base,'sleep',0).realism.schedule.sleep,4);
const overloaded={...base,children:Array.from({length:5},(_,i)=>({id:`c${i}`,age:2,alive:true})),realism:{...base.realism,schedule:{sleep:5,study:25,hobbies:15,social:10,exercise:6}}};const stressed=advanceRealism(overloaded,()=>.5);assert.ok(stressed.realism.energy<advanceRealism(base,()=>.5).realism.energy);assert.ok(stressed.realism.stress>base.realism.stress);assert.equal(advanceRealism(stressed,()=>0),stressed);assert.equal(JSON.stringify(base),snapshot);
const promise=relationshipAction(base,'partner','promise');assert.equal(relationshipAction(promise,'partner','promise'),promise);const kept=relationshipAction(promise,'partner','talk');assert.equal(kept.realism.promises[0].status,'fulfilled');const broken=advanceRealism({...promise,year:2027},()=>.5);assert.equal(broken.realism.promises[0].status,'broken');assert.ok(broken.partner.trust<base.partner.trust);const counsel=relationshipAction(base,'partner','counselling');assert.equal(counsel.money,99820);assert.ok(counsel.partner.trust>base.partner.trust);assert.equal(relationshipAction({...base,money:0,bankBalance:0},'partner','counselling').money,0);
const care=chooseCare(base,'mother','professional');assert.equal(weeklySchedule(care).values.Caregiving,2);const cared=advanceRealism(care,()=>.5);assert.equal(cared.realism.careArrears,0);assert.ok(cared.family.parents[0].health>=base.family.parents[0].health);const unpaid=advanceRealism({...care,money:0,bankBalance:0},()=>.5);assert.ok(unpaid.realism.careArrears>0);assert.ok(planningNetWorth(unpaid)<0);const deceased=advanceRealism({...care,family:{...base.family,parents:[{...base.family.parents[0],alive:false}]}},()=>.5);assert.deepEqual(deceased.realism.carePlans,{});
const tenant=moveHome(base,'apartment');assert.equal(tenant.money,99700);assert.ok(housingQuote(tenant,'apartment')>0);const rented=advanceRealism(tenant,()=>.5);assert.ok(rented.money<tenant.money);assert.equal(housingQuote({...tenant,educationStatus:'enrolled',universityHousing:'Campus residence'},'apartment'),0);const owned=buyStarterHome(base);assert.equal(owned.assets.length,1);assert.equal(owned.loans.length,1);assert.equal(planningNetWorth(owned),planningNetWorth(base));assert.equal(buyStarterHome(owned),owned);assert.equal(buyStarterHome({...base,creditScore:400}).assets.length,0);assert.equal(buyStarterHome({...base,salary:100}).assets.length,0);const repaired=repairHome({...owned,assets:[{...owned.assets[0],condition:60}]});assert.equal(repaired.assets[0].condition,75);assert.equal(repairHome(repaired),repaired);
const contract={...base,livingArrangement:{assetId:'rented-home'},assets:[{id:'rented-home',name:'Existing rental',category:'Homes',status:'rented',monthlyCost:700}],realism:undefined};const migrated=normalizeRealism(contract);assert.equal(migrated.realism.housing.type,'asset');assert.equal(advanceRealism(migrated,()=>.5).realism.housingArrears,0);
const chronic={...base,realism:{...base.realism,conditions:[{id:'diabetes',type:'diabetes',severity:40}]}};const untreated=advanceRealism(chronic,()=>.5),treated=treatPersistent(chronic,'diabetes');assert.equal(treated.money,98800);assert.equal(treatPersistent(treated,'diabetes'),treated);assert.equal(treated.realism.conditions.length,1);assert.ok(advanceRealism(treated,()=>.5).stats.health>untreated.stats.health);let insured=buyInsurance(chronic,'health').state;assert.ok(insured);const insuredCare=treatPersistent(insured,'diabetes');assert.ok(insuredCare.insurance.claims.length);assert.equal(surgeryRecovery(base,true).conditions[0].remaining,2);
const job={title:'Financial Analyst',salary:70000,category:'Finance'};const shortlisted=prepareInterview({...base,job:null,salary:0},job);assert.ok(shortlisted.pendingInterview);const hired=completeInterview(shortlisted,'examples',()=>0);assert.equal(hired.job,job.title);assert.equal(hired.realism.career.probation,true);const reviewed=advanceRealism(hired,()=>.5);assert.equal(reviewed.realism.career.probation,false);assert.ok(reviewed.realism.career.history.some(h=>h.outcome.includes('Performance')));const rejected=completeInterview(shortlisted,'exaggerate',()=>.99);assert.equal(rejected.job,null);assert.ok(rejected.realism.reputation<shortlisted.realism.reputation);const feedback=workAction(base,'feedback');assert.equal(workAction(feedback,'mentor'),feedback);assert.equal(workAction(base,'change').job,null);const laidOff=advanceRealism(base,()=>0);assert.equal(laidOff.job,null);assert.equal(laidOff.salary,0);assert.equal(laidOff.realism.economy.phase,'Recession');assert.equal(laidOff.money,base.money);
const child={id:'child',name:'Jordan',role:'Child',age:18,alive:true,interest:'art',autonomy:90,closeness:55};const family={...base,children:[child],educationPlans:{child:{path:'University',balance:60000,annualContribution:5000}}};const choices=prepareChildChoices(family);assert.equal(choices.children[0].ownEducationChoice,'Work');const independent=advanceFuturePlanning(choices,0);assert.equal(independent.educationPlans.child.yearsCompleted,undefined);assert.equal(independent.educationPlans.child.pausedForChoice,true);assert.ok(independent.educationPlans.child.balance>=60000);const supported=relationshipAction(choices,'child','support');assert.ok(supported.children[0].autonomy>choices.children[0].autonomy);const pressured=relationshipAction(choices,'child','pressure');assert.ok(pressured.children[0].trust<supported.children[0].trust);assert.ok(advanceRealism(choices,()=>.5).children[0].personalWealth>0);
const next=generationRealism(stressed,child);assert.equal(next.realism.burnout,0);assert.deepEqual(next.realism.conditions,[]);assert.deepEqual(next.realism.promises,[]);assert.equal(next.realism.economy,stressed.realism.economy);assert.equal(exertActivity(base,'Hiking').realism.energy,76);assert.equal(exertActivity(base,'Wellness').realism.energy,88);assert.equal(trainSkill({...base,realism:{...base.realism,energy:0}},'Music').skills.Music,10);
const accident={...base,realism:{...base.realism,event:{id:'accident',title:'Accident',choices:[{id:'care',cost:450,medical:true,recovery:1,health:3}]}}};const resolved=resolveRealEvent(accident,'care');assert.equal(resolved.realism.event,null);assert.equal(resolved.realism.conditions[0].type,'injury');assert.equal(resolveRealEvent(resolved,'care'),resolved);assert.equal(recordConsequence(base,{effects:{universityStanding:-20}},{key:'university-integrity',title:'Integrity'}).realism.reputation,44);
assert.ok(economyQuote({...base,realism:{...base.realism,economy:{...base.realism.economy,priceIndex:2}}}).living>economyQuote(base).living);assert.ok(advanceLifeSystems(advanceRealism(base,()=>.5),80000).economyHistory.length);
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{const Screen=(await server.ssrLoadModule('/src/RealismScreen.jsx')).default;for(const tab of ['Schedule','Relationships','Children','Health & care','Home','Work life','Economy','Life events']){const html=renderToStaticMarkup(React.createElement(Screen,{game:{...choices,realism:resolved.realism,pendingInterview:shortlisted.pendingInterview},setGame:()=>{},initialTab:tab}));assert.ok(html.length>1000,tab);assert.ok(!html.includes('NaN'),tab);const empty=renderToStaticMarkup(React.createElement(Screen,{game:{...base,age:0,alive:false,job:null,partner:null,children:[],friends:[],family:{parents:[],siblings:[]},realism:undefined},setGame:()=>{},initialTab:tab}));assert.ok(!empty.includes('NaN'),`${tab}: empty saved life`);}const AppModule=await server.ssrLoadModule('/src/App.jsx');assert.ok(AppModule.default);
 const paidMortgage=AppModule.simulateYearEconomy(owned);assert.equal(paidMortgage.loans[0].monthsPaid,12);assert.ok(paidMortgage.loans[0].balance<owned.loans[0].balance);assert.ok(paidMortgage.transactions.some(t=>t.label==='Loan repayments'));assert.ok(paidMortgage.transactions.some(t=>t.label==='Property and asset upkeep'));
 const originalRandom=Math.random;try{Math.random=()=>.5;assert.equal(AppModule.progressCareerYear(setRoutine(base,'work','leave')).salaryIncome,0);assert.equal(AppModule.progressCareerYear(setRoutine(base,'work','part-time')).salaryIncome,48000);}finally{Math.random=originalRandom;}
 const roundTrip=normalizeRealism(JSON.parse(JSON.stringify(resolved)));assert.deepEqual(roundTrip.realism.conditions,resolved.realism.conditions);assert.equal(roundTrip.realism.energy,resolved.realism.energy);
}
finally{await server.close();}
console.log('PASS: schedules/burnout, relationship memory, care/arrears, housing/mortgages, health/insurance, interviews/reviews/layoffs, child autonomy, inheritance resets, inflation, event decisions, and all eight screens.');
