import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createServer} from 'vite';
import {marry,divorce,divorceQuote,planningNetWorth,buyInsurance,insuredQuote,insuredExpense,settleLifeInsurance,setPensionRate,retire,pensionEstimate,saveEducationPlan,fundEducation,tutorChild,nominateSuccessor,inheritFamilyPlans,advanceFuturePlanning} from './src/futurePlanning.js';
const base={name:'Alex',age:40,year:2026,alive:true,money:1000000,bankBalance:0,salary:100000,job:'Engineer',stats:{smarts:80,health:90,happiness:75},partner:{id:'spouse',name:'Sam',age:38,personalWealth:100000,closeness:85},children:[{id:'child',name:'Taylor',age:10,alive:true,smarts:70}],assets:[],companies:[],loans:[],investments:null,family:{parents:[],siblings:[]},friends:[],log:[],transactions:[]};
const snapshot=JSON.stringify(base);
assert.ok(marry({...base,age:17}).error);
let married=marry(base,{prenup:true}).state;
assert.equal(married.money,996000);assert.equal(married.marriage.protectedWealth,996000);
assert.equal(divorceQuote({...married,bankBalance:200000,year:2032}).settlement,100000);
assert.equal(divorceQuote({...married,bankBalance:200000,year:2032,marriage:{...married.marriage,protectedInheritance:200000}}).settlement,0);
let pooled=marry(base,{prenup:false}).state;
assert.equal(pooled.bankBalance,100000);assert.equal(divorceQuote(pooled).settlement,548750);
const ended=divorce({...married,bankBalance:200000,year:2032},'Shared').state;
assert.equal(ended.marriage,null);assert.equal(ended.partner,null);assert.equal(ended.divorceObligations[0].alimony,10500);
assert.equal(ended.divorceObligations[0].yearsRemaining,3);assert.equal(ended.divorceHistory[0].settlement,100000);
const house={id:'house',name:'Home',category:'Homes',status:'owned',value:200000,condition:100};
const liquidation=divorce({...married,money:0,bankBalance:0,assets:[house],marriage:{...married.marriage,prenup:false}}).state;
assert.equal(liquidation.assets.length,0);assert.equal(liquidation.money,97500);
let insured=buyInsurance(base,'health').state;
const medical=insuredQuote(insured,10000,'health');assert.equal(medical.covered,8550);assert.equal(medical.userCost,1450);
const treatment=insuredExpense(insured,10000,'health',null,'Hospital');assert.equal(treatment.money,996150);assert.equal(treatment.insurance.claims[0].covered,8550);
const second=insuredQuote(treatment,1000,'health');assert.equal(second.userCost,100);
const cancelled={...treatment,insurance:{...treatment.insurance,policies:treatment.insurance.policies.map(p=>({...p,active:false}))}};
const reactivated=buyInsurance(cancelled,'health').state;assert.equal(reactivated.money,cancelled.money);assert.equal(reactivated.insurance.policies[0].claimsPaid,8550);
const lapsed=advanceFuturePlanning({...insured,year:2027,money:0,bankBalance:0},0);assert.equal(lapsed.insurance.policies[0].active,false);
const renewed=advanceFuturePlanning({...treatment,year:2027},0);assert.equal(renewed.insurance.policies[0].paidYear,2027);assert.equal(renewed.insurance.policies[0].deductibleUsed,0);
const auto=buyInsurance({...base,assets:[{id:'car',name:'Car',kind:'Car',status:'owned',value:50000}]},'auto','car').state;
assert.equal(insuredQuote(auto,10000,'auto','car').covered,7650);assert.equal(insuredQuote(auto,10000,'auto','other').covered,0);
let life=buyInsurance(base,'life').state;const payout=settleLifeInsurance({...life,alive:false});assert.equal(payout.bankBalance,250000);assert.equal(settleLifeInsurance(payout).bankBalance,250000);
let pension=setPensionRate(base,10).state;const annual=advanceFuturePlanning({...pension,year:2027},100000);
assert.equal(annual.pension.balance,13520);assert.equal(annual.pension.serviceYears,1);assert.equal(annual.money,990000);
assert.equal(advanceFuturePlanning(annual,100000),annual);
assert.ok(retire(base).error);
const retirement=retire({...base,age:60,pension:{balance:100000,serviceYears:20,totalSalary:2000000}}).state;
assert.equal(retirement.job,null);assert.equal(pensionEstimate(retirement).state,30000);
const paidPension=advanceFuturePlanning({...retirement,year:2027},0);assert.equal(paidPension.pension.lastPayment,34160);assert.equal(paidPension.bankBalance,34160);assert.equal(paidPension.pension.balance,99840);
let education=saveEducationPlan(base,'child',{path:'University',annualContribution:1000}).state;
education=fundEducation(education,'child',60000).state;assert.equal(education.educationPlans.child.balance,60000);
const tutored=tutorChild(education,'child').state;assert.equal(tutored.children[0].smarts,76);assert.ok(tutorChild(tutored,'child').error);
let study={...education,children:[{...base.children[0],age:18,smarts:80}],educationPlans:{child:{...education.educationPlans.child,annualContribution:0}}};
for(let year=2027;year<=2030;year++)study=advanceFuturePlanning({...study,year},0);
assert.equal(study.educationPlans.child.yearsCompleted,4);assert.equal(study.educationPlans.child.completed,true);assert.equal(study.children[0].educationLevel,2);
const unsupported=advanceFuturePlanning({...base,money:0,bankBalance:0,year:2027,divorceObligations:[{id:'d',childIds:['child'],childSupportPerChild:1000,custody:'Shared',yearsRemaining:1,alimony:500,arrears:0}],children:[...base.children,{id:'new-child',name:'New',age:2}]},0);
assert.equal(unsupported.divorceObligations[0].arrears,1000);assert.equal(unsupported.divorceObligations[0].childSupport,500);
const noMoreSupport=advanceFuturePlanning({...unsupported,year:2028,children:[{...base.children[0],age:18}]},0);assert.equal(noMoreSupport.divorceObligations[0].childSupport,0);
const company={id:'company',name:'Family Co',ownership:60,valuation:100000,cash:25000,debt:5000,employees:4};
const legacy=nominateSuccessor({...base,money:100000,companies:[company],will:{beneficiaries:[{id:'child',percent:50},{id:'charity',percent:50}]}},'company','child').state;
assert.equal(planningNetWorth(legacy),160000);
const heir=inheritFamilyPlans(legacy,base.children[0],160000);assert.equal(heir.bankBalance,50000);assert.equal(heir.companies[0].ownership,60);assert.equal(heir.companies[0].cash,25000);assert.equal(heir.companies[0].debt,5000);assert.equal(heir.companies[0].generation,2);assert.equal(heir.companies[0].professionalManager,true);
assert.equal(inheritFamilyPlans(legacy,{id:'other',name:'Other',age:20},160000).companies.length,0);
assert.equal(JSON.stringify(base),snapshot,'Planning functions must not mutate input state');
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{const Screen=(await server.ssrLoadModule('/src/FuturePlanningScreen.jsx')).default;const App=(await server.ssrLoadModule('/src/App.jsx')).default;
 const headings={'Marriage':'Review wedding','Insurance':'Health insurance','Retirement':'Your retirement plan','Children’s education':'Save education plan','Family business':'Save business successor'};
 for(const [section,heading] of Object.entries(headings)){const html=renderToStaticMarkup(React.createElement(Screen,{game:legacy,setGame:()=>{},section}));assert.match(html,/Available funds/);assert.ok(html.includes(heading),`${section} must render its primary action`);}
 const marriedHtml=renderToStaticMarkup(React.createElement(Screen,{game:married,setGame:()=>{},section:'Marriage'}));assert.match(marriedHtml,/Review divorce settlement/);
 assert.ok(renderToStaticMarkup(React.createElement(App)).length>1000);
 console.log('PASS: prenups, settlements and liquidation, support arrears and age limits, insurance claims/renewal/payouts, pensions, education and scholarships, business inheritance, input immutability, and screen rendering.');
}finally{await server.close();}
