import {funds,spend} from './futurePlanning.js';
import {countryBudgets} from './lifeSystems.js';
import {formatMoney} from './money.js';
const log=(g,text,tag='Child support')=>({...g,log:[{year:g.year,age:g.age,text,tag,icon:'👶'},...(g.log||[])]});
export function parentsTogether(g,id){return Boolean(id&&g.partner?.id===id&&g.partner.alive!==false);}
export const divorceOrderFor=(g,id)=>(g.divorceObligations||[]).find(o=>o.childIds?.includes(id));
export function reconcileChildSupport(input){
 let changed=false;const orders=[...(input.childSupportOrders||[])];
 const children=(input.children||[]).map(original=>{
  let child=original;const previous=orders.find(o=>o.childId===child.id),divorce=divorceOrderFor(input,child.id);
  const inferred=child.otherParentId||previous?.otherParentId||divorce?.formerSpouseId||(!child.adopted&&!child.singleParentAdoption?input.partner?.id:null);
  if(inferred&&!child.otherParentId){child={...child,otherParentId:inferred};changed=true;}
  if(!inferred)return child;
  const together=parentsTogether(input,inferred);
  if(together&&child.custody!=='Together'){child={...child,custody:'Together'};changed=true;}
  if(!together&&child.custody==='Together'){child={...child,custody:previous?.custody||divorce?.custody||(['Boy','Man'].includes(input.gender)?'Other parent':'You')};changed=true;}
  if(!together&&child.alive!==false&&child.age<18&&!previous&&!divorce){
   const other=(input.friends||[]).find(p=>p.id===inferred)||input.familyTree?.[inferred];
   orders.push({id:`support-${child.id}`,childId:child.id,childName:child.name,otherParentId:inferred,otherParentName:other?.name||'Other parent',otherIncome:other?.annualIncome??other?.salary??(countryBudgets[input.country]?.[0]||8000)*3,custody:['You','Shared','Other parent'].includes(child.custody)?child.custody:['Boy','Man'].includes(input.gender)?'Other parent':'You',arrears:0,startedYear:input.year,status:'Active'});changed=true;
  }
  return child;
 });
 const updated=orders.map(order=>{const child=children.find(c=>c.id===order.childId);const status=!child||child.age>=18||child.alive===false?'Ended':parentsTogether(input,order.otherParentId)?'Parents together':divorceOrderFor(input,order.childId)?'Divorce agreement':'Active';if(order.status===status)return order;changed=true;return {...order,status};});
 return changed?{...input,children,childSupportOrders:updated}:input;
}
export function supportQuote(g,order){const child=(g.children||[]).find(c=>c.id===order.childId);if(!child||child.alive===false||child.age>=18||parentsTogether(g,order.otherParentId)||divorceOrderFor(g,order.childId))return 0;if(order.custody==='You'&&(g.friends||[]).some(p=>p.id===order.otherParentId&&p.alive===false))return 0;const income=order.custody==='You'?order.otherIncome||0:Math.max(0,(g.lastEmploymentIncome??g.salary??0)+(g.pension?.lastPayment||0));return Math.round(Math.max((countryBudgets[g.country]?.[0]||8000)*.12,income*.15)*(order.custody==='Shared'?.5:1));}
export function changeCustody(input,childId,custody){const g=reconcileChildSupport(input);if(!g.alive||g.age<18||!['You','Shared','Other parent'].includes(custody))return input;const child=g.children?.find(c=>c.id===childId&&c.alive!==false&&c.age<18),order=g.childSupportOrders?.find(o=>o.childId===childId);if(!child||!order||parentsTogether(g,order.otherParentId)||divorceOrderFor(g,childId)||order.custody===custody||order.changedYear===g.year)return input;const paid=spend(g,300,'Co-parenting agreement');if(!paid)return input;return log({...paid,children:g.children.map(c=>c.id===childId?{...c,custody}:c),childSupportOrders:g.childSupportOrders.map(o=>o.childId===childId?{...o,custody,changedYear:g.year}:o)},`You and ${order.otherParentName} agreed on ${custody.toLowerCase()} custody for ${child.name}. The new support amount applies from the next yearly payment.`);}
export function paySupportArrears(g,childId){const order=g.childSupportOrders?.find(o=>o.childId===childId);if(!g.alive||!order?.arrears)return g;const amount=Math.min(funds(g),order.arrears);if(!amount)return g;const paid=spend(g,amount,'Child support arrears');return log({...paid,childSupportOrders:g.childSupportOrders.map(o=>o.childId===childId?{...o,arrears:o.arrears-amount}:o)},`You paid ${formatMoney(amount)} toward support owed for ${order.childName}.`);}
export function advanceChildSupport(input){if(!input.alive||input.childSupportYear===input.year)return input;let g={...reconcileChildSupport(input),childSupportYear:input.year};const orders=[];for(const original of g.childSupportOrders||[]){let order={...original};const due=supportQuote(g,order);let paid=0,received=0;if(order.custody==='You'){received=due;if(received)g={...g,bankBalance:(g.bankBalance||0)+received,lifetimeIncome:(g.lifetimeIncome||0)+received,transactions:[{label:`Child support received · ${order.childName}`,amount:received,year:g.year},...(g.transactions||[])]};}else{const total=due+(order.arrears||0);paid=Math.min(funds(g),total);if(paid)g=spend(g,paid,`Child support · ${order.childName}`);order.arrears=total-paid;}order={...order,lastPaid:paid,lastReceived:received,lastDue:due,lastYear:g.year};orders.push(order);if(due||paid||order.arrears)g=log(g,`Child support for ${order.childName}: ${received?`received ${formatMoney(received)}`:`paid ${formatMoney(paid)}; due ${formatMoney(due)}`}.${order.arrears?` Arrears: ${formatMoney(order.arrears)}.`:''}`);}return {...g,childSupportOrders:orders};}
export function separateParents(input){if(!input.alive||!input.partner||input.marriage)return input;const former=input.partner;const children=(input.children||[]).map(c=>!c.otherParentId&&!c.singleParentAdoption?{...c,otherParentId:former.id,custody:['Boy','Man'].includes(input.gender)?'Other parent':'You'}:c);const next={...input,children,partner:null,relationship:'Single',friends:[...(input.friends||[]).filter(p=>p.id!==former.id),{...former,role:'Friend',relationshipLabel:'Former partner',closeness:Math.max(18,(former.closeness||50)-24)}],relationshipHistory:[{year:input.year,formerPartnerId:former.id,formerPartnerName:former.name},...(input.relationshipHistory||[])]};return log(reconcileChildSupport(next),`You and ${former.name} separated.${children.some(c=>c.otherParentId===former.id&&c.age<18)?' Review custody and yearly child support in Child Support.':''}`,'A relationship ends');}
