import React,{useState} from 'react';
import {companyCeoSalary,salaryLimit,suggestedSalary,salaryReason,setCompanySalary} from './companySalary.js';
import {formatMoney} from './money.js';
export default function CompanySalaryPanel({game,company,setGame,onNotice}){
 const [amount,setAmount]=useState(()=>companyCeoSalary(game,company));
 const reason=salaryReason(game,company,Number(amount));
 const submit=()=>{const result=setCompanySalary(game,company.id,amount);if(result.error){onNotice(result.error);return;}setGame(result.game);onNotice(result.message);};
 return <section className="company-salary-panel"><div className="salary-heading"><h4>Your CEO salary</h4><span className="life-status">{company.ownership>=80?'Owner approval':'Board review required'}</span></div><p>Set your annual pay for {company.name}. Below 80% ownership, independent directors must approve it. Family appointees cannot vote on your compensation.</p><div className="life-metrics"><div><small>Current annual pay</small><b>{formatMoney(companyCeoSalary(game,company))}</b></div><div><small>Maximum · 5% of value</small><b>{formatMoney(salaryLimit(company))}</b></div></div><label className="salary-input">Annual salary<input type="number" min="0" max={salaryLimit(company)} step="1000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="development-actions"><button className="career-secondary" onClick={()=>setAmount(suggestedSalary(company))}>Use suggested · {formatMoney(suggestedSalary(company))}</button><button className="career-action" disabled={Boolean(reason)} onClick={submit}>{company.ownership>=80?'Set salary':'Submit to the board'}</button></div>{reason&&<p role="status">{reason}</p>}{company.salaryReview&&<p className="salary-review">Last proposal: {formatMoney(company.salaryReview.amount)} · {company.salaryReview.approved?'Approved':'Declined'}{company.salaryReview.reviewed?` · ${company.salaryReview.yesVotes}/${company.salaryReview.totalVotes} votes`:''}</p>}<small>Paid from company cash at age-up. Three months of salary must be held in reserve.</small></section>;
}
