import SportsTeamScreen from './SportsTeamScreen.jsx';
import {SportsActivityPanel} from './PublicCareerPanels.jsx';
import React,{useState} from 'react';
import {enrichmentState} from './enrichmentCore.js';
import {ambitions,enrichmentAction,businessExperience,captureTimeline} from './lifeEnrichment.js';
import {housingAction,renovateHome,neighbourhoods,transportModes,renovationOptions} from './housingLife.js';
import {academicGrade,letterGrade,difficultyModes} from './simulationSettings.js';
import {peopleInLife} from './gameFixes.js';
const fmt=n=>`$${Math.round(n||0).toLocaleString()}`;
function useAction(setGame){const [notice,setNotice]=useState('');return [notice,fn=>setGame(g=>{const r=fn(g);setNotice(r.error||r.message||'Saved.');return r.game;})];}
function Card({title,children}){return <section className="enrichment-card"><h3>{title}</h3>{children}</section>;}
export function BusinessLifePanel({game,setGame,company}){const [notice,run]=useAction(setGame);return <Card title="Products, customers & acquisitions"><p>Customer rating: {(company.customerRating||3).toFixed(1)} / 5 · {(company.acquisitions||[]).length} acquisitions. Strategies use company cash; one decision per year.</p><div className="enrichment-actions">{[['product','Launch a new product',.04],['reviews','Improve customer service',.015],['acquisition','Acquire a regional rival',.4]].map(([a,label,rate])=><button key={a} onClick={()=>run(g=>businessExperience(g,company.id,a))}>{label}<small>{fmt(Math.max(2000,company.valuation*rate))}</small></button>)}{company.cash<0&&<button onClick={()=>run(g=>businessExperience(g,company.id,'bankruptcy'))}>Enter bankruptcy and close company</button>}</div>{notice&&<p role="status">{notice}</p>}</Card>;}
export function RelationshipLifePanel({game,setGame,person}){const [notice,run]=useAction(setGame);const p=peopleInLife(game).find(p=>p.id===person.id)||person;return <Card title="Trust & personal boundaries"><p>{p.estranged?'Estranged · give them time to rebuild trust':(p.closeness??50)>=80?'A strong, lasting bond':'Your connection is still growing'} · {p.boundary==='Space'?'They need personal space':'Open to contact'}</p><div className="enrichment-actions">{[['boundary','Discuss boundaries'],['reconnect','Offer reconciliation'],['reunion','Arrange a reunion']].map(([a,label])=><button key={a} onClick={()=>run(g=>enrichmentAction(g,a,p.id))}>{label}</button>)}</div>{notice&&<p role="status">{notice}</p>}</Card>;}
export function TravelLifePanel({game,setGame,destination}){const [notice,run]=useAction(setGame);return <Card title="Prepare for travel"><p>Visitor visa: {(game.enrichment?.travelVisas?.[destination]?.expires||0)>=game.year?'Valid':'Not held'} · Local language familiarity: {game.enrichment?.languages?.[destination]||0}/100</p><p>Visitor visas are simulated for foreign trips. They do not grant residence or erase criminal records.</p><div className="enrichment-actions"><button onClick={()=>run(g=>enrichmentAction(g,'visa',destination))}>Apply for visitor visa<small>$150 processing fee</small></button><button onClick={()=>run(g=>enrichmentAction(g,'language',destination))}>Study the local language<small>{game.age<18?'Family learning':'$300 course'}</small></button></div>{notice&&<p role="status">{notice}</p>}</Card>;}
export function EstateLifePanel({game,setGame}){return <Card title="Estate planning & family succession"><p>Your existing will allocates the estate and Family & Future assigns company successors. Unequal distributions can trigger sibling claims. Explain your wishes to reduce disputes.</p><label><input type="checkbox" checked={!!game.estatePlan?.levyEnabled} onChange={e=>{const enabled=e.target.checked;setGame(g=>({...g,estatePlan:{...g.estatePlan,levyEnabled:enabled}}));}}/> Include a simulated estate levy</label><p>Game rule: 15% of the net estate above $2 million, paid before beneficiary shares. This is a fictional difficulty rule.</p><button onClick={()=>setGame(g=>({...g,worldLife:{...g.worldLife,estateExplained:true},estatePlan:{...g.estatePlan,explainedYear:g.year},log:[{year:g.year,age:g.age,text:'You explained your estate wishes to your family.',tag:'Estate planning',icon:'📜'},...(g.log||[])]}))} disabled={!game.alive||game.age<18}>Explain your wishes to the family</button>{game.estateReceipt&&<p>Last estate: {fmt(game.estateReceipt.netEstate)} · levy {fmt(game.estateReceipt.levy)} · inheritance after levy {fmt(game.estateReceipt.received)}</p>}</Card>;}
export default function EnrichmentScreen({type,game,setGame,onSocial}){const [notice,run]=useAction(setGame),[memo,setMemo]=useState(''),[filter,setFilter]=useState('All');const state=enrichmentState(game),h=state.housing,s=state.sports;const act=(a,v)=>run(g=>enrichmentAction(g,a,v));const tags=[...new Set((game.lifeTimeline||game.log||[]).map(e=>e.tag).filter(Boolean))];return <div className={`enrichment-screen ${type==='Sports Career'?'sports-enrichment-shell':''}`}><header hidden={type==='Sports Career'}><span className="eyebrow">YOUR LIFE · AGE {game.age}</span><h2>{type}</h2><p>Choices today become part of your story tomorrow.</p></header>{notice&&<p className="enrichment-notice" role="status">{notice}</p>}
 {type==='Housing & Daily Life'&&<><Card title="Your neighbourhood"><p>{h.neighbourhood} · {h.transport} commute · {game.realism?.housing?.quality||65}/100 home quality</p><div className="enrichment-actions">{Object.entries(neighbourhoods).map(([n,v])=><button key={n} onClick={()=>run(g=>housingAction(g,'neighbourhood',n))}>{n}<small>Quality {v.quality} · rent ×{v.factor} · move {fmt(1200*v.factor)}</small></button>)}</div></Card><Card title="Commuting"><div className="enrichment-actions">{Object.entries(transportModes).map(([n,v])=><button key={n} onClick={()=>run(g=>housingAction(g,'transport',n))}>{n}<small>{fmt(v.cost)} / year while working or studying</small></button>)}</div></Card><Card title="Roommates"><p>{h.roommate?`${h.roommate.name} · reliability ${h.roommate.reliability}% · last contribution ${fmt(h.roommate.paid)}`:'Share rent with one roommate. Reliable roommates cost less in missed contributions.'}</p><div className="enrichment-actions">{h.roommate?<button onClick={()=>run(g=>housingAction(g,'end-roommate'))}>End roommate agreement</button>:['Avery','Jules','Kai'].map((name,i)=><button key={name} onClick={()=>run(g=>housingAction(g,'roommate',`roommate-${name.toLowerCase()}`))}>{name}<small>Reliability {[90,70,55][i]}%</small></button>)}</div></Card>{(game.assets||[]).filter(a=>a.category==='Homes').map(a=><Card key={a.id} title={a.name}><p>{a.country||game.country} · {fmt(a.value)} · condition {a.condition??100}% · {a.renovation?.status||'No renovation underway'}</p><button onClick={()=>run(g=>housingAction(g,'home',a.id))}>Move into this home</button><div className="enrichment-actions">{Object.entries(renovationOptions).map(([n,v])=><button key={n} onClick={()=>run(g=>renovateHome(g,a.id,n))}>{n}<small>From {fmt(Math.max(800,a.value*v.rate))} · completes next year</small></button>)}</div></Card>)}</>}
 {type==='Childhood'&&<><Card title="Household rules"><p>{game.age>=18?'Your childhood is behind you. Its choices remain in your timeline.':`Curfew ${state.childhood.curfew}:00 · parental strictness ${state.childhood.strictness}/100 · allowance up to ${fmt(state.childhood.allowance)} / week, subject to your parent’s funds.`}</p><div className="enrichment-actions"><button onClick={()=>act('chores')}>Help with chores</button><button onClick={()=>act('rules')}>Negotiate household rules</button><button onClick={()=>act('rebel')}>Break curfew</button></div></Card><Card title="Academic strengths"><p>Academic grade {letterGrade(academicGrade(game))} · {Math.round(academicGrade(game))}% · focus: {state.childhood.focus}. One major childhood decision per year.</p><div className="enrichment-actions">{['Science','Mathematics','Literature','Art','Languages'].map(n=><button key={n} onClick={()=>act('study',n)}>Practise {n}</button>)}</div><p>School clubs, cliques, classmates and bullying support remain in the School menu.</p></Card></>}
 {type==='Sports Career'&&<SportsTeamScreen game={game} setGame={setGame} onSocial={onSocial}/>}
 {type==='Life Ambitions'&&<><Card title="What makes a life meaningful?"><div className="enrichment-actions">{ambitions.map(n=><button key={n} aria-pressed={state.ambition?.name===n} onClick={()=>act('ambition',n)}>{n}</button>)}</div></Card>{state.ambition&&<Card title={state.ambition.name}><p>Satisfaction {state.ambition.satisfaction}/100</p><progress max="100" value={state.ambition.satisfaction}/><p>Your progress is reviewed at each age-up and kept in your life history.</p></Card>}</>}
 {type==='Simulation Settings'&&<><Card title="Difficulty"><div className="enrichment-actions">{Object.keys(difficultyModes).map(n=><button key={n} aria-pressed={(game.difficulty||'Realistic')===n} onClick={()=>setGame(g=>({...g,difficulty:n}))}>{n}<small>{n==='Relaxed'?'Lower costs and risks':n==='Challenging'?'Higher costs and fewer opportunities':'Balanced costs and risks'}</small></button>)}</div></Card><Card title="Tune your simulation">{[['economySeverity','Cost of living'],['eventSeverity','New event severity']].map(([key,label])=><label key={key}>{label} · {game.simulationSettings?.[key]||1}×<input type="range" min=".5" max="1.5" step=".1" value={game.simulationSettings?.[key]||1} onChange={e=>{const value=Number(e.target.value);setGame(g=>({...g,simulationSettings:{...g.simulationSettings,[key]:value}}));}}/></label>)}<p>These settings change living and housing costs, athletic opportunities and new incident risks. Taxes and existing debts keep their original rules.</p></Card></>}
 {type==='Life Timeline'&&<><Card title="Preserve a memory"><label>A personal note<textarea maxLength={600} value={memo} onChange={e=>setMemo(e.target.value)}/></label><button disabled={!memo.trim()} onClick={()=>{const text=memo.trim();setGame(g=>captureTimeline({...g,log:[{age:g.age,year:g.year,text,tag:'Personal memory',icon:'📖'},...(g.log||[])]}));setMemo('');}}>Save memory</button><label>Add a photo (up to 250 KB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>250000||!['image/png','image/jpeg','image/webp'].includes(file.type)){run(g=>({game:g,error:'Choose a PNG, JPEG or WebP image under 250 KB.'}));return;}const reader=new FileReader();reader.onload=()=>setGame(g=>({...g,timelinePhotos:[...(g.timelinePhotos||[]),{id:`photo-${Date.now()}`,age:g.age,year:g.year,name:file.name,url:reader.result}]}));reader.readAsDataURL(file);}}/></label></Card><label>Filter events<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...tags].map(t=><option key={t}>{t}</option>)}</select></label>{(game.timelinePhotos||[]).map(p=><figure key={p.id}><img src={p.url} alt={p.name}/><figcaption>Age {p.age} · {p.year}<button onClick={()=>setGame(g=>({...g,timelinePhotos:g.timelinePhotos.filter(x=>x.id!==p.id)}))}>Remove photo</button></figcaption></figure>)}{[...(game.lifeTimeline||game.log||[])].filter(e=>filter==='All'||e.tag===filter).sort((a,b)=>b.year-a.year||b.age-a.age).map((e,i)=><article className="timeline-event" key={e.id||i}><span>{e.icon||'✨'}</span><div><small>Age {e.age} · {e.year} · {e.tag}</small><p>{e.text}</p></div></article>)}{(game.legacyTimelines||[]).map((l,i)=><details key={i}><summary>{l.name} · generation {l.generation}</summary>{(l.photos||[]).map(p=><figure key={p.id}><img src={p.url} alt={p.name}/><figcaption>Age {p.age} · {p.year}</figcaption></figure>)}{l.events.map((e,j)=><p key={j}>Age {e.age}: {e.text}</p>)}</details>)}</>}
 </div>;}
