import React from 'react';
import {PersonPortrait} from './RelationshipPortrait.jsx';
import {formatMoney} from './money.js';
import {appointmentReason,appointChild,dismissChild,familyRoleSalary,isSpouse,familyEmployees} from './familyEmployment.js';
export default function FamilyBusinessStaff({game,company,setGame,onNotice}){
  const children=familyEmployees(game).filter((p,i,all)=>p.alive!==false&&all.findIndex(n=>n.id===p.id)===i&&((game.children||[]).some(c=>c.id===p.id)||isSpouse(game,p)||p.familyEmployment?.companyId===company.id));
  const run=(child,role)=>{const result=role==='dismiss'?dismissChild(game,company.id,child.id):appointChild(game,company.id,child.id,role);if(result.error){onNotice(result.error);return;}setGame(result.game);onNotice(result.message);};
  return <section className="family-staff-panel"><h4>Family appointments</h4><p>Appoint your spouse or adult children to management or the board. You can dismiss any family appointee. Salaries come from company cash at year-end; board seats grant no ownership.</p>{children.length?children.map(child=>{const current=child.familyEmployment?.companyId===company.id?child.familyEmployment:null;return <article className="family-staff-row" key={child.id}><div className="family-staff-person"><PersonPortrait person={child}/><div><b>{child.name}</b><small>{isSpouse(game,child)?'Spouse · ':''}Age {child.age} · {current?(current.role==='board'?'Board director':'Manager'):child.job||'No company role'}</small>{current&&<small>{formatMoney(current.salary)}/year</small>}</div></div>{child.age<18?<small>Available at age 18</small>:<div className="family-staff-actions">{[['manager','Manager'],['board','Board member']].map(([role,label])=>{const reason=appointmentReason(game,company,child,role);return <button className="career-secondary" key={role} disabled={Boolean(reason)} title={reason||`${formatMoney(familyRoleSalary(company,role))}/year`} onClick={()=>run(child,role)}>{current?.role===role?'Current: ':''}{label}<small>{formatMoney(familyRoleSalary(company,role))}/year</small></button>;})}{current&&<button className="career-secondary" onClick={()=>run(child,'dismiss')}>End appointment · Dismiss</button>}</div>}{child.age>=18&&!current&&appointmentReason(game,company,child,'manager')&&<small>{appointmentReason(game,company,child,'manager')}</small>}</article>;}):<p>A spouse or adult child can join your company here.</p>}</section>;
}
