import {spend,funds} from './futurePlanning.js';
const pairs=[['EUR/USD',1.08,.0001,1.2],['GBP/USD',1.27,.0001,1.5],['USD/JPY',149,.01,1.4],['AUD/USD',.66,.0001,1.3],['USD/CHF',.88,.0001,1.6],['USD/CAD',1.36,.0001,1.5]];
export const createForex=()=>({minute:0,quotes:pairs.map(([symbol,mid,pip,spread])=>({symbol,mid,pip,spread,history:Array.from({length:64},(_,i)=>mid+pip*(Math.sin(i*.41)*6+Math.sin(i*.13)*12-Math.sin(63*.41)*6-Math.sin(63*.13)*12)),bias:0})),positions:[],history:[],news:[],realized:0});
export const forexState=g=>g.forex||createForex();
export const forexMarketOpen=f=>Math.floor(f.minute/1440)%7<5;
export const forexQuote=q=>({bid:q.mid-q.pip*q.spread/2,ask:q.mid+q.pip*q.spread/2});
const dollarRate=q=>q.symbol.endsWith('/USD')?1:1/q.mid;
export const forexPnl=(p,q)=>((p.side==='buy'?forexQuote(q).bid:forexQuote(q).ask)-p.entry)*(p.side==='buy'?1:-1)*p.units*dollarRate(q)-(p.swap||0);
export function openForex(g,symbol,side,margin,leverage,stopPips=30,takePips=60){const f=forexState(g),q=f.quotes.find(q=>q.symbol===symbol);margin=Number(margin);leverage=Number(leverage);stopPips=Number(stopPips);takePips=Number(takePips);if(!g.alive||g.age<18||!q||!['buy','sell'].includes(side))return {game:g,error:'Trading is available to living adults.'};if(!Number.isInteger(margin)||margin<10||!Number.isInteger(leverage)||leverage<1||leverage>30||!Number.isFinite(stopPips)||stopPips<=q.spread||!Number.isFinite(takePips)||takePips<1)return {game:g,error:'Use margin of at least $10, leverage 1–30, and stop distance greater than the spread.'};if(!forexMarketOpen(f))return {game:g,error:'The simulated currency market is closed for the weekend.'};const paid=spend(g,margin,'Forex margin reserved');if(!paid)return {game:g,error:'Not enough free funds for this margin.'};const entry=side==='buy'?forexQuote(q).ask:forexQuote(q).bid,units=margin*leverage/(entry*dollarRate(q)),sign=side==='buy'?1:-1;const p={id:`fx-${Date.now()}-${f.positions.length}`,symbol,side,margin,leverage,units,entry,stop:entry-sign*stopPips*q.pip,take:entry+sign*takePips*q.pip,openedMinute:f.minute,swap:0};return {game:{...paid,lifetimeSpending:g.lifetimeSpending||0,forex:{...f,positions:[p,...f.positions]}},message:`${side==='buy'?'Long':'Short'} ${symbol} opened. Margin ${margin}, leverage ${leverage}:1.`};}
export function closeForex(g,id,reason='Manual close'){const f=forexState(g),p=f.positions.find(p=>p.id===id);if(!p)return g;const q=f.quotes.find(q=>q.symbol===p.symbol),pnl=forexPnl(p,q),returned=Math.max(0,p.margin+pnl),realized=returned-p.margin;const entry={...p,closedMinute:f.minute,exit:p.side==='buy'?forexQuote(q).bid:forexQuote(q).ask,pnl:realized,reason};return {...g,money:(g.money||0)+returned,lifetimeIncome:(g.lifetimeIncome||0)+Math.max(0,realized),lifetimeSpending:(g.lifetimeSpending||0)+Math.max(0,-realized),transactions:[{year:g.year,age:g.age,label:`Forex · ${p.symbol} · ${reason}`,amount:returned},...(g.transactions||[])],forex:{...f,positions:f.positions.filter(n=>n.id!==id),realized:f.realized+realized,history:[entry,...f.history].slice(0,100)}};}
export function tickForex(input,random=Math.random){if(!input.alive||!input.forex)return input;let f=forexState(input),minute=f.minute+5;const open=forexMarketOpen({...f,minute});const news=open&&minute%60===0?{id:`fx-news-${minute}`,minute,symbol:f.quotes[Math.floor(random()*f.quotes.length)].symbol,positive:random()>.5,headline:['Interest-rate expectations shift after a central bank speech','Employment data surprises currency traders','Inflation release increases currency volatility'][Math.floor(random()*3)]}:null;
const quotes=f.quotes.map(q=>{if(!open)return q;const hit=news?.symbol===q.symbol,bias=hit?(news.positive?1:-1):q.bias*.94;const move=(random()-.5)*q.pip*8+bias*q.pip*1.5,mid=Math.max(q.pip*100,q.mid+move);return {...q,mid,bias,spread:hit?q.spread*1.6:Math.max(pairs.find(p=>p[0]===q.symbol)[3],q.spread*.94),history:[...q.history.slice(-79),mid]};});
let g={...input,forex:{...f,minute,quotes,news:news?[news,...f.news].slice(0,20):f.news,positions:f.positions.map(p=>({...p,swap:p.swap+(Math.floor(minute/1440)>Math.floor(f.minute/1440)?p.margin*p.leverage*.00008:0)}))}};
for(const p of g.forex.positions){const q=quotes.find(q=>q.symbol===p.symbol),exit=p.side==='buy'?forexQuote(q).bid:forexQuote(q).ask;const stop=p.side==='buy'?exit<=p.stop:exit>=p.stop,take=p.side==='buy'?exit>=p.take:exit<=p.take;if(stop||take||p.margin+forexPnl(p,q)<=p.margin*.5)g=closeForex(g,p.id,stop?'Stop loss':take?'Take profit':'Margin closeout');}return g;}
export const forexEquity=g=>forexState(g).positions.reduce((n,p)=>n+Math.max(0,p.margin+forexPnl(p,forexState(g).quotes.find(q=>q.symbol===p.symbol))),0);
