import {recordAge} from './lifeRecords.js';
import {skillNames} from './lifeSystems.js';
import React,{useState} from 'react';
import {PersonPortrait} from './RelationshipPortrait.jsx';
import {formatMoney} from './money.js';
import {planningNetWorth,pensionEstimate,companyEquity} from './futurePlanning.js';
export const basicStats=[{key:'happiness',label:'Happiness',icon:'☀️'},{key:'health',label:'Health',icon:'❤️'},{key:'smarts',label:'Smarts',icon:'🧠'},{key:'looks',label:'Looks',icon:'✨'}];
export function statPercent(value){const number=Number(value);return value==null||!Number.isFinite(number)?null:Math.round(Math.max(0,Math.min(100,number))*10)/10;}
export function CharacterStatBars({stats={},search=''}){
 return <div className="character-stat-list">{basicStats.filter(stat=>!search||stat.label.toLowerCase().includes(search)).map(stat=>{const value=statPercent(stats?.[stat.key]);return <div className="character-stat-meter" key={stat.key}><div className="character-stat-caption"><span>{stat.icon} {stat.label}</span><b>{value===null?'—':`${value}%`}</b></div><div className="character-stat-track" role="progressbar" aria-label={stat.label} aria-valuemin={0} aria-valuemax={100} {...(value===null?{'aria-valuetext':'Not recorded'}:{'aria-valuenow':value})}><span style={{width:`${value??0}%`}}/></div></div>;})}</div>;
}
const number=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n)||0);
const count=(label,value)=>({label,value:number(value)});
const currency=(label,value)=>({label,value:formatMoney(value)});
const text=(label,value)=>({label,value:value==null||value===''?'Not recorded':String(value)});
const percent=(label,value)=>({label,value:statPercent(value)===null?'Not recorded':`${statPercent(value)}%`});
const average=people=>people.length?people.reduce((sum,p)=>sum+(p.closeness??50),0)/people.length:null;
export function fullStatGroups(g){
 const children=(g.children||[]).filter(p=>p.alive!==false);const friends=(g.friends||[]).filter(p=>p.alive!==false);
 const parents=(g.family?.parents||[]).filter(p=>p.alive!==false);const siblings=(g.family?.siblings||[]).filter(p=>p.alive!==false);
 const education=g.educationLevel||0;const p=g.pension||{};const estimate=pensionEstimate(g);
 const accounts=Object.values(g.socialAccounts||{});const posts=accounts.flatMap(a=>a.posts||[]);const companies=g.companies||[];const policies=g.insurance?.policies||[];
 const groups=[
 {title:'Casual encounters',icon:'🌙',rows:[count('One-night stands',g.casualEncounters?.encounters?.length),count('Profiles viewed this year',g.casualEncounters?.searchYear===g.year?g.casualEncounters.searches:0)]},
 {title:'Nightlife',icon:'🪩',rows:[count('Recorded club visits',g.nightlife?.history?.length),count('Casual encounters',g.nightlife?.encounters?.length),count('Pending pregnancies',g.pendingPregnancies?.length)]},
 {title:'Child support',icon:'👶',rows:[count('Child support agreements',(g.childSupportOrders?.length||0)+(g.divorceObligations||[]).filter(o=>o.childIds?.length).length),currency('Support paid this year',(g.childSupportOrders||[]).reduce((n,o)=>n+(o.lastYear===g.year?o.lastPaid||0:0),0)),currency('Support received this year',(g.childSupportOrders||[]).reduce((n,o)=>n+(o.lastYear===g.year?o.lastReceived||0:0),0)),currency('Child support arrears',(g.childSupportOrders||[]).reduce((n,o)=>n+(o.arrears||0),0))]},
 {title:'Daily life & circumstances',icon:'🌍',rows:[percent('Energy',g.realism?.energy),percent('Stress',g.realism?.stress),percent('Burnout',g.realism?.burnout),percent('Mobility',g.realism?.mobility),percent('Public reputation',g.realism?.reputation),percent('Work performance',g.realism?.career?.performance),text('Economic cycle',g.realism?.economy?.phase),percent('Inflation',(g.realism?.economy?.inflation||0)*100),percent('Unemployment',(g.realism?.economy?.unemployment||0)*100),text('Residence',g.realism?.housing?.type),currency('Unpaid rent',g.realism?.housingArrears),currency('Unpaid care costs',g.realism?.careArrears),count('Persistent conditions',g.realism?.conditions?.length),count('Kept promises',g.realism?.promises?.filter(p=>p.status==='fulfilled').length),count('Broken promises',g.realism?.promises?.filter(p=>p.status==='broken').length)]},
 {title:'Skills & personality',icon:'📚',rows:[...skillNames.map(k=>percent(k,g.skills?.[k])),text('Personality traits',g.traits?.join(', ')),count('Achievements',g.achievements?.length),text('Current challenge',g.challenge?.status),count('Family records',Object.keys(g.familyTree||{}).length),currency('Unpaid country budget',g.economyArrears),text('Lifestyle',g.lifestyle||'Balanced')]},
  {title:'Character & abilities',icon:'🧠',rows:[text('Favourite skill',g.skill),...Object.entries(g.stats||{}).filter(([key,value])=>!basicStats.some(s=>s.key===key)&&typeof value==='number').map(([key,value])=>percent(key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()),value)),count('Diagnosed health conditions',(g.healthConditions||[]).filter(c=>c.diagnosed).length),text('Sterilization',g.sterilized?'Recorded':'Not sterilized')]},
  {title:'Education',icon:'🎓',rows:[text('Qualification',['No qualification','High school / vocational','University degree','Graduate degree'][education]||g.education),text('Education status',g.educationStatus||g.education||'Not enrolled'),percent('School grade',g.schoolRecord?.grade),text('University course',g.universityCourse),text('University GPA',g.universityGpa==null?'Not recorded':`${number(g.universityGpa)} / 4`),count('University credits',g.universityCreditsCompleted),count('University years completed',g.universityYearsCompleted),percent('Academic standing',g.universityStanding)]},
  {title:'Career & reputation',icon:'💼',rows:[text('Current role',g.job||g.career||'Not employed'),count('Years in current career',g.careerYears),currency('Annual salary',g.salary),percent('Career reputation',g.careerReputation),percent('Contract performance',g.fameContract?.performance),percent('Fame',g.fame??0),count('Recorded working years',p.serviceYears)]},
  {title:'Money & assets',icon:'💰',rows:[currency('Net worth',planningNetWorth(g)),currency('Cash',g.money),currency('Bank savings',g.bankBalance),currency('Outstanding loans',(g.loans||[]).reduce((s,l)=>s+(l.balance||0),0)),currency('Family support arrears',(g.divorceObligations||[]).reduce((s,o)=>s+(o.arrears||0),0)),count('Credit score',g.creditScore??680),count('Owned assets',(g.assets||[]).filter(a=>a.status==='owned').length),count('Investment positions',g.investments?.holdings?.length),currency('Lifetime income',g.lifetimeIncome),currency('Lifetime spending',g.lifetimeSpending),currency('Charitable donations',g.lifetimeDonations)]},
  {title:'Family & relationships',icon:'💛',rows:[text('Relationship',g.relationship||'Single'),percent('Partner bond',g.partner?.closeness),percent('Partner trust',g.partner?.trust),count('Living parents',parents.length),count('Living siblings',siblings.length),count('Living children',children.length),count('Friends',friends.length),percent('Average friendship bond',average(friends)),percent('Average bond with children',average(children)),count('Pets',(g.pets||[]).filter(p=>p.alive!==false).length),count('Recorded divorces',g.divorceHistory?.length)]},
  {title:'Retirement & legacy',icon:'🌅',rows:[text('Retirement status',g.retired?'Retired':'Not retired'),currency('Retirement savings',p.balance),percent('Salary contribution',(p.contributionRate||0)*100),currency('Estimated yearly state pension',estimate.state),currency('Estimated yearly savings draw',estimate.privateIncome),currency('Last pension payment',p.lastPayment),text('Will',g.will?`Signed at age ${g.will.signedAge??recordAge({year:g.will.signedYear},g)}`:'Not written'),count('Will beneficiaries',g.will?.beneficiaries?.length),count('Education plans',Object.keys(g.educationPlans||{}).length),currency('Reserved child education savings',Object.values(g.educationPlans||{}).reduce((s,plan)=>s+(plan.balance||0),0)),count('Business succession plans',Object.keys(g.businessSuccession||{}).length)]},
  {title:'Politics & public service',icon:'🏛️',rows:[text('Office',g.politicalOffice||'No elected office'),text('Party',g.politicalParty),text('Platform',g.politicalPlatform),percent('Public approval',g.publicApproval),percent('Coalition support',g.politicalCoalition),count('Campaigns',g.politicalCampaigns),count('Total public service years',g.politicalTotalServiceYears||g.politicalServiceYears),count('Bills passed',g.politicalBillsPassed),count('Years left in term',Math.max(0,(g.politicalTermEnds||g.year)-g.year))]},
  {title:'Social media',icon:'📱',rows:[count('Social accounts',accounts.length),count('Followers across social accounts',accounts.reduce((s,a)=>s+(a.followers||0),0)),count('Recorded social posts',posts.length),count('Views on recorded social posts',posts.reduce((s,post)=>s+(post.views||0),0)),currency('Social account earnings',accounts.reduce((s,a)=>s+(a.earnings||0),0)),count('Video channel followers',g.creatorProfile?.followers),count('Lifetime video views',g.creatorProfile?.totalViews),currency('Video channel earnings',g.creatorProfile?.earnings),percent('Video channel brand trust',g.creatorProfile?.brandReputation),count('Account strikes',g.creatorProfile?.strikes)]},
  {title:'Insurance & legal history',icon:'🛡️',rows:[count('Active insurance policies',policies.filter(policy=>policy.active&&policy.paidYear===g.year).length),currency('Annual active premiums',policies.filter(policy=>policy.active).reduce((s,policy)=>s+(policy.premium||0),0)),count('Recorded insurance claims',g.insurance?.claims?.length),currency('Recorded insurer payments',(g.insurance?.claims||[]).reduce((s,claim)=>s+(claim.covered||0),0)),count('Criminal record entries',g.criminalRecord?.length),count('Court cases',g.courtCases?.length),count('Civil cases',g.civilCases?.length),count('Custody years remaining',g.jail?.yearsRemaining)]},
 ];
 if(companies.length)groups.push({title:'Business ownership',icon:'🏢',rows:[count('Companies owned',companies.length),currency('Combined ownership value',companies.reduce((s,c)=>s+companyEquity(c),0)),count('Total employees',companies.reduce((s,c)=>s+(c.employees||0),0)),currency('Last annual revenue',companies.reduce((s,c)=>s+(c.lastYearRevenue||0),0)),currency('Last annual profit',companies.reduce((s,c)=>s+(c.lastYearProfit||0),0)),...companies.flatMap(c=>[percent(`${c.name} · Performance`,c.performance),percent(`${c.name} · Staff morale`,c.morale),percent(`${c.name} · Reputation`,c.reputation),count(`${c.name} · Generation`,c.generation||1)])]});
 return groups;
}
export default function FullStatsScreen({game}){
 const [search,setSearch]=useState('');const query=search.trim().toLowerCase();const groups=fullStatGroups(game).map(group=>({...group,rows:group.rows.filter(row=>!query||`${group.title} ${row.label} ${row.value}`.toLowerCase().includes(query))})).filter(group=>group.rows.length);
 const wellbeingQuery='well-being'.includes(query)?'':query;
 const showWellbeing=basicStats.some(stat=>stat.label.toLowerCase().includes(wellbeingQuery));
 return <div className="full-stats-content"><div className="full-stats-hero"><PersonPortrait person={game}/><div><small>YOUR COMPLETE LIFE RECORD</small><h2>{game.name}</h2><p>Age {game.age} · {game.country}</p></div></div><label className="full-stats-search">Find a stat<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search money, reputation, education…"/></label>{showWellbeing&&<section className="full-stats-section"><h3>🌿 Well-being</h3><CharacterStatBars stats={game.stats} search={wellbeingQuery}/></section>}{groups.map(group=><section className="full-stats-section" key={group.title}><h3>{group.icon} {group.title}</h3><dl className="full-stats-grid">{group.rows.map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></section>)}{!groups.length&&!showWellbeing&&<p className="full-stats-empty">No stats match “{search}”. Try a different search.</p>}<p className="full-stats-note">Values come from your current life’s records. “Not recorded” means that score has not been tracked yet.</p></div>;
}
