import CustodyPanel from './CustodyPanel.jsx';
import {recordAge} from './lifeRecords.js';
import {useFeedbackNotice} from './OutcomeFeedback.jsx';
import ChildSupportScreen from './ChildSupportScreen.jsx';
import React,{useState} from 'react';
import {PersonPortrait} from './RelationshipPortrait.jsx';
import {formatMoney as money} from './money.js';
import {funds,marry,divorce,divorceQuote,policyQuote,buyInsurance,pensionEstimate,setPensionRate,retire,saveEducationPlan,fundEducation,tutorChild,nominateSuccessor,educationPaths,companyEquity,spend} from './futurePlanning.js';
import './systems.css';
const tabs=['Marriage','Child Support','Insurance','Retirement','Children’s education','Family business'];
export default function FuturePlanningScreen({game,setGame,section}){
 const [tab,setTab]=useState(section||'Marriage');const [notice,setNotice]=useFeedbackNotice('');const [confirmation,setConfirmation]=useState('');
 const [prenup,setPrenup]=useState(true);const [weddingCost,setWeddingCost]=useState(2500);const [spouseShare,setSpouseShare]=useState(50);
 const [custody,setCustody]=useState('Shared');const [method,setMethod]=useState('Amicable');const [educationDrafts,setEducationDrafts]=useState({});const [successors,setSuccessors]=useState({});
 const available=funds(game);const active=section||tab;const quote=divorceQuote(game,custody,method);const pension=pensionEstimate(game);const p=game.pension||{};
 const run=(result,message)=>{if(result?.error){setNotice(result.error);return;}if(result?.state){setGame(result.state);setNotice(message);setConfirmation('');}};
 const eligibleChildren=(game.children||[]).filter(c=>c.alive!==false);
 const policyOffers=[policyQuote(game,'health'),policyQuote(game,'life'),...(game.assets||[]).filter(a=>a.status==='owned').flatMap(a=>[policyQuote(game,'auto',a.id),policyQuote(game,'home',a.id)])].filter(Boolean);
 const draftFor=child=>({path:game.educationPlans?.[child.id]?.path||'University',annualContribution:game.educationPlans?.[child.id]?.annualContribution||0,topup:1000,...educationDrafts[child.id]});
 const editChild=(id,field,value)=>setEducationDrafts(d=>({...d,[id]:{...(d[id]||{}),[field]:value}}));
 return <div className="game-system-screen future-planning-screen"><CustodyPanel game={game} setGame={setGame}/><div className="system-hero"><span>{active==='Insurance'?'🛡️':active==='Retirement'?'🌅':active==='Family business'?'🏢':active==='Children’s education'?'🎓':'💍'}</span><div><small>FAMILY & FUTURE</small><h2>{section||'Plan the next chapter'}</h2><p>Protect your household, plan your retirement, and prepare the next generation. These rules belong to the fictional game economy.</p></div></div>
  {!section&&<div className="planning-tabs" role="tablist" aria-label="Family planning sections">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>{setTab(t);setNotice('');}}>{t}</button>)}</div>}
  <div className="planning-balance"><span>Available funds</span><b>{money(available)}</b></div>
  {notice&&<div className="system-notice" role="status">{notice}</div>}
  {game.age<18&&<div className="system-notice">Financial planning actions unlock at age 18. You can explore the options now.</div>}
  {active==='Child Support'&&<ChildSupportScreen game={game} setGame={setGame} onOpenPlanning={()=>setTab('Marriage')}/>}
  {active==='Marriage'&&<>
   <section className="system-card"><h3>{game.marriage?'Your marriage agreement':'Marriage & prenups'}</h3>
    {!game.partner?<div className="system-empty">Start a relationship before planning a wedding.</div>:<><div className="planning-person"><PersonPortrait person={game.partner}/><div><b>{game.partner.name}</b><small>{game.marriage?`Married at age ${recordAge(game.marriage,game)}`:`Partner · Age ${game.partner.age}`}</small></div></div>
    {game.marriage?<><p>{game.marriage.prenup?`Your prenup protects ${money(game.marriage.protectedWealth)} of premarital wealth and leaves ${game.marriage.spouseShare}% of shared growth to your spouse if you divorce.`:'You married without a prenup. A divorce divides the net estate equally.'}</p><p>Your spouse contributes {money(game.marriage.spouseIncome)} to the household each year.</p></>:<><div className="planning-form"><label>Wedding<select value={weddingCost} onChange={e=>setWeddingCost(Number(e.target.value))}><option value={2500}>Civil ceremony · $2,500</option><option value={10000}>Family wedding · $10,000</option><option value={50000}>Grand celebration · $50,000</option></select></label><label>Agreement<select value={prenup?'prenup':'shared'} onChange={e=>setPrenup(e.target.value==='prenup')}><option value="prenup">Prenup · $1,500 legal fee</option><option value="shared">No prenup · pool your savings</option></select></label>{prenup&&<label>Spouse’s share of marital growth<select value={spouseShare} onChange={e=>setSpouseShare(Number(e.target.value))}><option value={30}>30%</option><option value={50}>50%</option><option value={70}>70%</option></select></label>}</div><p>A prenup protects premarital wealth and future inheritances. Without one, your spouse’s savings join your bank account and the combined estate is shared. Both partners agree to the selected terms in this simulation.</p><button className="system-primary-action" disabled={!game.alive||game.age<18||game.partner.age<18||available<weddingCost+(prenup?1500:0)} onClick={()=>setConfirmation('marriage')}>Review wedding · {money(weddingCost+(prenup?1500:0))}</button></>}
   </>}
   </section>
   {game.marriage&&quote&&<section className="system-card"><h3>Divorce & settlement</h3><div className="planning-form"><label>Process<select value={method} onChange={e=>setMethod(e.target.value)}><option>Amicable</option><option>Court</option></select></label><label>Custody of minor children<select value={custody} onChange={e=>setCustody(e.target.value)}><option>Shared</option><option>You</option><option>Other parent</option></select></label></div><div className="planning-metrics"><article><small>Spouse settlement</small><b>{money(quote.settlement)}</b></article><article><small>Legal fees</small><b>{money(quote.legalFee)}</b></article><article><small>Annual alimony</small><b>{money(quote.alimony)}</b><small>{quote.alimonyYears} years</small></article><article><small>Annual child support</small><b>{money(quote.childSupport)}</b><small>{quote.childSupportReceived?`Receive ${money(quote.childSupportReceived)} with your custody`: 'Recalculated as children turn 18'}</small></article></div><p>Cash and savings pay first. If needed, property, investments, business shares, and retirement assets are sold or transferred to settle the bill. Support obligations continue after separation.</p><button className="system-primary-action planning-danger" disabled={!game.alive} onClick={()=>setConfirmation('divorce')}>Review divorce settlement</button></section>}
   {(game.divorceObligations||[]).some(o=>o.yearsRemaining>0||o.childSupport>0||o.arrears>0)&&<section className="system-card"><h3>Ongoing family support</h3>{(game.divorceObligations||[]).map(o=><article className="planning-history" key={o.id}><b>{o.custody} custody · Alimony {money(o.alimony)} / year for {o.yearsRemaining} more years</b><p>Child support: {money(o.childSupport)} / year · Arrears: {money(o.arrears||0)}</p>{o.arrears>0&&<button disabled={!game.alive||available<o.arrears} onClick={()=>{const paid=spend(game,o.arrears,'Support arrears paid');if(paid)run({state:{...paid,divorceObligations:paid.divorceObligations.map(d=>d.id===o.id?{...d,arrears:0}:d)}},'Your support arrears were paid.');}}>Pay arrears · {money(o.arrears)}</button>}</article>)}</section>}
   {(game.divorceHistory||[]).length>0&&<section className="system-card"><h3>Settlement history</h3>{game.divorceHistory.map((d,i)=><p key={i}>Age {recordAge(d,game)} · {d.spouse} · {money(d.settlement)} settlement · {d.custody} custody</p>)}</section>}
  </>}
  {active==='Insurance'&&<>
   <section className="system-card"><h3>Protect your health and assets</h3><p>Premiums renew automatically each year. A policy lapses if the premium cannot be paid. Health coverage applies to hospital treatment; vehicle and home cover apply to repairs. Routine upkeep, elective cosmetic procedures, and sterilization are excluded.</p><div className="planning-policy-list">{policyOffers.map(offer=>{const policy=game.insurance?.policies?.find(p=>p.id===offer.id);const covered=policy?.active&&policy.paidYear===game.year;const price=policy?.paidYear===game.year?0:offer.premium;return <article className="planning-policy" key={offer.id}><div><b>{offer.name}</b><small>Premium {money(offer.premium)} / year · Deductible {money(offer.deductible)}</small><small>{offer.kind==='life'?`Estate benefit ${money(offer.limit)} on life ending`:`Covers ${Math.round(offer.rate*100)}% after deductible · Annual limit ${money(offer.limit)}`}</small>{covered&&<small>Active · Claims paid this year: {money(policy.claimsPaid||0)}</small>}</div>{covered?<button disabled={!game.alive} onClick={()=>{setGame(g=>({...g,insurance:{...g.insurance,policies:g.insurance.policies.map(p=>p.id===offer.id?{...p,active:false}:p)}}));setNotice('Policy cancelled. Paid premiums are not refunded.');}}>Cancel policy</button>:<button disabled={!game.alive||game.age<18||available<price||offer.kind==='life'&&game.age>70&&price>0} onClick={()=>run(buyInsurance(game,offer.kind,offer.assetId),'Your policy is active. Premiums renew each year.')}>{price===0?'Reactivate':policy?'Renew':'Buy'} · {money(price)}</button>}</article>;})}</div></section>
   <section className="system-card"><h3>Claims history</h3>{(game.insurance?.claims||[]).length?(game.insurance.claims||[]).slice(0,10).map((c,i)=><article key={i} className="planning-history"><b>{c.label} · Age {recordAge(c,game)}</b><p>Bill {money(c.bill)} · Insurer {money(c.covered)} · You paid {money(c.paid)}</p></article>):<div className="system-empty">Covered treatments and repairs will appear here after you use them.</div>}</section>
  </>}
  {active==='Retirement'&&<>
   <section className="system-card"><h3>Your retirement plan</h3><div className="planning-metrics"><article><small>Retirement savings</small><b>{money(p.balance||0)}</b></article><article><small>Recorded working years</small><b>{p.serviceYears||0}</b></article><article><small>Estimated state pension</small><b>{money(pension.state)} / year</b></article><article><small>Estimated savings draw</small><b>{money(pension.privateIncome)} / year</b></article></div><p>Choose a percentage of employment pay to save each year. Your employer matches up to 3%, and retirement savings grow by 4% annually in this simulation. Benefits require ten recorded working years; the state pension is based on career earnings and service.</p><label className="planning-single-label">Annual contribution<select value={Math.round((p.contributionRate||0)*100)} disabled={!game.alive||game.age<18} onChange={e=>run(setPensionRate(game,Number(e.target.value)),'Your pension contribution rate was updated.')}>{[0,5,10,15,20].map(rate=><option key={rate} value={rate}>{rate}% of employment salary</option>)}</select></label><p>Retirement opens at age 60. It ends your job and salary. You then receive the state benefit plus a 4% draw from your remaining retirement savings each year.</p>{game.retired?<div className="system-notice">Retired since {p.retiredYear} · Last annual pension {money(p.lastPayment||0)}</div>:<button className="system-primary-action" disabled={!game.alive||game.age<60} onClick={()=>setConfirmation('retire')}>{game.age<60?'Retire at age 60':'Review retirement'}</button>}</section>
  </>}
  {active==='Children’s education'&&<>
   <section className="system-card"><h3>Invest in your children’s future</h3><p>Reserve savings for each child. Accounts grow 3% per year and accept automatic annual contributions. From age 18, a funded course progresses each year; children with at least 75 smarts receive a 25% merit scholarship. Unused savings belong to that child.</p>{!eligibleChildren.length&&<div className="system-empty">Welcome or adopt a child to create an education plan.</div>}{eligibleChildren.map(child=>{const plan=game.educationPlans?.[child.id];const draft=draftFor(child);return <article className="planning-child" key={child.id}><div className="planning-person"><PersonPortrait person={child}/><div><b>{child.name} · Age {child.age}</b><small>Smarts {child.smarts??55}% · {child.education||'Not enrolled in a planned course'}</small></div></div><div className="planning-metrics"><article><small>Reserved balance</small><b>{money(plan?.balance||0)}</b></article><article><small>Course progress</small><b>{plan?.yearsCompleted||0} / {educationPaths[draft.path].years} years</b><small>{plan?.completed?'Graduated':`${money(educationPaths[draft.path].target)} tuition target`}</small></article></div><div className="planning-form"><label>Path<select value={draft.path} disabled={plan?.started} onChange={e=>editChild(child.id,'path',e.target.value)}><option>University</option><option>Vocational</option></select></label><label>Automatic annual saving<input type="number" min="0" max="100000000" value={draft.annualContribution} onChange={e=>editChild(child.id,'annualContribution',e.target.value)}/></label></div><button disabled={!game.alive||game.age<18} onClick={()=>run(saveEducationPlan(game,child.id,draft),'Education plan saved.')}>Save education plan</button>{child.age>=6&&child.age<18&&<button disabled={!game.alive||game.age<18||available<500||child.tutoringYear===game.year} onClick={()=>run(tutorChild(game,child.id),'Tutoring improved your child’s smarts.')}>Tutoring · $500 · +6 smarts</button>}{plan&&<div className="planning-topup"><label>One-time contribution<input type="number" min="1" value={draft.topup} onChange={e=>editChild(child.id,'topup',e.target.value)}/></label><button disabled={!game.alive||game.age<18||available<Number(draft.topup)||Number(draft.topup)<=0} onClick={()=>run(fundEducation(game,child.id,draft.topup),'Funds reserved for this child.')}>Add savings</button></div>}</article>;})}</section>
  </>}
  {active==='Family business'&&<>
   <section className="system-card"><h3>Keep your business in the family</h3><p>Choose a child to inherit your company ownership. This business nomination takes priority over the general cash shares in your will. The company keeps its cash, debts, staff, history, and your ownership percentage; it is removed from the estate’s cash distribution to avoid counting it twice.</p>{!(game.companies||[]).length&&<div className="system-empty">Start or acquire a company in Career to create a family business plan.</div>}{(game.companies||[]).map(company=>{const plan=game.businessSuccession?.[company.id];const selected=successors[company.id]||plan?.childId||eligibleChildren[0]?.id||'';return <article className="planning-child" key={company.id}><h3>{company.name}</h3><p>Your equity: {money(companyEquity(company))} · Ownership {company.ownership??100}% · Generation {company.generation||1}</p>{company.ownerName&&<p>Family owner: {company.ownerName}{company.professionalManager?' · A professional manager is running operations.':''}</p>}<label className="planning-single-label">Nominated heir<select disabled={!eligibleChildren.length} value={selected} onChange={e=>setSuccessors(s=>({...s,[company.id]:e.target.value}))}>{!eligibleChildren.length&&<option value="">No living children</option>}{eligibleChildren.map(c=><option key={c.id} value={c.id}>{c.name} · Age {c.age}</option>)}</select></label><button disabled={!game.alive||game.age<18||!selected} onClick={()=>run(nominateSuccessor(game,company.id,selected),'The family business successor was recorded.')}>Save business successor</button>{plan&&<p>Nominated: {plan.childName} · Age {recordAge(plan,game)}</p>}{company.inheritedYear&&<button disabled={!game.alive||game.age<18||!!game.job} onClick={()=>{setGame(g=>({...g,job:'Founder & CEO',career:'Family business owner',salary:Math.min(120000,Math.max(18000,Math.round(company.valuation*.015))),companies:g.companies.map(c=>c.id===company.id?{...c,professionalManager:false,professionalManagerSalary:0}:c)}));setNotice('You took over day-to-day management as CEO.');}}>{game.age<18?'Take leadership at age 18':'Take over as CEO'}</button>}</article>;})}</section>
  </>}
  {confirmation&&<div className="dialog-backdrop family-modal-backdrop" onClick={()=>setConfirmation('')}><section className="confirm-dialog family-modal" role="dialog" aria-modal="true" aria-labelledby="planning-confirm-title" onClick={e=>e.stopPropagation()}><h2 id="planning-confirm-title">{confirmation==='marriage'?'Confirm your wedding':confirmation==='divorce'?'Confirm divorce settlement':'Confirm retirement'}</h2><p>{confirmation==='marriage'?`Marry ${game.partner?.name} for ${money(weddingCost+(prenup?1500:0))}. ${prenup?'Both partners sign the selected prenup.':'Your spouse’s savings join your household account.'}`:confirmation==='divorce'?`End your marriage and pay ${money((quote?.settlement||0)+(quote?.legalFee||0))}. Assets may be sold to cover this settlement. Annual alimony: ${money(quote?.alimony||0)}; child support: ${money(quote?.childSupport||0)}. Custody: ${custody}.`:`Leave your job and start retirement. Your estimated pension is ${money(pension.total)} per year; payments begin at your next age-up.`}</p><div className="family-confirm-actions"><button onClick={()=>setConfirmation('')}>Cancel</button><button className="confirm-new" onClick={()=>confirmation==='marriage'?run(marry(game,{prenup,weddingCost,spouseShare}),'You are now married.'):confirmation==='divorce'?run(divorce(game,custody,method),'Divorce and settlement completed.'):run(retire(game),'You retired. Your first pension is due next year.')}>Confirm {confirmation==='marriage'?'marriage':confirmation==='divorce'?'divorce':'retirement'}</button></div></section></div>}
 </div>;
}
