import {spend,funds} from './futurePlanning.js';
import {clamp,enrichmentState,enrich,note,success,failure} from './enrichmentCore.js';
import {simulationSettings} from './simulationSettings.js';
export const neighbourhoods={Budget:{quality:45,factor:.8,commute:8},Balanced:{quality:65,factor:1,commute:5},Family:{quality:80,factor:1.2,commute:4},Premium:{quality:92,factor:1.55,commute:3}};
export const transportModes={Walking:{hours:1.6,cost:0},Bicycle:{hours:1.15,cost:150},Transit:{hours:1,cost:600},Car:{hours:.65,cost:1200},Remote:{hours:0,cost:0}};
export const renovationOptions={Kitchen:{rate:.02,quality:8,condition:12},Insulation:{rate:.012,quality:5,condition:8},Accessibility:{rate:.015,quality:7,condition:10},Garden:{rate:.008,quality:5,condition:5}};
export function housingLifeState(g){return {...enrichmentState(g).housing};}
export function neighbourhoodFactor(g){const h=housingLifeState(g);return neighbourhoods[h.neighbourhood]?.factor||1;}
const localHome=(g,id)=>(g.assets||[]).find(a=>a.id===id&&a.category==='Homes'&&!a.rentedOut&&(!a.country||a.country===(g.educationStudy?.country||g.country)));
export function housingAction(g,action,value){if(!g.alive||g.age<18)return failure(g,'Independent housing decisions open at 18.');let h=housingLifeState(g),next=g;const r=g.realism||{},home=r.housing||{};
 if(action==='neighbourhood'){const area=neighbourhoods[value];if(!area)return failure(g,'Choose a neighbourhood.');if(home.type==='owned'||g.livingArrangement?.assetId)return failure(g,'Your property stays in its neighbourhood. Move to another home first.');if(h.moveYear===g.year)return failure(g,'You have already moved this year.');const fee=Math.round(1200*area.factor*simulationSettings(g).cost);next=spend(g,fee,'Neighbourhood move and deposit');if(!next)return failure(g,`Save $${fee.toLocaleString()} for the move.`);h={...h,neighbourhood:value,moveYear:g.year,roommate:null};next={...next,livingArrangement:null,realism:{...r,housing:{...home,type:home.type==='family'?'shared':home.type||'shared',country:g.country,assetId:null,quality:area.quality,commute:area.commute,condition:80,changedYear:g.year}}};}
 else if(action==='home'){const a=localHome(g,value);if(!a)return failure(g,'Choose a local home that is not let to tenants.');next=spend(g,750,'Move to an existing home');if(!next)return failure(g,'Save $750 for moving costs.');h={...h,neighbourhood:a.neighbourhood||'Balanced',roommate:null,moveYear:g.year};next={...next,livingArrangement:{type:a.status==='owned'?'buy':'rent',assetId:a.id},realism:{...r,housing:{type:a.status==='owned'?'owned':'asset',assetId:a.id,sourceAssetId:a.id,country:g.country,quality:a.homeQuality||70,condition:a.condition??100,commute:5,changedYear:g.year}}};}
 else if(action==='transport'){const mode=transportModes[value];if(!mode)return failure(g,'Choose a travel mode.');if(value==='Car'&&(!(g.assets||[]).some(a=>(a.category==='Cars'||/car/i.test(a.kind||''))&&a.status==='owned'&&(!a.country||a.country===g.country))||g.driversLicense?.status!=='licensed'||g.driversLicense.country!==g.country))return failure(g,'Driving requires a local car and a valid local license.');if(value==='Remote'&&!g.realism?.career?.remote)return failure(g,'Your current job does not permit remote work.');h={...h,transport:value};next={...g,realism:{...r,housing:{...home,commute:(neighbourhoods[h.neighbourhood]?.commute||5)*mode.hours}}};}
 else if(action==='roommate'){if(home.type==='family')return failure(g,'Move into your own accommodation before inviting a roommate.');if(h.roommate)return failure(g,'You already share your home with a roommate.');const candidates=[{id:'roommate-avery',name:'Avery',reliability:90,tidiness:85},{id:'roommate-jules',name:'Jules',reliability:70,tidiness:65},{id:'roommate-kai',name:'Kai',reliability:55,tidiness:40}];const p=candidates.find(p=>p.id===value);if(!p)return failure(g,'Choose a roommate.');h={...h,roommate:{...p,sinceYear:g.year}};}
 else if(action==='end-roommate'){if(!h.roommate)return failure(g,'There is no roommate agreement.');h={...h,roommate:null};}
 else return failure(g,'Choose an available housing action.');
 return success(enrich(next,'housing',h),action==='transport'?`You switched your commute to ${value.toLowerCase()}.`:action==='roommate'?`${h.roommate.name} moved in. They contribute half of rent when their budget permits.`:action==='end-roommate'?'Your roommate agreement ended.':`You settled into ${action==='home'?'your selected home':`the ${value.toLowerCase()} neighbourhood`}.`,'Housing & daily life','🏡');}
export function renovateHome(g,id,kind){const a=localHome(g,id),option=renovationOptions[kind];if(!g.alive||g.age<18||!a||a.status!=='owned'||!option)return failure(g,'Renovations require a local home you own.');if(a.renovation?.status==='In progress')return failure(g,'Complete the current project before starting another.');const cost=Math.max(800,Math.round((a.value||0)*option.rate*simulationSettings(g).cost)),next=spend(g,cost,`${kind} renovation`);if(!next)return failure(g,`This project needs $${cost.toLocaleString()}.`);return success({...next,assets:next.assets.map(p=>p.id===id?{...p,renovation:{kind,cost,finishYear:g.year+1,status:'In progress',...option}}:p)},`${kind} work started at ${a.name}. It finishes at the next age-up; the project transfers with the property if you sell or gift it.`,'Home renovation','🛠️');}
export function advanceHousingLife(g,random=Math.random){let next=g;const completed=[];const h=housingLifeState(g);next={...next,assets:(g.assets||[]).map(a=>{const p=a.renovation;if(!p||p.status!=='In progress'||p.finishYear>g.year)return a;completed.push(`${p.kind} renovations at ${a.name} are complete.`);return {...a,value:(a.value||0)+Math.round(p.cost*.65),condition:clamp((a.condition??80)+p.condition),homeQuality:clamp((a.homeQuality||70)+p.quality),renovation:{...p,status:'Complete'},renovationHistory:[...(a.renovationHistory||[]),{...p,completedYear:g.year}]};})};for(const text of completed)next=note(next,text,'Home renovation','🏡');
 if(g.age<18)return next;const mode=transportModes[h.transport]||transportModes.Transit;if((g.job||g.educationStudy||g.educationStatus==='enrolled')&&mode.cost){const due=Math.round(mode.cost*simulationSettings(g).cost),paid=spend(next,Math.min(due,funds(next)),'Annual commuting');next=paid||next;if(funds(g)<due)next=note(next,'Your transport budget was too small; the commute became more stressful.','Daily life','🚌');}
 if(h.roommate){const housing=g.realism?.housing;if(housing?.type==='family')return enrich(next,'housing',{...h,roommate:null});const pays=random()<h.roommate.reliability/100;const rent=g.realism?.lastHousingCost||0;const reimbursement=pays?Math.round(rent*.5):0;if(reimbursement)next={...next,bankBalance:(next.bankBalance||0)+reimbursement,lifetimeSpending:Math.max(0,(next.lifetimeSpending||0)-reimbursement),transactions:[{age:g.age,year:g.year,label:`Roommate rent contribution · ${h.roommate.name}`,amount:reimbursement},...(next.transactions||[])]};next=enrich(next,'housing',{...h,roommate:{...h.roommate,paidYear:g.year,paid:reimbursement}});next=note(next,pays?`${h.roommate.name} contributed $${reimbursement.toLocaleString()} toward rent.`:`${h.roommate.name} missed their rent contribution. You covered the household bills.`,'Roommate','🏠');}
 return next;}
