import {simulationSettings} from './simulationSettings.js';
import {regionalBudgets,regionalIncomeTax} from './regions.js';
import {spend,planningNetWorth} from './futurePlanning.js';
export const skillNames=['Charisma','Discipline','Cooking','Music','Technology'];
export const traitDescriptions={Kind:'Builds relationship bonds faster.',Ambitious:'Improves career prospects but puts more pressure on happiness.',Curious:'Learns faster and enjoys studying.',Outgoing:'Improves dating and social confidence.',Frugal:'Reduces everyday living costs.',Resilient:'Softens annual happiness losses.'};
const clamp=n=>Math.max(0,Math.min(100,n));
export function normalizeLife(g){return {...g,characterId:g.characterId||`life-${g.name}-${g.year-g.age}`,skills:Object.fromEntries(skillNames.map(k=>[k,clamp(Number(g.skills?.[k]??(g.skill===k?20:10))||0)])),traits:g.traits||['Kind','Curious'],achievements:g.achievements||[],familyTree:g.familyTree||{}};}
export function trainSkill(input,key,lesson=false){const g=normalizeLife(input);if(!skillNames.includes(key)||g.age<6||!g.alive||(g.realism?.energy??80)<15)return input;const sessions=g.trainingYear===g.year?g.trainingSessions||{}:{};if((sessions[key]||0)>=2||g.skills[key]>=100)return input;const paid=lesson?spend(g,250,`${key} lesson`):g;if(!paid)return input;const gain=(lesson?8:3)+(g.traits.includes('Curious')?1:0);return {...paid,...(g.realism?{realism:{...g.realism,energy:clamp(g.realism.energy-4)}}:{}),skills:{...g.skills,[key]:clamp(g.skills[key]+gain)},trainingYear:g.year,trainingSessions:{...sessions,[key]:(sessions[key]||0)+1},stats:{...g.stats,happiness:clamp(g.stats.happiness+1)},log:[{year:g.year,age:g.age,text:`You trained ${key.toLowerCase()} and reached ${clamp(g.skills[key]+gain)}/100.`,tag:'Skill training',icon:'📚'},...(g.log||[])]};}
export function careerBonus(g,title=''){const s=normalizeLife(g).skills;return s.Discipline*.0007+(/tech|developer|engineer/i.test(title)?s.Technology*.001:/music|singer/i.test(title)?s.Music*.001:/chef|cook/i.test(title)?s.Cooking*.001:s.Charisma*.0005)+(g.traits?.includes('Ambitious')?.04:0);}
export function socialBonus(g){return (g.skills?.Charisma||0)*.001+(g.traits?.includes('Outgoing')?.04:0)+((g.realism?.reputation??50)-50)*.001;}
export function bondBonus(g){return g.traits?.includes('Kind')?2:0;}
// Fictional annual USD game budgets. These are deliberately simplified, not real tax tables.
export const countryBudgets={...regionalBudgets,'United States':[12000,.22],'Nigeria':[2400,.12],'United Kingdom':[13500,.27],'Canada':[12000,.25],'Australia':[14000,.25],'Japan':[10500,.24],'Brazil':[4800,.18],'India':[3000,.15],'France':[13000,.3],'Germany':[12500,.3],'Mexico':[4800,.16],'South Korea':[10000,.23],'China':[6000,.2],'South Africa':[5000,.18],'Kenya':[2800,.12],'Ghana':[2600,.12],'Egypt':[3000,.14],'Italy':[10500,.27],'Spain':[9500,.25],'Philippines':[3200,.14],'New Zealand':[12500,.25],'Ireland':[13000,.27]};
export const lifestyles={Frugal:.65,Balanced:1,Comfortable:1.6,Luxury:3};
export function economyQuote(g,income=0){const [base,rate]=countryBudgets[g.country]||[8000,.2];const taxable=Math.max(0,income-10000);const tax=regionalIncomeTax(g,income)??Math.round(Math.min(taxable,40000)*rate+Math.max(0,taxable-40000)*Math.min(.48,rate+.1));const living=g.age<18?0:Math.round(base*simulationSettings(g).cost*(g.realism?.economy?.priceIndex||1)*(g.realism?.diet==='Nutritious'?1.08:g.realism?.diet==='Convenience'?1.05:1)*(lifestyles[g.lifestyle]||1)*(g.traits?.includes('Frugal')?.85:1)*(1-(g.skills?.Cooking||0)*.001));return {income:Math.max(0,income),tax,living,total:tax+living,rate};}
const badgeRules=[['adult','Independent adult',g=>g.age>=18],['graduate','University graduate',g=>g.educationLevel>=2],['millionaire','Millionaire',g=>planningNetWorth(g)>=1e6],['parent','New generation',g=>g.children?.length>0],['founder','Business founder',g=>g.companies?.length>0],['public-service','Public servant',g=>!!g.politicalOffice],['generous','Community supporter',g=>g.lifetimeDonations>=10000],...skillNames.map(k=>[`master-${k}`,`${k} master`,g=>g.skills?.[k]>=100])];
export const challenges=[{id:'learn',name:'Dedicated learner',description:'Reach 60 in any trainable skill within 10 years.',years:10},{id:'wealth',name:'Build a nest egg',description:'Reach $100,000 net worth within 15 years.',years:15},{id:'health',name:'Healthy chapter',description:'Keep health at 80 or above for five consecutive age-ups.',years:10}];
export function updateGoals(g){const earned=badgeRules.filter(([id,,test])=>!g.achievements?.some(a=>a.id===id)&&test(g));let challenge=g.challenge;if(challenge?.status==='active'){const success=challenge.id==='learn'?Object.values(g.skills||{}).some(n=>n>=60):challenge.id==='wealth'?planningNetWorth(g)>=100000:challenge.streak>=5;if(success||g.year>challenge.deadline)challenge={...challenge,status:success?'completed':'failed',finishedYear:g.year};}if(challenge?.status==='completed'&&!g.achievements?.some(a=>a.id===`challenge-${challenge.id}`))earned.push([`challenge-${challenge.id}`,`${challenges.find(c=>c.id===challenge.id)?.name||'Life'} challenge completed`]);if(!earned.length&&challenge===g.challenge)return g;return {...g,challenge,achievements:[...(g.achievements||[]),...earned.map(([id,name])=>({id,name,year:g.year,age:g.age}))]};}
export function syncTree(g){const tree={...(g.familyTree||{})};const me=g.characterId;const record=(p,extra={})=>{const id=p.id||me;tree[id]={...tree[id],...p,...extra};};record({id:me,name:g.name,age:g.age,gender:g.gender,avatarSeed:g.avatarSeed||g.avatar,alive:g.alive},{parentIds:(g.family?.parents||[]).map(p=>p.id),childIds:(g.children||[]).map(p=>p.id),career:g.job||g.career,realismSummary:g.realism?{reputation:g.realism.reputation,healthConditions:g.realism.conditions,careerHistory:g.realism.career?.history||[],promises:g.realism.promises}:null,skills:g.skills,traits:g.traits,achievements:g.achievements,history:(g.log||[]).filter(e=>e.age!=null&&(e.actorId===me||(!Object.hasOwn(e,'actorId')&&(e.year==null||e.year>=(g.generationStartYear??g.year-g.age))))).slice(0,40)});for(const p of g.family?.parents||[])record(p);for(const p of g.family?.siblings||[])record(p);for(const p of g.children||[])record(p,{parentIds:[me,...(p.otherParentId?[p.otherParentId]:g.partner?[g.partner.id]:[])]});for(const p of g.friends||[])if((g.children||[]).some(c=>c.otherParentId===p.id))record(p);if(g.partner)record(g.partner);return {...g,familyTree:tree};}
export function nextGeneration(g,child){const archived=syncTree(normalizeLife(g));return {publicCareer:null,fameContract:null,enrichment:null,enrichmentYear:null,schoolAcademicGrade:null,lifeTimeline:[],timelinePhotos:[],legacyTimelines:[...(g.legacyTimelines||[]),{name:g.name,generation:g.generation||1,events:g.lifeTimeline||g.log||[],photos:g.timelinePhotos||[]}],estatePlan:null,criminalRecordsByCountry:{},immigrationStatus:null,illegalMigrationAttemptYear:null,generation:(g.generation||1)+1,lifeSummary:null,depthYear:null,educationStudy:null,careerProgress:null,personalLoans:[],deferredConsequences:[],depthEventHistory:[],classmates:[],schoolClubs:[],schoolClique:null,fameHistory:[],fameReviewYear:null,activeVisit:null,pendingPregnancies:[],childSupportOrders:[],childSupportYear:null,nightlife:null,casualEncounters:null,nightlifeYear:null,lastEmploymentIncome:0,characterId:child.id,generationStartYear:g.year,familyTree:archived.familyTree,skills:normalizeLife({...child,skill:child.skill}).skills,traits:Array.isArray(child.traits)?child.traits:['Kind','Curious'],achievements:[],challenge:null,trainingYear:null,trainingSessions:{},economyYear:null,economyHistory:[],economyArrears:0,lifestyle:'Balanced'};}
export function advanceLifeSystems(input,income=0){let g=normalizeLife(input);if(!g.alive||g.economyYear===g.year)return input;const quote=economyQuote(g,income);const due=quote.total+(g.economyArrears||0);const available=Math.max(0,g.money||0)+Math.max(0,g.bankBalance||0);const amount=Math.min(due,available);const paid=amount?spend(g,amount,'Annual taxes and living costs'):g;let challenge=g.challenge;if(challenge?.status==='active'&&challenge.id==='health')challenge={...challenge,streak:g.stats.health>=80?(challenge.streak||0)+1:0};g={...paid,challenge,economyYear:g.year,economyArrears:due-amount,economyHistory:[{...quote,paid:amount,arrears:due-amount,year:g.year,country:g.country},...(g.economyHistory||[])].slice(0,80),stats:{...g.stats,happiness:clamp(g.stats.happiness+(g.traits.includes('Ambitious')?-1:0)+(g.traits.includes('Resilient')?1:0))},log:[{year:g.year,age:g.age,text:`Annual budget: taxes ${quote.tax}, living costs ${quote.living} USD.${due>amount?` Unpaid balance: ${due-amount} USD.`:''}`,tag:'Annual budget',icon:'🧾'},...(paid.log||[])]};return syncTree(updateGoals(g));}
