import {syncPublicAudience} from './fameAudience.js';
import {advanceEnrichment} from './lifeEnrichment.js';
import {academicGrade} from './simulationSettings.js';
import {peopleInLife,updatePerson} from './gameFixes.js';
import {spend,planningNetWorth} from './futurePlanning.js';
import {recordVisaChance,localizeCriminalRecord} from './criminalConsequences.js';
const clamp=n=>Math.max(0,Math.min(100,n));
export const depthLog=(g,text,tag='Life decisions',icon='🧭')=>({...g,log:[{year:g.year,age:g.age,text,tag,icon},...(g.log||[])]});
export function locateLife(g){let next=g;for(const p of peopleInLife(g)){if(!p.country)next=updatePerson(next,p.id,n=>({...n,country:g.country}));}if((g.assets||[]).some(a=>!a.country))next={...next,assets:g.assets.map(a=>a.country?a:{...a,country:g.country})};return next;}
export const currentCountry=g=>g.educationStudy?.country||g.country;
export const nearby=(g,p)=>!p.country||p.country===currentCountry(g)||g.activeVisit?.personId===p.id&&g.activeVisit.year===g.year;
export const localAsset=(g,a)=>!a.country||a.country===currentCountry(g)||!['Homes','Vehicles','Cars'].includes(a.category)&&!String(a.kind).toLowerCase().includes('car');
export function remember(g,id,action,detail,delta=0){return updatePerson(g,id,p=>({...p,closeness:clamp((p.closeness??50)+delta),memory:[...(p.memory||[]),{year:g.year,age:g.age,action,detail}]}));}
export function relationshipInteraction(g,id,action,amount=100){const p=peopleInLife(g).find(n=>n.id===id);if(!g.alive||!p)return {game:g,error:'Choose a living person.'};let next=g,delta=0,text='';
 if(action==='call'){delta=2;text='You called and caught up over the phone.';if(p.lastCallYear===g.year)return {game:g,error:'You have already had your meaningful call this year.'};next=updatePerson(next,id,n=>({...n,lastCallYear:g.year}));}
 else if(action==='visit'){if(nearby(g,p))return {game:g,error:'You are already nearby.'};next=spend(g,1800,`Trip to visit ${p.name}`);if(!next)return {game:g,error:'Save $1,800 for flights and accommodation.'};next={...next,activeVisit:{personId:id,country:p.country,year:g.year},visitedCountries:[...new Set([g.country,...(g.visitedCountries||[]),p.country])]};delta=5;text=`You travelled to ${p.country} to visit. You can spend time together during this year.`;}
 else if(action==='lend'){amount=Number(amount);if(!Number.isInteger(amount)||amount<1)return {game:g,error:'Enter a whole positive loan amount.'};next=spend(g,amount,`Loan to ${p.name}`);if(!next)return {game:g,error:'You cannot afford that loan.'};next={...next,personalLoans:[...(g.personalLoans||[]),{id:`loan-${id}-${g.year}-${(g.personalLoans||[]).length}`,personId:id,amount,dueYear:g.year+3,status:'pending'}]};delta=7;text=`You lent $${amount.toLocaleString()} with repayment expected in three years.`;}
 else if(action==='insult'){delta=-15;text='You insulted them. They will remember the hurt.';}
 else if(action==='fight'){if(g.age<18||p.age<18||!nearby(g,p))return {game:g,error:'This interaction requires two adults who are physically together.'};delta=-30;text='A confrontation became physical. It damaged trust and was recorded in your shared history.';next=updatePerson({...g,stats:{...g.stats,health:clamp((g.stats?.health||50)-8)},courtCases:[{id:`fight-${id}-${g.year}-${(g.courtCases||[]).length}`,charge:'Assault',severity:2,status:'pending',year:g.year,age:g.age},...(g.courtCases||[])]},id,n=>({...n,trust:clamp((n.trust??50)-25)}));}
 else if(action==='reconcile'){if(p.lastReconcileYear===g.year)return {game:g,error:'Give them time before another reconciliation.'};delta=(p.closeness??50)<60?8:2;text='You apologized and made space for rebuilding trust.';next=updatePerson(next,id,n=>({...n,lastReconcileYear:g.year}));}
 else return {game:g,error:'Choose an available interaction.'};
 return {game:depthLog(remember(next,id,action,text,delta),`${p.name}: ${text}`,'Relationship memory','💬'),message:text};}
export function migrationBlock(g){if(!g.alive||g.age<18)return 'Independent relocation opens at 18.';if(g.job)return 'Leave your job before emigrating.';if((g.companies||[]).some(c=>c.status!=='Sold'&&c.status!=='Closed')||(g.assets||[]).some(a=>a.category==='Businesses'&&a.status==='owned'))return 'Sell or close your active businesses before emigrating.';if(g.educationStatus==='enrolled'||g.educationStudy)return 'Complete or withdraw from your university program before emigrating.';if(g.jail?.yearsRemaining>0)return 'You cannot relocate while incarcerated.';return '';}
export function illegalRelocate(g,country,random=Math.random){const block=migrationBlock(g);if(block)return {game:g,error:block};if(country===g.country)return {game:g,error:'You already live here.'};if(g.illegalMigrationAttemptYear===g.year)return {game:g,error:'You can attempt this route once per year.'};if((g.money||0)+(g.bankBalance||0)<7500)return {game:g,error:'This risky route requires $7,500 available.'};const roll=random(),chance=Math.min(.55,.3+(g.stats?.smarts||50)*.0015);let next=spend({...g,illegalMigrationAttemptYear:g.year},2500,'Illegal emigration attempt');if(roll<chance){const out=relocate(next,country,[],()=>0);if(out.error)return out;next={...out.game,immigrationStatus:{country,status:'Undocumented',arrivedYear:g.year},migrationHistory:out.game.migrationHistory.map((m,i)=>i===out.game.migrationHistory.length-1?{...m,mode:'illegal'}:m)};return {game:depthLog(next,'You arrived without legal residency. Your local record is separate from your history abroad.','Illegal emigration','🧳'),message:'You reached the new country. You have no new local convictions, but your old record remains archived. Your residency is undocumented.'};}const detained=roll<.82;next={...next,stats:{...g.stats,health:clamp((g.stats?.health??70)-(detained?2:15)),happiness:clamp((g.stats?.happiness??50)-8)},criminalRecord:detained?[{charge:'Illegal emigration attempt',country:g.country,year:g.year,age:g.age},...(g.criminalRecord||[])]:g.criminalRecord,jail:detained?{facility:'Immigration detention',yearsRemaining:1,security:'Minimum',disciplinaryRecord:0}:g.jail,migrationHistory:[...(g.migrationHistory||[]),{from:g.country,to:country,year:g.year,mode:'illegal',approved:false,outcome:detained?'Detained':'Injured'}]};return {game:depthLog(next,detained?'Your illegal emigration attempt failed. You were detained and the offense entered your local record.':'The attempt failed and you were injured. You remain in your home country.','Illegal emigration','⚠️'),message:detained?'Caught and detained for one simulated year. $2,500 was lost.':'The attempt failed. You lost $2,500 and suffered an injury.'};}
export function relocate(g,country,ids=[],random=Math.random){const error=migrationBlock(g);if(error)return {game:g,error};if(country===g.country)return {game:g,error:'You already live here.'};const located=locateLife(g),people=peopleInLife(located),companions=people.filter(p=>ids.includes(p.id));if(companions.some(p=>p.country!==g.country))return {game:g,error:'Only people currently in your country can relocate with you.'};if(companions.some(p=>p.age<18&&!(g.children||[]).some(c=>c.id===p.id)))return {game:g,error:'You can relocate only with your own minor children or consenting adults.'};if(companions.some(p=>p.age<18&&p.custody&&p.custody!=='You'&&p.custody!=='Together'&&!ids.includes(p.otherParentId)))return {game:g,error:'Shared-custody children need their other parent to relocate too.'};if(companions.some(p=>p.age>=18&&(p.closeness??50)<40))return {game:g,error:'A companion declined because your bond is too strained.'};const fee=5000+companions.length*1000;if((g.money||0)+(g.bankBalance||0)<fee)return {game:g,error:`Save $${fee.toLocaleString()} for this relocation.`};const approved=random()<recordVisaChance(g,Math.min(.94,.65+(g.educationLevel||0)*.05+(g.stats?.smarts||50)*.001));let next=spend(located,approved?fee:900,'Relocation application');if(!approved)return {game:depthLog(next,`Your application to ${country} was declined.`),message:'Application declined. $900 document fees were paid.'};for(const p of companions)next=remember(updatePerson(next,p.id,n=>({...n,country})),p.id,'relocation',`Moved with you to ${country}.`,3);next={...localizeCriminalRecord(next,country),country,immigrationStatus:{country,status:'Legal resident',arrivedYear:g.year},city:country==='United Arab Emirates'?'Dubai':null,activeVisit:null,livingArrangement:null,realism:next.realism?{...next.realism,housing:{type:'shared',assetId:null,condition:60,commute:6}}:next.realism,driversLicense:g.driversLicense?{...g.driversLicense,status:'review-required'}:null,visitedCountries:[...new Set([g.country,...(g.visitedCountries||[]),country])],migrationHistory:[...(g.migrationHistory||[]),{year:g.year,from:g.country,to:country,approved:true,companions:companions.map(p=>p.id)}]};return {game:depthLog(next,`You moved to ${country}${companions.length?` with ${companions.map(p=>p.name).join(', ')}`:''}. People and property left behind remain in ${g.country}.`,'Relocation','🧳'),message:`Welcome to ${country}. Your former assets remain abroad.`};}

export const educationPrograms=[{id:'vocational',title:'Vocational diploma',years:2,fee:4000,level:1,min:0},{id:'certification',title:'Professional certification',years:1,fee:2000,level:0,min:1},{id:'masters',title:"Master’s degree",years:2,fee:18000,level:3,min:2},{id:'phd',title:'PhD',years:4,fee:12000,level:4,min:3}];
export function enrollDepth(g,id,major,prestige=50,country=g.country){const p=educationPrograms.find(p=>p.id===id);if(!g.alive||g.age<18||!p||g.educationStudy||g.educationStatus==='enrolled'||(g.educationLevel||0)<p.min)return {game:g,error:'Complete the required qualification before starting another program.'};if(!Number.isFinite(Number(prestige))||![30,60,90].includes(Number(prestige)))return {game:g,error:'Choose a college tier.'};if(country!==g.country&&(g.job||(g.companies||[]).length))return {game:g,error:'Leave work and active businesses before full-time study abroad.'};if(prestige===90&&(g.universityGpa??((academicGrade(g)||60)/25))<3.2)return {game:g,error:'A selective university requires a GPA of at least 3.20.'};return {game:depthLog({...locateLife(g),educationStudy:{...p,major,prestige,country,completed:0,gpa:g.universityGpa||2.8,fee:Math.round(p.fee*(.6+prestige/100)),startedYear:g.year},educationStatus:'advanced-enrolled'},`You enrolled in ${p.title} in ${major} at a ${prestige===90?'prestigious':prestige===60?'regional':'community'} institution in ${country}.`,'Education','🎓'),message:'Enrolled. Tuition is charged each academic year; shortages become student debt.'};}
export function scholarship(g){if(!g.alive||g.age<16||g.scholarshipAppliedYear===g.year)return {game:g,error:'Scholarships can be applied for once per year from age 16.'};const merit=(g.universityGpa??((academicGrade(g)||60)/25));const value=merit>=3.6?12000:merit>=3?6000:merit>=2.5?2000:0;return {game:depthLog({...g,scholarshipAppliedYear:g.year,universityScholarshipBalance:(g.universityScholarshipBalance||0)+value},value?`You earned a $${value.toLocaleString()} merit scholarship.`:'Your scholarship application was unsuccessful. Improve your grades and try next year.','Scholarship','🎓'),message:value?`Awarded $${value.toLocaleString()} toward tuition.`:'No award this year.'};}
export function withdrawStudy(g){if(!g.educationStudy&&g.educationStatus!=='enrolled')return g;return depthLog({...g,educationStudy:null,educationStatus:'dropped-out',educationHistory:[...(g.educationHistory||[]),{year:g.year,degree:g.educationStudy?.title||'Bachelor’s degree',major:g.educationStudy?.major||g.universityCourse,status:'Withdrawn'}]},'You withdrew from your program. Credits remain on your transcript; existing student debt still needs repayment.','Education','📚');}
export function advanceEducation(g){const p=g.educationStudy;if(!p||p.lastYear===g.year)return g;let next=g;const award=Math.min(g.universityScholarshipBalance||0,p.fee),due=p.fee-award,cash=Math.min(due,(g.money||0)+(g.bankBalance||0));if(cash)next=spend(next,cash,`${p.title} tuition`);const financed=due-cash;if(financed)next={...next,loans:[...(next.loans||[]),{id:`student-depth-${g.year}`,studentLoan:true,purpose:p.title,principal:financed,balance:financed,apr:.055,termMonths:120,monthlyPayment:Math.ceil(financed*.01085),monthsPaid:0,status:'active'}]};const gpa=Math.max(0,Math.min(4,p.gpa+((g.stats?.smarts||50)-50)*.005+((g.realism?.schedule?.study||0)-10)*.005-(g.realism?.burnout||0)*.002+.04));const completed=p.completed+(gpa>=2?1:0),finished=completed>=p.years;next={...next,universityScholarshipBalance:(g.universityScholarshipBalance||0)-award,educationStudy:finished?null:{...p,gpa,completed,lastYear:g.year},educationStatus:finished?'graduated':'advanced-enrolled',educationLevel:finished?Math.max(g.educationLevel||0,p.level):g.educationLevel,education:finished?p.title:g.education,universityGpa:gpa,educationHistory:finished?[...(g.educationHistory||[]),{year:g.year,degree:p.title,major:p.major,gpa,prestige:p.prestige,country:p.country,status:'Completed'}]:g.educationHistory,certifications:finished&&p.id==='certification'?[...new Set([...(g.certifications||[]),p.major])]:g.certifications};return depthLog(next,finished?`You earned your ${p.title} in ${p.major}, GPA ${gpa.toFixed(2)}.`:`${p.title}: ${completed}/${p.years} academic years completed; GPA ${gpa.toFixed(2)}.${gpa<2?' Repeat the year after improving your grades.':''}${financed?` $${financed.toLocaleString()} financed.`:''}`,'Education','🎓');}

export const achievementCatalog=[{id:'millionaire',title:'🏆 Millionaire',description:'Reach $1 million net worth',test:g=>planningNetWorth(g)>=1e6},{id:'soulmates',title:'❤️ Soulmates',description:'Stay married for 50 years',test:g=>g.marriage&&g.year-g.marriage.year>=50},{id:'scholar',title:'🎓 Scholar',description:'Earn a PhD',test:g=>g.educationLevel>=4||(g.educationHistory||[]).some(p=>p.degree==='PhD'&&p.status==='Completed')},{id:'big-family',title:'👶 Big Family',description:'Have 10 children',test:g=>(g.children||[]).length>=10},{id:'world-traveler',title:'🌍 World Traveler',description:'Visit 25 countries',test:g=>new Set([g.country,...(g.visitedCountries||[])]).size>=25},{id:'self-made',title:'💼 Self Made',description:'Build a company worth $100 million',test:g=>(g.companies||[]).some(c=>c.valuation>=1e8&&!c.acquired)},{id:'dynasty',title:'🧬 Dynasty',description:'Reach 10 generations',test:g=>(g.generation||1)>=10}];
export function awardDepth(g){const unlocked=achievementCatalog.filter(a=>a.test(g)&&!(g.achievements||[]).some(n=>n.id===a.id));if(!unlocked.length)return g;return {...g,achievements:[...(g.achievements||[]),...unlocked.map(a=>({id:a.id,title:a.title,year:g.year,age:g.age,description:a.description}))]};}
export const fameLevel=n=>n>=90?'Global icon':n>=70?'International star':n>=45?'National celebrity':n>=20?'Rising public figure':n>0?'Local recognition':'Private life';
export const syncFameAudience=syncPublicAudience;
export function advanceFame(g){if(g.fameReviewYear===g.year)return syncFameAudience(g);const fame=clamp((g.fame||0)+(g.fameContract?.status==='active'?3:-1));return syncFameAudience({...g,fame,fameReviewYear:g.year,fameHistory:[...(g.fameHistory||[]),{year:g.year,fame,level:fameLevel(fame)}]});}
export function sponsorship(g,platform){const a=g.socialAccounts?.[platform],offer=a?.sponsorOffer;if(!g.alive||g.age<18||!offer||offer.year!==g.year||a.sponsoredYear===g.year||a.privacy==='Private'||a.suspended)return {game:g,error:'No available sponsorship for this account.'};return {game:depthLog({...g,money:(g.money||0)+offer.fee,lifetimeIncome:(g.lifetimeIncome||0)+offer.fee,socialAccounts:{...g.socialAccounts,[platform]:{...a,sponsoredYear:g.year,earnings:(a.earnings||0)+offer.fee,sponsorOffer:null}},transactions:[{year:g.year,age:g.age,label:`Disclosed sponsorship · ${offer.brand}`,amount:offer.fee},...(g.transactions||[])]},`You delivered a clearly disclosed ${offer.brand} campaign on ${platform}.`,'Sponsorship','📣'),message:'Campaign delivered and paid.'};}

const eventThemes=[
 ['education','A teacher offers extra mentoring','A difficult exam needs preparation','An academic contest opens','A project partner stops contributing','A library workshop has one place left','A scholarship essay deadline approaches','A class presentation goes wrong','A tutor offers a different study method','A campus debate challenges your beliefs','Your research catches a lecturer’s attention'],
 ['career','A colleague asks for help on a deadline','A manager offers a stretch assignment','A client complains about a mistake','An employer offers paid training','Your team faces a difficult audit','A coworker takes credit for your work','An old colleague recommends you','A workplace dispute needs mediation','Your department is reorganizing','A professional conference has an opening'],
 ['family','A relative needs practical support','An old family disagreement resurfaces','A family tradition is fading','A loved one asks for honest advice','A reunion brings unexpected news','A younger relative seeks a mentor','A birthday becomes a turning point','A family keepsake needs a new home','Someone feels left out of your plans','A family member wants to rebuild trust'],
 ['community','A community project needs volunteers','A neighbour is struggling alone','A local fundraiser asks for your help','A public garden needs restoring','A community group offers a leadership role','An old neighbourhood friend contacts you','A local crisis sparks mutual aid','A youth centre needs a mentor','A neighbourhood argument escalates','A volunteer group asks you to return'],
 ['finance','A tempting investment arrives by email','A friend asks you to guarantee a loan','An unexpected bill disrupts your budget','A financial workshop offers guidance','A subscription quietly becomes expensive','A stranger promises easy returns','A disputed charge needs investigating','A forgotten savings account resurfaces','A bargain has hidden costs','An adviser suggests reviewing your emergency fund'],
 ['health','Your sleep has become irregular','A routine checkup is overdue','A new exercise group welcomes you','A stressful week affects your mood','An old injury needs attention','A wellness class has an opening','You notice signs of burnout','A friend proposes a healthier routine','Your doctor recommends a lifestyle change','A quiet retreat could help you reset'],
 ['fame','An interviewer asks a difficult question','An old post attracts criticism','Fans discover your favourite quiet spot','A public appearance gets unexpected attention','A brand invites you to an exclusive event','A private conversation is taken out of context','A charity asks you to lend your platform','A fan account spreads an inaccurate story','A documentary crew asks to follow you','A public rival offers a collaboration'],
 ['relationships','An old friend feels forgotten','Someone asks you to keep a difficult secret','A friendship is becoming one-sided','A friend offers a heartfelt apology','A reunion tests your patience','An acquaintance asks for support','An honest conversation changes your bond','An old message brings back memories','Someone misunderstands your intentions','A friend celebrates a major milestone']
];
const contexts=[['quiet','The invitation arrives quietly, giving you room to think.',1,5],['urgent','The decision needs an answer before the week ends.',2,12],['public','Other people will see how you respond.',3,20],['personal','This connects to something you care deeply about.',4,27]];
export const eventCatalog=eventThemes.flatMap(([category,...titles])=>titles.flatMap((title,i)=>contexts.map(([context,text,scale,delay])=>({id:`depth-${category}-${i}-${context}`,category,title,text,scale,delay,minAge:category==='education'?6:category==='career'||category==='finance'||category==='fame'?18:8,eligible:g=>category==='education'?g.age<18||g.educationStatus==='enrolled'||Boolean(g.educationStudy):category==='career'?Boolean(g.job&&g.job!=='Founder & CEO'):category==='family'?peopleInLife(g).some(p=>['Parent','Sibling','Child','Partner'].includes(p.role)):category==='relationships'?peopleInLife(g).length>0:category==='fame'?(g.fame||0)>=20:true}))));
export function pickDepthEvent(g,random=Math.random){if(!g.alive)return null;const due=(g.deferredConsequences||[]).find(c=>c.dueYear<=g.year&&!c.resolved);if(due)return {engine:'depth',key:due.id,consequenceId:due.id,age:g.age,category:'Long-term consequences',icon:'🕰️',title:due.positive?'A choice comes back to reward you':'An old decision catches up with you',text:`At age ${due.age}, ${due.context} ${due.positive?'The person you helped has an opportunity for you.':'The unresolved issue has returned and needs attention.'}`,choices:[{label:due.positive?'Accept the opportunity':'Take responsibility',detail:'Resolve this chapter of your life.',effects:{money:due.positive?1500:-500,stats:{happiness:due.positive?6:-3}}},{label:'Let it pass',detail:'Close this chapter without a financial change.',effects:{stats:{happiness:due.positive?0:-5}}}]};const eligible=eventCatalog.filter(e=>g.age>=e.minAge&&e.eligible(g)&&!(g.depthEventHistory||[]).some(h=>h.id===e.id));if(!eligible.length)return null;const e=eligible[Math.min(eligible.length-1,Math.floor(random()*eligible.length))];return {engine:'depth',key:e.id,age:g.age,category:e.category,icon:'🧭',title:e.title,text:e.text,delay:e.delay,choices:[{label:'Invest time and handle it thoughtfully',detail:'Build trust and a future opportunity; costs $100.',memory:true,positive:true,effects:{money:-100,stats:{smarts:e.scale,happiness:2}}},{label:'Set a respectful boundary',detail:'Protect your energy and close the matter.',effects:{stats:{health:2}}},{label:'Take a shortcut and ignore the consequences',detail:'An unresolved issue may return years later.',positive:false,effects:{stats:{happiness:2}}}]};}
export function resolveDepthEvent(g,event,choice){let next=g;const money=choice.effects?.money||0;if(money<0){next=spend(g,-money,event.title);if(!next)return {game:g,error:'Save enough to choose this response.'};}else if(money>0)next={...g,money:(g.money||0)+money,lifetimeIncome:(g.lifetimeIncome||0)+money};let stats={...next.stats};for(const [key,value] of Object.entries(choice.effects?.stats||{}))stats[key]=clamp((stats[key]||0)+value);const deferred=(g.deferredConsequences||[]).map(c=>c.id===event.consequenceId?{...c,resolved:true,resolvedYear:g.year}:c);if(!event.consequenceId&&choice.positive!==undefined)deferred.push({id:`consequence-${event.key}-${g.year}`,dueYear:g.year+(event.delay||10),age:g.age,context:event.title.toLowerCase()+'.',positive:choice.positive,resolved:false});next={...next,stats,pendingLifeEvent:null,depthEventHistory:[...(g.depthEventHistory||[]),{id:event.key,year:g.year,age:g.age,choice:choice.label}],deferredConsequences:deferred};const person=peopleInLife(g)[0];if(choice.memory&&person)next=remember(next,person.id,'support',event.title,3);return {game:depthLog(next,`${event.title}: ${choice.label}.`,'Life event',event.icon)};}
export function lifeSummary(g){const born=g.year-g.age;return {name:g.name,born,died:g.year,age:g.age,country:g.country,netWorth:planningNetWorth(g),peakFame:Math.max(g.fame||0,...(g.fameHistory||[]).map(h=>h.fame)),children:(g.children||[]).length,marriageYears:g.marriage?g.year-g.marriage.year:0,education:g.education,qualifications:g.educationHistory||[],countries:[...new Set([g.country,...(g.visitedCountries||[])])],achievements:g.achievements||[],career:g.job||g.career||'Many paths',memories:peopleInLife(g).reduce((n,p)=>n+(p.memory||[]).length,0),moments:(g.log||[]).filter(l=>!String(l.tag).startsWith('Age ')).slice(0,20)};}
export function advanceDepth(g,random=Math.random){if(g.depthYear===g.year)return g;let next=advanceEnrichment(advanceFame(advanceEducation(locateLife(g))),random);for(const loan of next.personalLoans||[]){if(loan.status==='pending'&&loan.dueYear<=g.year){const p=peopleInLife(next).find(p=>p.id===loan.personId),repaid=p&&p.alive!==false&&(p.closeness??50)>=40;next={...next,money:(next.money||0)+(repaid?loan.amount:0),personalLoans:next.personalLoans.map(l=>l.id===loan.id?{...l,status:repaid?'repaid':'defaulted'}:l)};if(p)next=remember(next,p.id,repaid?'loan repaid':'loan default',repaid?'They repaid the money you lent.':'They could not repay your loan.',repaid?5:-10);}}
 next={...next,classmates:(next.classmates||[]).map(p=>({...p,age:p.age+1}))};
 const annualDeath=g.age>=100?.2:g.age>=85?.08:g.age>=70?.015:0;const ended=!next.alive||(next.stats?.health??100)<=0||random()<annualDeath;next=awardDepth({...next,depthYear:g.year,alive:ended?false:next.alive});return ended?{...next,lifeSummary:next.lifeSummary||lifeSummary(next),pendingLifeEvent:null}:next;}
