import WorldFeatures from './WorldFeatures.jsx';
import {LifeHero,LifeTabs} from './LifeScreenUI.jsx';
import React,{useState} from 'react';
import {skillNames,traitDescriptions,trainSkill,countryBudgets,lifestyles,economyQuote,challenges,syncTree} from './lifeSystems.js';
import {formatMoney} from './money.js';
import {PersonPortrait} from './RelationshipPortrait.jsx';
export default function LifeDevelopmentScreen({game,setGame}){const [tab,setTab]=useState('Skills');const [selected,setSelected]=useState(null);const quote=economyQuote(game,game.salary||0);const tree=syncTree(game).familyTree;return <div className="development-screen life-screen legacy-screen"><LifeHero icon="🌳" title="Build a lasting legacy" description="Develop your talents, discover your family history and shape the life you leave behind." badge="Life & Legacy"/><LifeTabs label="Life and legacy sections" value={tab} onChange={setTab} items={[['Skills','🎯'],['Personality','✨'],['Family tree','🌳'],['Country budget','💰'],['Achievements','🏆'],['Family legacy','📜']]}/>
{tab==='Family legacy'&&<WorldFeatures type="inheritance" game={game} setGame={setGame} expanded/>}
{tab==='Skills'&&<><h2>Practice shapes your life</h2><p>Energy: {Math.round(game.realism?.energy??80)}/100. Each session uses 4 energy; rest before training when energy falls below 15.</p><p>Training starts at age 6. Each skill allows two sessions per year. Discipline helps careers; charisma helps dating; specialist skills help related jobs. Cooking lowers living costs.</p>{skillNames.map(k=><section key={k}><h3>{k} · {game.skills?.[k]||0}/100</h3><progress max="100" value={game.skills?.[k]||0}/><div className="development-actions">{[false,true].map(lesson=><button key={String(lesson)} disabled={!game.alive||game.age<6||(game.realism?.energy??80)<15||game.skills?.[k]>=100||(game.trainingYear===game.year&&(game.trainingSessions?.[k]||0)>=2)||(lesson&&game.money+(game.bankBalance||0)<250)} onClick={()=>setGame(g=>trainSkill(g,k,lesson))}>{lesson?'Lesson · $250':'Practice · Free'}</button>)}</div></section>)}</>}
{tab==='Personality'&&<><h2>Your personality</h2><p>Choose up to two traits once for this character. These influence annual well-being, learning, spending, dating and relationships.</p>{Object.entries(traitDescriptions).map(([name,description])=><section key={name}><label><input type="checkbox" checked={game.traits?.includes(name)||false} disabled={game.personalityLocked||(!game.traits?.includes(name)&&game.traits?.length>=2)} onChange={()=>setGame(g=>({...g,traits:g.traits.includes(name)?g.traits.filter(t=>t!==name):[...g.traits,name]}))}/> <b>{name}</b></label><p>{description}</p></section>)}<button disabled={game.personalityLocked||!game.traits?.length} onClick={()=>setGame(g=>({...g,personalityLocked:true}))}>{game.personalityLocked?'Personality chosen':'Confirm personality'}</button></>}
{tab==='Family tree'&&<><h2>Your family across generations</h2><p>Select a person to read their recorded history. Unknown ancestors are left unrecorded.</p>{Object.values(tree).map(p=><button className="tree-person" key={p.id} onClick={()=>setSelected(p.id)}><span><PersonPortrait person={p}/></span><div><b>{p.name}</b><small>Age {p.age} · {p.alive===false?'Deceased':'Living'}{p.id===game.characterId?' · You':''}</small><small>Children: {(p.childIds||[]).map(id=>tree[id]?.name||'Unknown').join(', ')||'None recorded'}</small><small>Parents: {(p.parentIds||[]).map(id=>tree[id]?.name||'Unknown').join(', ')||'Not recorded'}</small></div></button>)}{selected&&tree[selected]&&<section><h3>{tree[selected].name}’s history</h3><p>{tree[selected].career||'Career not recorded'}</p><p>Recorded reputation: {tree[selected].realismSummary?.reputation??'Not recorded'}</p><p>Traits: {tree[selected].traits?.join(', ')||'Not recorded'}</p><p>Achievements: {tree[selected].achievements?.map(a=>a.name).join(', ')||'None recorded'}</p>{(tree[selected].history||[]).map((e,i)=><p key={i}><b>Age {e.age}</b> {e.text}</p>)}</section>}</>}
{tab==='Country budget'&&<><h2>{game.country} · Annual budget</h2><p>Simplified fictional game rates in USD. The first $10,000 of annual salary and investment distributions is tax-free. The next $40,000 uses the country rate; income above that uses a higher rate. Housing, insurance and tuition are billed separately. Families cover living costs before age 18.</p><section><p>Base tax rate: {Math.round(quote.rate*100)}%</p><p>Estimated salary tax: {formatMoney(quote.tax)}</p><p>Annual living costs: {formatMoney(quote.living)}</p><p>Unpaid budget balance: {formatMoney(game.economyArrears||0)}</p><label>Lifestyle <select value={game.lifestyle||'Balanced'} onChange={e=>setGame(g=>({...g,lifestyle:e.target.value}))}>{Object.keys(lifestyles).map(k=><option key={k}>{k}</option>)}</select></label></section>{(game.economyHistory||[]).map(r=><section key={r.year}><b>{r.year} · {r.country}</b><p>Tax {formatMoney(r.tax)} · Living {formatMoney(r.living)} · Paid {formatMoney(r.paid)} · Outstanding {formatMoney(r.arrears)}</p></section>)}</>}
{tab==='Achievements'&&<><h2>Life challenges</h2>{game.challenge&&<section><h3>{challenges.find(c=>c.id===game.challenge.id)?.name}</h3><p>{game.challenge.status} · Deadline {game.challenge.deadline}{game.challenge.id==='health'?` · Healthy years ${game.challenge.streak||0}/5`:''}</p></section>}{challenges.map(c=><section key={c.id}><h3>{c.name}</h3><p>{c.description}</p><button disabled={!game.alive||game.challenge?.status==='active'} onClick={()=>setGame(g=>({...g,challenge:{id:c.id,status:'active',startedYear:g.year,deadline:g.year+c.years,streak:0}}))}>Start challenge</button></section>)}<h2>Achievements · {game.achievements?.length||0}</h2><p>Badges are awarded automatically as you reach milestones.</p>{(game.achievements||[]).map(a=><section key={a.id}><b>🏆 {a.name}</b><p>Age {a.age} · {a.year}</p></section>)}</>}
</div>;}
