import {spend,funds} from './futurePlanning.js';
import {peopleInLife,updatePerson} from './gameFixes.js';
import {enrichmentState,enrich,note,success,failure,clamp,hash} from './enrichmentCore.js';
import {advanceHousingLife} from './housingLife.js';
import {simulationSettings,academicGrade} from './simulationSettings.js';
export const ambitions=['Family','Friendship','Wealth','Creativity','Service','Adventure','Learning'];
export function captureTimeline(g){const key=e=>`${e.age}:${e.tag}:${e.text}`;const original=g.lifeTimeline||[],seen=new Set();const timeline=original.filter(e=>{const k=key(e);if(seen.has(k))return false;seen.add(k);return true;});const archived=new Set((g.legacyTimelines||[]).flatMap(l=>l.events||[]).map(key));const fresh=[];for(const e of g.log||[]){if(Object.hasOwn(e,'actorId')&&e.actorId!==g.characterId||archived.has(key(e))||seen.has(key(e)))continue;seen.add(key(e));fresh.push({...e,year:e.year??g.year-(g.age-e.age),id:hash(`${g.characterId||g.name}:${key(e)}`)});}return fresh.length||timeline.length!==original.length?{...g,lifeTimeline:[...timeline,...fresh]}:g;}

const memory=(g,id,action,detail,delta)=>updatePerson(g,id,p=>({...p,closeness:clamp((p.closeness??50)+delta),memory:[...(p.memory||[]),{age:g.age,year:g.year,action,detail}]}));
export function enrichmentAction(g,action,value,random=Math.random){if(!g.alive)return failure(g,'This life has ended.');let next=g;const state=enrichmentState(g),sports=state.sports;
 if(action==='ambition'){if(!ambitions.includes(value))return failure(g,'Choose a life ambition.');return success(enrich(g,'ambition',{name:value,satisfaction:50,since:g.year}),`Your personal ambition is ${value.toLowerCase()}. Success will reflect more than your bank balance.`);}
 if(action==='study'||action==='chores'||action==='rebel'||action==='rules'){if(g.age<5||g.age>=18)return failure(g,'These childhood choices are available from ages 5 to 17.');const c=state.childhood;if(c.actionYear===g.year)return failure(g,'You have made your childhood decision this year.');const subject=String(value||c.focus);next=enrich(g,'childhood',{...c,focus:action==='study'?subject:c.focus,chores:(c.chores||0)+(action==='chores'?1:0),curfew:Math.max(17,Math.min(23,c.curfew+(action==='rules'?1:action==='rebel'?-1:0))),strictness:clamp(c.strictness+(action==='rebel'?10:action==='rules'?-5:0)),actionYear:g.year});next={...next,schoolAcademicGrade:clamp(academicGrade(g)+(action==='study'?6:action==='rebel'?-5:1)),stats:{...g.stats,happiness:clamp(g.stats.happiness+(action==='rebel'?6:2))}};for(const p of g.family?.parents||[])next=memory(next,p.id,action,`You chose to ${action==='rules'?'discuss household rules':action}.`,action==='rebel'?-6:3);return success(next,action==='rules'?'Your parents agreed to review your curfew and expectations.':action==='study'?`You practised ${subject}, improving your school grades.`:action==='chores'?'You helped at home and strengthened your parents’ trust.':'Breaking curfew felt exciting, but your parents tightened their rules.','Growing up','🧒');}
 if(action==='sport-join'){if(g.age<8||g.age>25||sports||!['Football','Basketball','Tennis','Track'].includes(value))return failure(g,'Join one sport between ages 8 and 25.');return success(enrich(g,'sports',{sport:value,skill:30,fitness:60,stage:g.age<18?'School team':'Amateur club',trainingYear:null,injuredUntil:0,offers:[],history:[]}),`You joined a ${value.toLowerCase()} team.`,'Sports','🏅');}
 if(action==='sport-train'){if(!sports||sports.stage==='Retired'||g.jail?.yearsRemaining>0||sports.injuredUntil>g.year||sports.trainingYear===g.year)return failure(g,'Training needs an active, healthy athlete and is available once per year.');next=spend(g,g.age<18?0:400,'Athletic training');if(!next)return failure(g,'Training costs $400.');return success(enrich({...next,...(next.fameContract?.sports&&sports.focus==='Teamwork'?{fameContract:{...next.fameContract,performance:clamp((next.fameContract.performance||60)+5)}}:{})},'sports',{...sports,skill:clamp(sports.skill+(sports.focus==='Fitness'?4:8)*simulationSettings(g).opportunity),fitness:clamp(sports.fitness+(sports.focus==='Fitness'?12:5)),trainingYear:g.year}), 'Your coach worked on technique, fitness and consistency.','Sports training','🏋️');}
 if(action==='sport-sign'){const offer=sports?.offers?.find(o=>o.id===value);if(!offer||offer.expires<g.year||g.age<18||g.jail?.yearsRemaining>0||(g.educationStatus==='enrolled'||g.educationStudy)||g.job&&!g.fameContract?.sports)return failure(g,'A current offer requires an adult athlete free from another job, university or business.');next={...g,job:`Professional ${sports.sport} Athlete`,salary:offer.salary,career:'Professional athlete',fame:clamp((g.fame||0)+(g.fameContract?.sports?0:8)),fameContract:{signedYear:g.year,sports:true,status:'active',annualSalary:offer.salary,yearsRemaining:offer.years,performance:sports.skill}};return success(enrich(next,'sports',{...sports,stage:'Professional',club:offer.club,offers:[],history:[...(sports.history||[]),{year:g.year,club:offer.club,salary:offer.salary}]}),`You signed a ${offer.years}-year contract with ${offer.club}. Salary is paid through normal annual employment income.`,'Sports contract','🏟️');}
 if(action==='sport-retire'){if(!sports||sports.stage==='Retired')return failure(g,'You have no sporting career.');return success(enrich({...g,...(g.fameContract?.sports?{job:null,salary:0,fameContract:null}: {})},'sports',{...sports,stage:'Retired',offers:[]}), 'You retired from competition. Your sporting history remains in your timeline.','Sports retirement','🏅');}
 if(['boundary','reconnect','reunion'].includes(action)){const p=peopleInLife(g).find(p=>p.id===value);if(!p)return failure(g,'Choose a person in your life.');if(p.relationshipActionYear===g.year)return failure(g,'Give this relationship time before another major decision.');if(action==='reunion'&&p.country&&p.country!==g.country)return failure(g,'Arrange a visit or phone call with someone living abroad.');if(action==='reconnect'&&random()>(p.closeness??30)/100+.35){next=updatePerson(g,p.id,p=>({...p,relationshipActionYear:g.year}));return success(memory(next,p.id,'reconnection declined','You offered reconciliation; they asked for more time.',0),`${p.name} needs more time. Respect their decision.`,'Relationships','💬');}next=updatePerson(g,p.id,p=>({...p,relationshipActionYear:g.year,...(action==='boundary'?{boundary:p.boundary==='Space'?'Open':'Space'}:{estranged:false})}));next=memory(next,p.id,action,action==='boundary'?'You discussed personal space and boundaries.':'You made time to rebuild your connection.',action==='boundary'?0:8);return success(next,action==='boundary'?`You agreed on boundaries with ${p.name}.`:`You renewed your connection with ${p.name}.`,'Relationships','🤝');}
 if(action==='language'){if(g.age<8)return failure(g,'Language study opens at 8.');if(state.languageYear===g.year)return failure(g,'You have completed language study this year.');next=spend(g,g.age<18?0:300,'Language course');if(!next)return failure(g,'The course costs $300.');const languages=state.languages||{};return success({...next,enrichment:{...state,languageYear:g.year,languages:{...languages,[value]:clamp((languages[value]||0)+20)}}},`Your ${value} proficiency improved. Familiar languages reduce travel mishaps.`,'Language study','🌍');}
 if(action==='visa'){if(g.age<18)return failure(g,'Adult travel visa applications open at 18.');if(state.visaAttempt?.[value]===g.year)return failure(g,'You have applied for this travel visa this year.');next=spend(g,150,'Travel visa application');if(!next)return failure(g,'Visa processing costs $150.');const record=(g.criminalRecord||[]).length;const approved=random()<Math.max(.1,.9-record*.2)*simulationSettings(g).opportunity;next={...next,enrichment:{...state,visaAttempt:{...state.visaAttempt,[value]:g.year},travelVisas:{...state.travelVisas,...(approved?{[value]:{expires:g.year+3}}:{})}}};return success(next,approved?`Your simulated visitor visa for ${value} is valid for three years.`:`Your visitor visa for ${value} was declined. The processing fee is not refunded.`,'Travel visa','🛂');}
 return failure(g,'Choose an available action.');
}
export function businessExperience(g,id,action,random=Math.random){const c=(g.companies||[]).find(c=>c.id===id);if(!g.alive||g.age<18||!c||c.successionDisputed)return failure(g,'Resolve company ownership before making business decisions.');if(action==='bankruptcy'){if((c.cash||0)>=0)return failure(g,'Bankruptcy is available when company cash is negative.');return success({...g,companies:g.companies.filter(p=>p.id!==id),job:/CEO/i.test(g.job||'')?null:g.job,salary:/CEO/i.test(g.job||'')?0:g.salary},`${c.name} entered bankruptcy. Your equity was lost; company debts stayed with the company. Personal guarantees remain your responsibility.`,'Business bankruptcy','🏢');}if(c.experienceYear===g.year)return failure(g,'Your company has completed its strategic action this year.');const rate=action==='acquisition'?.4:action==='product'?.04:.015,cost=Math.max(2000,Math.round(c.valuation*rate));if(!['acquisition','product','reviews'].includes(action)||c.cash<cost)return failure(g,`This strategy requires $${cost.toLocaleString()} in company cash.`);const won=random()<Math.min(.95,.5+(c.reputation||50)/200);const bonus=won?(action==='acquisition'?15:action==='product'?10:6):-3;
 const next={...g,companies:g.companies.map(p=>p.id===id?{...p,cash:p.cash-cost,experienceYear:g.year,customerRating:Math.max(1,Math.min(5,(p.customerRating||3)+bonus/20)),competition:{...p.competition,share:clamp((p.competition?.share||30)+bonus),brand:clamp((p.competition?.brand||50)+bonus)},valuation:Math.max(1000,p.valuation+(won?cost*.7:-cost*.2)),acquisitions:action==='acquisition'&&won?[...(p.acquisitions||[]),{name:`${p.sector||'Regional'} rival`,year:g.year,cost}]:p.acquisitions||[]}:p)};return success(next,`${c.name} ${won?'succeeded':'struggled'} with its ${action==='reviews'?'customer service programme':action}. Company cash funded the decision.`,'Business strategy','🏢');}
export function travelExperience(g,trip,random=Math.random){const state=enrichmentState(g),foreign=trip.destination!==g.country;let next=g;const skilled=(state.languages?.[trip.destination]||0)>=40;const roll=random();const outcome=roll<.2&&!skilled?'A language misunderstanding disrupted an excursion.':roll<.55?'You met a welcoming local and exchanged contact details.':'The trip gave you a fresh perspective and lasting memories.';if(roll>=.2&&roll<.55){const id=`travel-friend-${hash(`${g.characterId||g.name}:${trip.destination}:${g.year}`)}`;if(!(next.friends||[]).some(p=>p.id===id))next={...next,friends:[...(next.friends||[]),{id,name:`${['Alex','Sam','Jordan','Robin'][Math.floor(random()*4)]} (${trip.destination})`,age:g.age,alive:true,country:trip.destination,closeness:45,gender:'Person',memory:[{year:g.year,age:g.age,action:'met abroad',detail:'You met during a holiday.'}]}]};}return note({...next,enrichment:{...enrichmentState(next),tripMemories:[{...trip,outcome,foreign},...(state.tripMemories||[])]}},outcome,'Travel experience','🌍');}
export function advanceEnrichment(g,random=Math.random){if(g.enrichmentYear===g.year)return captureTimeline(g);let next=advanceHousingLife(g,random),state=enrichmentState(next);if(g.age>=5&&g.age<18){const c=state.childhood,parent=(g.family?.parents||[]).find(p=>p.alive!==false);const amount=parent?Math.min(Math.max(0,parent.personalWealth||0),Math.round(c.allowance*52*(1+(c.chores||0)*.1))):0;if(amount){next=updatePerson(next,parent.id,p=>({...p,personalWealth:Math.max(0,(p.personalWealth||0)-amount)}));next={...next,money:(next.money||0)+amount,transactions:[{year:g.year,age:g.age,label:'Parental allowance',amount},...(next.transactions||[])]};}next={...next,schoolAcademicGrade:clamp(academicGrade(next)+((next.skills?.Discipline||0)>60?2:0))};}
 let s=state.sports;if(s&&s.stage!=='Retired'){if(s.stage==='School team'&&g.age>=18)s={...s,stage:'Amateur club'};if(s.injuredUntil<=g.year&&random()<.08*simulationSettings(g).risk){s={...s,injuredUntil:g.year+1,fitness:clamp(s.fitness-15)};next=note(next,'A sporting injury requires a year of recovery. Training pauses and your next season’s earnings are reduced.','Sports injury','🩹');}if(g.age>=18&&g.age<38&&s.skill>=60&&s.injuredUntil<=g.year&&random()<.65*simulationSettings(g).opportunity){const offer={id:`sports-${g.year}`,club:`${g.country} ${['United','Athletics','City'][Math.floor(random()*3)]}`,salary:Math.round(18000+s.skill*s.skill*12),years:3,expires:g.year+1};s={...s,offers:[offer]};next=note(next,`${offer.club} offered you a professional contract. Review it in Sports Career.`, 'Talent scout','📨');}if(g.age>=38&&s.stage==='Professional'){next={...next,...(next.fameContract?.sports?{job:null,salary:0,fameContract:null}:{})};s={...s,stage:'Retired',offers:[]};next=note(next,'You retired from professional sport after a demanding career.','Sports retirement','🏅');}next=enrich(next,'sports',s);}
 for(const p of peopleInLife(next)){if(p.age>=16&&(p.closeness??50)<15&&!p.estranged){next=updatePerson(next,p.id,q=>({...q,estranged:true}));next=note(next,`${p.name} became estranged after years of strain. A respectful reconnection may help.`, 'Relationship distance','💔');}else if((p.closeness??0)>=80&&g.year-(p.friendshipSince||g.year)>=10)next=memory(next,p.id,'lifelong friendship','Another year of a lasting friendship.',1);else if(!p.friendshipSince)next=updatePerson(next,p.id,q=>({...q,friendshipSince:g.year}));}
 state=enrichmentState(next);if(state.ambition){const a=state.ambition.name;const score=a==='Family'?Math.min(100,(next.children||[]).length*15+(next.partner?40:0)):a==='Friendship'?Math.min(100,peopleInLife(next).filter(p=>p.closeness>=70).length*20):a==='Wealth'?Math.min(100,Math.log10(Math.max(1,funds(next)))*15):a==='Creativity'?next.skills?.Music||0:a==='Learning'?academicGrade(next):a==='Adventure'?Math.min(100,(next.visitedCountries||[]).length*10):Math.min(100,Math.log10(1+(next.lifetimeDonations||0))*15+(next.realism?.reputation||0)/2);next=enrich(next,'ambition',{...state.ambition,satisfaction:Math.round(score),history:[...(state.ambition.history||[]),{year:g.year,score:Math.round(score)}]});}
 return captureTimeline({...next,enrichmentYear:g.year});}
