import {funds,spend,divorce,insuredExpense} from './futurePlanning.js';
import {reconcileChildSupport,changeCustody} from './childSupport.js';
const clamp=n=>Math.max(0,Math.min(100,n));
const hash=s=>[...String(s)].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7);
const log=(g,text,tag='Life experience',icon='✨')=>({...g,log:[{age:g.age,text,tag,icon},...(g.log||[])]});
const result=(g,message,tag,icon)=>({game:log(g,message,tag,icon),message});
const fail=(g,error)=>({game:g,error});
const cash=(g,amount,label)=>({...g,bankBalance:(g.bankBalance||0)+amount,lifetimeIncome:(g.lifetimeIncome||0)+Math.max(0,amount),transactions:[{label,amount,age:g.age},...(g.transactions||[])]});
export const worldState=g=>({news:[],market:'Stable',school:{},milestones:[],celebrated:[],relationshipHistory:[],...g.worldLife});
export const rentalHomes=g=>(g.assets||[]).filter(a=>a.status==='owned'&&a.category==='Homes');
export function tenantCandidates(g,a){
 const rent=a.rental?.rent||a.rentalIncome||Math.max(500,Math.round((a.value||0)*.004));
 return ['Jordan Blake','Casey Morgan','Taylor Reed'].map((name,i)=>({id:`tenant-${a.id}-${g.year}-${i}`,name,job:['Project manager','Business owner','Medical specialist'][i],income:Math.round(rent*12*(3.1+i)),reliability:65+i*12,avatarSeed:`tenant-${a.id}-${i}`}));
}
export const isResidence=(g,a)=>g.livingArrangement?.assetId===a.id||g.realism?.housing?.assetId===a.id;
export function rentalAction(g,id,action,value){
 const a=rentalHomes(g).find(a=>a.id===id);if(!g.alive||g.age<18||!a)return fail(g,'An adult owner must manage this property.');
 if(a.country&&a.country!==(g.educationStudy?.country||g.country))return fail(g,`This property remains in ${a.country}. You can sell or gift it while abroad; local management is unavailable.`);
 if(isResidence(g,a))return fail(g,'Move to another residence before letting this home.');
 let rental={rent:a.rentalIncome||Math.max(500,Math.round((a.value||0)*.004)),arrears:0,...a.rental},paid=g,rentedOut=a.rentedOut,message='';
 if(action==='list'){if(rentedOut)return fail(g,'This property is already listed.');rentedOut=true;rental={...rental,tenant:null,occupiedMonths:0,paidMonths:0};message=`${a.name} is listed. Choose a tenant before rent can be collected.`;}
 else if(action==='unlist'){if(rental.tenant)return fail(g,'Agree an end to the tenancy before withdrawing the property.');rentedOut=false;message=`You withdrew ${a.name} from the rental market.`;}
 else if(action==='tenant'){if(!rentedOut||rental.tenant)return fail(g,'List a vacant property first.');const tenant=tenantCandidates(g,a).find(t=>t.id===value);if(!tenant)return fail(g,'Choose an applicant from the current list.');if(rental.rent*12>tenant.income*.35)return fail(g,'The applicant cannot comfortably afford this rent.');rental={...rental,tenant,occupiedMonths:12,paidMonths:12};message=`${tenant.name}, a ${tenant.job.toLowerCase()}, signed a tenancy at $${rental.rent.toLocaleString()} per month.`;}
 else if(action==='rent'){const amount=Number(value),base=a.rentalIncome||Math.max(500,Math.round((a.value||0)*.004));if(rental.tenant)return fail(g,'Rent is fixed during the current tenancy. Review it while the property is vacant.');if(!Number.isInteger(amount)||amount<Math.round(base*.5)||amount>Math.round(base*1.5))return fail(g,'Choose monthly rent between 50% and 150% of the market estimate.');rental.rent=amount;message=`The asking rent for ${a.name} is now $${amount.toLocaleString()} per month.`;}
 else if(action==='repair'){const cost=Math.max(250,Math.round((a.value||0)*.005));paid=insuredExpense(g,cost,'home',id,`Rental repairs · ${a.name}`);if(!paid)return fail(g,'You cannot afford repairs after insurance.');rental={...rental,repairNeeded:false};message=`You repaired ${a.name}. The property is ready for comfortable occupancy.`;}
 else if(action==='recover'){if(!rental.tenant||!(rental.arrears>0))return fail(g,'There is no tenant debt to recover.');if(rental.recoveryYear===g.year)return fail(g,'You have already agreed a repayment this year.');const recovered=Math.min(rental.arrears,Math.round(rental.rent*(rental.tenant.reliability/100)));paid=cash(g,recovered,'Tenant arrears repayment');rental={...rental,arrears:rental.arrears-recovered,recoveryYear:g.year};message=`${rental.tenant.name} repaid $${recovered.toLocaleString()} of outstanding rent.`;}
 else if(action==='end'){if(!rental.tenant)return fail(g,'The property is already vacant.');const cost=Math.max(300,Math.min(5000,Math.round(rental.rent*.25)));paid=spend(g,cost,'Tenancy resolution');if(!paid)return fail(g,'You need funds to complete the tenancy resolution.');message=`${rental.tenant.name}'s tenancy ended through the housing process. ${rental.arrears?`Unrecovered rent of $${rental.arrears.toLocaleString()} was written off. `:''}${a.name} is vacant.`;rental={...rental,tenant:null,arrears:0,occupiedMonths:0,paidMonths:0};}
 else return fail(g,'Choose a property action.');
 const condition=action==='repair'?Math.min(100,(a.condition??100)+20):a.condition;
 return result({...paid,assets:g.assets.map(p=>p.id===id?{...p,rentedOut,rental,condition}:p)},message,'Rental property','🏡');
}
export function monthlyRentalReceipt(a,month){if(a.status!=='owned'||!a.rentedOut)return 0;if(!a.rental)return a.rentalIncome||0;return a.rental.tenant&&month<(a.rental.paidMonths??12)?a.rental.rent||0:0;}
export function competitionState(c){const seed=hash(c.id);return {share:30,demand:100,brand:50,rival:`${['Summit','Horizon','Nova','Cedar'][seed%4]} ${c.sector||'Group'}`,rivalStrength:55,history:[],...c.competition};}
export function competitionAction(g,id,action,random=Math.random){
 const c=(g.companies||[]).find(c=>c.id===id);if(!g.alive||g.age<18||!c)return fail(g,'You must be an adult company owner.');const m=competitionState(c);
 if(c.successionDisputed)return fail(g,'Resolve the inheritance dispute before making major company decisions.');
 if(m.actionYear===g.year)return fail(g,'Your team can complete one competitive initiative per year.');
 const cost=Math.max(action==='acquire'?10000:2500,Math.round((c.valuation||0)*(action==='acquire'?.25:action==='launch'?.02:.01)));
 if(!['launch','market','acquire'].includes(action))return fail(g,'Choose a competitive initiative.');if((c.cash||0)<cost)return fail(g,'The company needs more cash for this initiative.');
 const success=action!=='launch'||random()<Math.min(.92,.4+(g.skills?.Technology||0)*.003+(c.reputation||50)*.003);
 const gain=action==='acquire'?15:success?action==='launch'?8:4:0;
 const updated={...c,cash:c.cash-cost,valuation:(c.valuation||0)+(action==='acquire'?Math.round(cost*.65):success?Math.round(cost*.8):0),employees:(c.employees||1)+(action==='acquire'?4:0),performance:clamp((c.performance||50)+(success?4:-3)),competition:{...m,share:clamp(m.share+gain),brand:clamp(m.brand+(success?8:2)),rivalStrength:clamp(m.rivalStrength-(action==='acquire'?18:0)),actionYear:g.year}};
 const message=action==='acquire'?`${c.name} acquired a division of ${m.rival}. Market share rose to ${updated.competition.share}% and four staff joined your company.`:action==='market'?`${c.name}'s marketing campaign raised brand recognition and market share.`:success?`${c.name} launched a successful product. Market share rose to ${updated.competition.share}%.`:`${c.name}'s launch failed to gain traction. Development costs were spent and performance fell.`;
 updated.competition.history=[{age:g.age,text:message},...m.history].slice(0,12);
 return result({...g,companies:g.companies.map(p=>p.id===id?updated:p)},message,'Business competition','🏢');
}
export const businessDemand=c=>{const m=competitionState(c);return Math.max(.45,Math.min(1.6,m.demand/100*(.8+m.share/150)));};
const newsTypes=[
 {kind:'Expansion',title:'Businesses expand as consumer confidence rises',description:'Demand improves and employers compete for skilled workers.',demand:1.15,housing:1.04},
 {kind:'Recession',title:'Employers cut spending as the economy slows',description:'Demand falls, vacancies shrink and redundancies become more likely.',demand:.8,housing:.95},
 {kind:'Housing boom',title:'A surge in housing demand lifts property prices',description:'Owned homes gain value and asking rents rise for vacant properties.',demand:1.02,housing:1.1},
 {kind:'Election',title:'An election brings a new economic agenda',description:'A business investment programme opens opportunities, while public debate affects confidence.',demand:1.06,housing:1.01},
 {kind:'Storm',title:'A severe storm disrupts homes and local businesses',description:'Some properties need repairs and customer demand is temporarily lower.',demand:.9,housing:.98},
 {kind:'Stable',title:'Local markets settle into a steady rhythm',description:'Businesses and households have a relatively stable outlook.',demand:1,housing:1.02}
];
export function prepareWorldYear(input,random=Math.random){
 if(!input.alive)return input;const w=worldState(input),year=input.year+1;if(w.preparedYear===year)return input;
 const item=newsTypes[Math.min(newsTypes.length-1,Math.floor(random()*newsTypes.length))];
 const news={...item,id:`news-${input.characterId}-${year}`,age:input.age+1,country:input.country};
 let g={...input,worldLife:{...w,preparedYear:year,market:item.kind,news:[news,...w.news].slice(0,20)}};
 const assets=(g.assets||[]).map(a=>{if(a.status!=='owned'||a.category!=='Homes')return a;let rental=a.rental?{...a.rental}:a.rentedOut?{rent:a.rentalIncome||500,arrears:0,tenant:{id:`tenant-${a.id}`,name:'Existing tenant',job:'Employed',income:(a.rentalIncome||500)*48,reliability:85}}:null;
 let condition=a.condition??100;if(item.kind==='Storm'&&random()<.35){condition=clamp(condition-15);if(rental)rental.repairNeeded=true;g=log(g,`${a.name} was damaged by the storm. Review repairs in Assets.`,'Storm damage','⛈️');}
 if(rental){let occupiedMonths=0,paidMonths=0;if(a.rentedOut&&rental.tenant){occupiedMonths=12;if(random()<.12){occupiedMonths=6;rental.departedTenant=rental.tenant.name;}paidMonths=Math.max(0,occupiedMonths-(random()>rental.tenant.reliability/100?(item.kind==='Recession'?3:1):0));if(rental.repairNeeded){occupiedMonths=Math.max(0,occupiedMonths-2);paidMonths=Math.min(paidMonths,occupiedMonths);}const arrears=(occupiedMonths-paidMonths)*rental.rent;rental.arrears=(rental.arrears||0)+arrears;if(arrears)g=log(g,`${rental.tenant.name} missed $${arrears.toLocaleString()} in rent at ${a.name}.`,'Tenant arrears','🏡');}rental={...rental,occupiedMonths,paidMonths,lastAnnualRent:paidMonths*rental.rent,...(!rental.tenant?{rent:Math.round(rental.rent*(item.kind==='Housing boom'?1.05:1))}:{})};}
 return {...a,value:Math.round((a.value||0)*item.housing),condition,...(rental?{rental}:{})};});
 g={...g,assets};
 g.companies=(g.companies||[]).map(c=>{const m=competitionState(c);return {...c,competition:{...m,demand:Math.round(100*item.demand*(.9+random()*.2)),share:clamp(m.share+(m.brand-m.rivalStrength)/30+(random()-.5)*4)}};});
 return log(g,`${item.title}. ${item.description}`,'In the news','📰');
}
export function jobOffers(g){
 if(!g.alive||g.age<18||g.retired||g.jail?.yearsRemaining>0)return [];
 const w=worldState(g),factor=w.market==='Recession'?.85:w.market==='Expansion'?1.15:1,base=Math.min(180000,Math.max(28000,Number(g.salary)||30000));
 const technical=(g.skills?.Technology||0)>=40;
 return ['remote','promotion','relocation'].map((kind,i)=>({id:`offer-${g.year}-${kind}`,kind,title:kind==='promotion'?(technical?'Senior technology specialist':'Operations manager'):kind==='remote'?(technical?'Remote developer':'Remote coordinator'):'Regional project manager',salary:Math.round(base*factor*(1.05+i*.1)),bonus:(i+1)*2500,country:kind==='relocation'?(g.country==='United Kingdom'?'Canada':'United Kingdom'):g.country,education:i===1?2:1,expiresAge:g.age+1}));
}
export function acceptJobOffer(g,id){
 const w=worldState(g),offer=jobOffers(g).find(o=>o.id===id);if(!offer)return fail(g,'This offer is no longer available.');if(w.offerAcceptedYear===g.year)return fail(g,'You already accepted an offer this year.');if(g.job==='Founder & CEO'||g.politicalOffice&&g.job===g.politicalOffice)return fail(g,'Leave your current executive or elected role before accepting another job.');if((g.educationLevel||0)<offer.education)return fail(g,offer.education===2?'This role requires a university degree.':'Complete secondary school for this role.');
 let next=cash(g,offer.bonus,'Signing bonus');if(offer.kind==='relocation'){next=spend(next,3000,'Work relocation');if(!next)return fail(g,'You need $3,000 for relocation after the signing bonus.');}
 next={...next,job:offer.title,career:offer.title,salary:offer.salary,careerYears:0,fameContract:null,country:offer.country,worldLife:{...w,offerAcceptedYear:g.year},...(offer.kind==='relocation'?{livingArrangement:null,driversLicense:g.driversLicense?{...g.driversLicense,status:'review-required'}:null}:{}),realism:{...g.realism,...(offer.kind==='relocation'?{housing:{type:'apartment',country:offer.country,quality:65,commute:4}}:{}),career:{...g.realism?.career,performance:60,probation:true,remote:offer.kind==='remote',plan:null}}};
 return result(next,`You accepted ${offer.title} at $${offer.salary.toLocaleString()} a year with a $${offer.bonus.toLocaleString()} signing bonus.${offer.kind==='relocation'?` Your household relocated to ${offer.country}; moving cost $3,000.`:offer.kind==='remote'?' You now work from home without a work commute.':''}`,'Career offer','💼');
}
export const schoolClubs={Robotics:{cost:150,skill:'Technology'},Music:{cost:100,skill:'Music'},Art:{cost:60,skill:'Charisma'},Sports:{cost:80,skill:'Discipline'}};
export function schoolAction(g,action,value,random=Math.random){
 if(!g.alive||g.age<6||g.age>=18)return fail(g,'These experiences are available from age 6 to 17.');const w=worldState(g),s=w.school;let next=g,message='';
 if(action==='club'){const club=schoolClubs[value];if(!club)return fail(g,'Choose a school club.');if(s.club===value)return fail(g,'You already belong to this club.');if(s.clubChangedYear===g.year)return fail(g,'You can change clubs once per year.');next=spend(g,club.cost,`${value} club membership`);if(!next)return fail(g,'You need funds for the club membership.');next={...next,worldLife:{...w,school:{...s,club:value,clubChangedYear:g.year}}};message=`You joined the ${value.toLowerCase()} club. Regular participation will build ${club.skill.toLowerCase()} when you age up.`;}
 else if(action==='friend'){if(s.friendYear===g.year)return fail(g,'You already met a classmate this year.');const person={id:`school-friend-${g.characterId}-${g.year}`,avatarSeed:`school-${g.characterId}-${g.year}`,name:['Jamie Ellis','Morgan Lee','Alex Rivera'][Math.floor(random()*3)],age:g.age,alive:true,role:'Friend',closeness:55,looks:55,smarts:60,health:80,relationshipLabel:'School friend'};next={...g,friends:[person,...(g.friends||[])],worldLife:{...w,school:{...s,friendYear:g.year}},stats:{...g.stats,happiness:clamp((g.stats?.happiness||50)+5)}};message=`You became friends with ${person.name}, a classmate your age.`;}
 else if(action==='competition'){if(!s.club)return fail(g,'Join a club before entering its competition.');if(s.competitionYear===g.year)return fail(g,'You entered a school competition this year.');const skill=schoolClubs[s.club].skill,won=random()<Math.min(.9,.2+(g.skills?.[skill]||0)*.005+(g.stats?.smarts||0)*.002);next={...g,worldLife:{...w,school:{...s,competitionYear:g.year,awards:(s.awards||0)+(won?1:0)}},stats:{...g.stats,happiness:clamp((g.stats?.happiness||50)+(won?7:2))},universityScholarshipBalance:(g.universityScholarshipBalance||0)+(won?2500:0)};message=won?`You won your ${s.club.toLowerCase()} competition and earned a $2,500 university scholarship.`:`You entered the ${s.club.toLowerCase()} competition. You did not win, but learned from the experience.`;}
 else if(action==='bullying'){if(!s.bullying)return fail(g,'There is no unresolved school incident.');if(!['help','friend','confront'].includes(value))return fail(g,'Choose a response.');const supported=value!=='confront'||random()<.5;next={...g,worldLife:{...w,school:{...s,bullying:null,lastResolution:supported?'Support helped resolve the bullying.':'The confrontation escalated the conflict.'}},stats:{...g.stats,happiness:clamp((g.stats?.happiness||50)+(supported?8:-5)),health:clamp((g.stats?.health||50)+(supported?0:-3))}};message=value==='help'?'A teacher intervened and helped you agree a safety plan.':value==='friend'?'You and your friends stood together and reported the bullying.':supported?'You set a firm boundary and the conflict eased.':'The confrontation escalated. You felt shaken and school staff intervened.';}
 else return fail(g,'Choose a school experience.');return result(next,message,'School life','🎒');
}
export function relationshipExperience(g,action,personId,random=Math.random){
 if(!g.alive||g.age<18)return fail(g,'Adult relationship experiences start at 18.');const w=worldState(g);let next=g,message='';
 if(action==='affair'){const person=(g.friends||[]).find(p=>p.id===personId&&p.alive!==false&&p.age>=18&&!/Former spouse|Former partner/.test(p.relationshipLabel||''));if(!g.partner||g.partner.age<18||g.partner.alive===false||!person)return fail(g,'You need a partner and an adult friend for this choice.');if(w.affairYear===g.year)return fail(g,'You have already pursued a secret date this year.');const mutual=random()<Math.min(.8,.25+(person.closeness||0)/150);next={...g,worldLife:{...w,affairYear:g.year}};if(!mutual)return result(next,`${person.name} declined a romantic date. You respected their decision.`,'Relationship choice','💞');const discovered=random()<.6;next={...next,stats:{...g.stats,happiness:clamp((g.stats?.happiness||50)+3)},worldLife:{...next.worldLife,relationshipEvent:discovered?{kind:'affair',title:'Your partner discovered the secret date',text:`${g.partner.name} learned about your date with ${person.name}. Your partner and family want an honest explanation.`,partnerId:g.partner.id}:next.worldLife.relationshipEvent},partner:discovered?{...g.partner,closeness:clamp((g.partner.closeness||50)-25),trust:clamp((g.partner.trust??60)-30)}:g.partner,children:discovered?(g.children||[]).map(p=>({...p,closeness:clamp((p.closeness||50)-5)})):g.children};message=`You went on a secret romantic date with ${person.name}.${discovered?' Your partner found out, damaging trust and upsetting your children.':' Your partner has not discovered it.'}`;}
 else if(action==='reconcile'){if(!g.partner)return fail(g,'There is no current partner to reconcile with.');if(w.reconciliationYear===g.year)return fail(g,'You have already tried counselling this year.');next=spend(g,180,'Relationship counselling');if(!next)return fail(g,'Counselling costs $180.');next={...next,partner:{...g.partner,closeness:clamp((g.partner.closeness||50)+10),trust:clamp((g.partner.trust??60)+16)},worldLife:{...w,reconciliationYear:g.year,relationshipEvent:null}};message=`You and ${g.partner.name} attended counselling and rebuilt some trust. Past hurt still takes time to heal.`;}
 else if(action==='decision'){const e=w.relationshipEvent;if(!e||e.partnerId!==g.partner?.id)return fail(g,'No current relationship decision needs an answer.');if(personId==='separate'){if(g.marriage){const separated=divorce(g,'Shared','Amicable');if(separated.error)return fail(g,separated.error);next=separated.state;}else next=reconcileChildSupport({...g,friends:[{...g.partner,role:'Friend',relationshipLabel:'Former partner'},...(g.friends||[])],partner:null,relationship:'Single'});message='You separated and arranged the next steps. Support agreements for your children are available in Child Support.';}else if(personId==='listen'){next={...g,partner:{...g.partner,closeness:clamp((g.partner.closeness||50)+6),trust:clamp((g.partner.trust??60)+8)}};message='You listened honestly and agreed boundaries. Trust will take time to recover.';}else return fail(g,'Choose how to respond.');next={...next,worldLife:{...w,relationshipEvent:null,relationshipHistory:[{age:g.age,title:e.title,text:message},...w.relationshipHistory].slice(0,15)}};}
 else if(action==='custody'){const child=(g.children||[]).find(p=>p.id===personId);if(!child||child.age>=18)return fail(g,'Choose a child under 18.');next=changeCustody(g,personId,'Shared');if(next===g)return fail(g,'Shared custody cannot be changed here right now. Review your agreement in Child Support.');message=`You agreed shared custody for ${child.name}. Support payments will follow the revised agreement.`;}
 else if(action==='meeting'){if(w.familyMeetingYear===g.year)return fail(g,'You have already held a family meeting this year.');next={...g,children:(g.children||[]).map(p=>({...p,closeness:clamp((p.closeness||50)+6)})),family:{...g.family,siblings:(g.family?.siblings||[]).map(p=>({...p,closeness:clamp((p.closeness||50)+6)}))},worldLife:{...w,familyMeetingYear:g.year,estateExplained:true,familyUnity:clamp((w.familyUnity||50)+15)}};message='Your family discussed boundaries, inheritance wishes and business responsibilities. Clear expectations eased some rivalry.';}
 else return fail(g,'Choose a relationship action.');return result(next,message,'Family relationships','💞');
}
export function availableMilestones(g){const w=worldState(g),celebrated=new Set(w.celebrated);const items=[...(w.milestones||[])];if(g.retired)items.push({id:'retirement',title:'Retirement celebration',description:'Celebrate your next chapter after working life.',cost:400});if(g.educationStatus==='graduated')items.push({id:'university-graduation',title:'University graduation',description:'Celebrate your degree with family and friends.',cost:300});if(g.marriage&&g.partner){const years=g.year-g.marriage.year;if(years>0)items.push({id:`anniversary-${g.marriage.partnerId}-${years}`,title:`${years}-year anniversary`,description:`Celebrate your marriage with ${g.partner.name}.`,cost:150});}if((g.family?.siblings||[]).some(p=>p.alive!==false)||(g.children||[]).some(p=>p.alive!==false))items.push({id:`reunion-${g.year}`,title:'Family reunion',description:'Bring your family together for an afternoon.',cost:250});return items.filter((p,i,all)=>!celebrated.has(p.id)&&all.findIndex(n=>n.id===p.id)===i);}
export function celebrateMilestone(g,id){if(!g.alive)return fail(g,'This life has ended.');const w=worldState(g),m=availableMilestones(g).find(p=>p.id===id);if(!m)return fail(g,'This milestone was already celebrated or is no longer available.');const next=spend(g,m.cost,m.title);if(!next)return fail(g,'You need funds to host this celebration.');return result({...next,worldLife:{...w,celebrated:[...w.celebrated,id]},stats:{...g.stats,happiness:clamp((g.stats?.happiness||50)+8)},partner:g.partner?{...g.partner,closeness:clamp((g.partner.closeness||50)+4)}:null,children:(g.children||[]).map(p=>({...p,closeness:clamp((p.closeness||50)+4)}))},`You celebrated ${m.title.toLowerCase()}. Your family enjoyed the occasion and felt closer.`,'A personal milestone','🎉');}
export function finishWorldYear(input,random=Math.random){
 if(!input.alive)return input;const w=worldState(input);if(w.finishedYear===input.year)return input;let g={...input,worldLife:{...w,finishedYear:input.year}};
 g.assets=(g.assets||[]).map(a=>a.rental?.departedTenant?{...a,rental:{...a.rental,tenant:null,departedTenant:null}}:a);
 const s=w.school;if(g.age>=6&&g.age<18){if(s.club&&schoolClubs[s.club]){const key=schoolClubs[s.club].skill;g.skills={...g.skills,[key]:clamp((g.skills?.[key]||0)+4)};g=log(g,`Regular ${s.club.toLowerCase()} club meetings improved your ${key.toLowerCase()}.`,'School club','🎒');}if(!s.bullying&&random()<.18){g.worldLife.school={...s,bullying:{age:g.age,text:'A classmate has been excluding you and making cruel comments. Choose how to seek help.'}};g.stats={...g.stats,happiness:clamp((g.stats?.happiness||50)-6)};g=log(g,'A school bullying incident needs your attention in School.','School decision','🎒');}}
 if(g.partner&&g.age>=18&&g.partner.age>=18&&!w.relationshipEvent&&random()<Math.max(.08,(60-(g.partner.closeness||50))*.006)){g.worldLife.relationshipEvent={kind:'jealousy',title:'Jealousy is straining your relationship',text:`${g.partner.name} feels excluded and wants to talk about trust and time together.`,partnerId:g.partner.id};g.partner={...g.partner,trust:clamp((g.partner.trust??60)-8)};g=log(g,'Your partner wants to discuss jealousy and boundaries in Relationships.','Relationship decision','💞');}
 if(!w.custodyDispute&&g.age>=18&&random()<.15){const child=(g.children||[]).find(c=>c.alive!==false&&c.age<18&&c.otherParentId&&g.partner?.id!==c.otherParentId);if(child){g.worldLife.custodyDispute={childId:child.id,otherParentId:child.otherParentId,text:`The other parent of ${child.name} wants to revisit custody. You can seek mediation or request a family hearing.`};g=log(g,`A custody disagreement about ${child.name} needs a response in Relationships.`,'Co-parenting decision','👶');}}
 const milestones=[...w.milestones];if(g.age===18)milestones.push({id:'secondary-graduation',title:'School graduation',description:'Mark the end of secondary school.',cost:200});if(g.educationStatus==='graduated'&&!milestones.some(p=>p.id==='university-graduation'))milestones.push({id:'university-graduation',title:'University graduation',description:'Celebrate your degree with the people who supported you.',cost:300});if(g.retired&&!milestones.some(p=>p.id==='retirement'))milestones.push({id:'retirement',title:'Retirement celebration',description:'Celebrate the next chapter after your working life.',cost:400});g.worldLife={...g.worldLife,milestones};return g;
}
export function successionWorld(previous,child,next){
 const siblings=(previous.children||[]).filter(p=>p.id!==child.id&&p.alive!==false),unequal=previous.will&&siblings.some(p=>(Number(previous.will.beneficiaries?.find(b=>b.id===p.id)?.percent)||0)<(Number(previous.will.beneficiaries?.find(b=>b.id===child.id)?.percent)||0)),rivals=siblings.filter(p=>(p.closeness??50)<45||unequal||(next.companies||[]).length>0);
 const contested=rivals.length>0&&!worldState(previous).estateExplained,held=contested?Math.floor(Math.max(0,next.bankBalance||0)*.15):0;
 const updated={...next,bankBalance:(next.bankBalance||0)-held,companies:(next.companies||[]).map(c=>({...c,ceoSalary:0,successionDisputed:contested})),worldLife:{news:worldState(previous).news,market:worldState(previous).market,school:{},milestones:[],celebrated:[],relationshipHistory:[],inheritance:contested?{status:'Contested',held,claimants:rivals.map(p=>({id:p.id,name:p.name})),text:'Relatives dispute the estate allocation and control of the family company. Part of your inherited cash is held until the dispute is resolved.'}:null}};
 return contested?log(updated,`Relatives contested your inheritance. $${held.toLocaleString()} is held until you resolve the dispute in Life & Legacy → Family legacy.`,'Family estate','⚖️'):updated;
}
export function resolveCustodyDispute(g,choice,random=Math.random){
 const w=worldState(g),d=w.custodyDispute,child=(g.children||[]).find(p=>p.id===d?.childId);
 if(!g.alive||g.age<18||!d||!child||child.alive===false||child.age>=18)return fail(g,'There is no active custody dispute to resolve.');
 if(!['mediate','court'].includes(choice))return fail(g,'Choose mediation or a family hearing.');
 const paid=spend(g,choice==='mediate'?300:1500,'Custody dispute resolution');if(!paid)return fail(g,'You need funds for this process.');
 const agreed=random()<(choice==='mediate'?.8:.65),divorceOrder=(g.divorceObligations||[]).find(o=>o.childIds?.includes(child.id)),affected=new Set(divorceOrder?.childIds||[child.id]);
 const message=agreed?`A shared custody arrangement was agreed for ${child.name}${affected.size>1?' and their siblings':''}. Support payments will reflect the revised agreement.`:'The process kept the current custody arrangement. You agreed a clearer communication plan for co-parenting.';
 return result({...paid,children:(paid.children||[]).map(p=>agreed&&affected.has(p.id)?{...p,custody:'Shared'}:p),childSupportOrders:(paid.childSupportOrders||[]).map(o=>agreed&&affected.has(o.childId)?{...o,custody:'Shared',changedYear:g.year}:o),divorceObligations:(paid.divorceObligations||[]).map(o=>agreed&&o.id===divorceOrder?.id?{...o,custody:'Shared'}:o),worldLife:{...w,custodyDispute:null,relationshipHistory:[{age:g.age,title:'Custody disagreement',text:message},...w.relationshipHistory].slice(0,15)}},message,'Co-parenting','👶');
}
export function resolveInheritance(g,choice,random=Math.random){const w=worldState(g),d=w.inheritance;if(!d||d.status!=='Contested')return fail(g,'There is no unresolved inheritance dispute.');if(!['settle','court'].includes(choice))return fail(g,'Choose mediation or a court hearing.');const fee=choice==='settle'?Math.round(d.held*.3):Math.min(d.held,Math.max(500,Math.round(d.held*.1))),won=choice==='settle'||random()<.65,release=Math.max(0,Math.round((d.held-fee)*(won?1:.5)));const message=choice==='settle'?`Mediation resolved the inheritance dispute. $${fee.toLocaleString()} was shared with claimants and $${release.toLocaleString()} was released to you.`:`The estate hearing ${won?'upheld your allocation':'awarded part of the disputed estate to relatives'}. After fees, $${release.toLocaleString()} was released.`;return result({...g,bankBalance:(g.bankBalance||0)+release,companies:(g.companies||[]).map(c=>({...c,successionDisputed:false,morale:clamp((c.morale||50)+(choice==='settle'?5:-3))})),family:{...g.family,siblings:(g.family?.siblings||[]).map(p=>({...p,closeness:clamp((p.closeness||50)+(choice==='settle'?8:-8))}))},worldLife:{...w,inheritance:{...d,status:'Resolved',held:0,outcome:message}}},message,'Inheritance dispute','⚖️');}
