import {recordAge} from './lifeRecords.js';
import {NpcFinancialDetails} from './RelationshipGroups.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {PersonPortrait} from './RelationshipPortrait.jsx';
import {CharacterStatBars} from './FullStatsScreen.jsx';
import {findCasualProfile,declineCasualProfile,acceptCasualProfile} from './casualEncounters.js';
import './casual-encounters.css';
export default function OneNightStandScreen({game,setGame,onOpenSupport}){
 const [gender,setGender]=useState('Woman'),[protection,setProtection]=useState(true);const started=useRef(false),acceptButton=useRef(null);const p=game.casualEncounters?.profile;const available=game.alive&&game.age>=18&&!game.jail&&(game.realism?.energy??80)>=5;const searches=game.casualEncounters?.searchYear===game.year?game.casualEncounters.searches||0:0;const open=p?.year===game.year&&!p.resolved;
 useEffect(()=>{if(started.current)return;started.current=true;setGame(g=>findCasualProfile(g));},[setGame]);
 useEffect(()=>{if(!open)return;acceptButton.current?.focus();const keydown=e=>{if(e.key==='Escape')setGame(g=>declineCasualProfile(g));if(e.key==='Tab'){const controls=document.querySelectorAll('.casual-profile-dialog button:not(:disabled),.casual-profile-dialog input');const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keydown);return()=>document.removeEventListener('keydown',keydown);},[open,setGame]);
 return <div className="development-screen"><h2>A casual encounter</h2><p>Meet an adult, review their profile and decide whether you want a one-night stand. No club visit or entry fee is required.</p><label className="realism-control">Meet<select value={gender} onChange={e=>setGender(e.target.value)}>{['Woman','Man','Any'].map(v=><option key={v}>{v}</option>)}</select></label><p>Profiles this year: {searches}/6 · Energy {Math.round(game.realism?.energy??80)}/100</p><button disabled={!available||searches>=6||open} onClick={()=>{setProtection(true);setGame(g=>findCasualProfile(g,gender));}}>Meet someone</button>{!available&&<p>Available to living adults outside custody with at least 5 energy.</p>}{game.casualEncounters?.lastNotice&&<section role="status"><p>{game.casualEncounters.lastNotice}</p></section>}<p>Both people must consent. Protection reduces pregnancy risk. Pregnancy, births, health consequences and relationship trust use the same life systems as other encounters.</p>{onOpenSupport&&<button onClick={onOpenSupport}>Review child support</button>}<h3>Pregnancies</h3>{(game.pendingPregnancies||[]).length?(game.pendingPregnancies||[]).map(pregnancy=><section key={pregnancy.id}><b>Other parent: {pregnancy.otherParent.name}</b><p>Due in {pregnancy.dueYear} · Initial primary care: {pregnancy.custody.toLowerCase()}</p></section>):<p>No pending pregnancies.</p>}<h3>Past encounters</h3>{(game.casualEncounters?.encounters||[]).map((e,i)=><section key={`${e.personId}-${i}`}><b>Age {recordAge(e,game)} · {e.name}</b><p>{e.protectedEncounter?'Protected':'Unprotected'} encounter{e.pregnancy?' · Pregnancy confirmed':''}</p></section>)}
 {open&&<div className="dialog-backdrop casual-profile-backdrop"><section className="casual-profile-dialog" role="dialog" aria-modal="true" aria-labelledby="casual-profile-title"><button className="casual-profile-close" aria-label="Decline and close profile" onClick={()=>setGame(g=>declineCasualProfile(g))}><X/></button><div className="casual-profile-portrait"><PersonPortrait person={p}/></div><span className="eyebrow">ONE-NIGHT STAND</span><h2 id="casual-profile-title">{p.name}</h2><p>{p.gender} · Age {p.age} · {p.occupation}</p><p>{p.personality}</p><NpcFinancialDetails person={p}/><CharacterStatBars stats={{looks:p.looks,smarts:p.smarts,health:p.health,happiness:p.happiness}}/><p>Would you like to have intercourse with {p.name}? Their consent is also required.</p><label className="casual-protection"><input type="checkbox" checked={protection} onChange={e=>setProtection(e.target.checked)}/> Use protection</label><div className="development-actions"><button disabled={!available} onClick={()=>setGame(g=>acceptCasualProfile(g,protection))}>Have intercourse</button><button ref={acceptButton} onClick={()=>setGame(g=>declineCasualProfile(g))}>Decline</button></div></section></div>}
 </div>;
}
