import {HeartPulse,Users,Mic,Handshake,ChevronRight,Trophy} from 'lucide-react';
import React from 'react';
import {useFeedbackNotice} from './OutcomeFeedback.jsx';
import {fameRoles,fameCareerAction,sportsCareerAction} from './publicCareers.js';
import {fameLevel} from './lifeDepth.js';
import {enrichmentState} from './enrichmentCore.js';
import {formatMoney} from './money.js';
const fmt=formatMoney;
function useCareerAction(setGame){const [notice,setNotice]=useFeedbackNotice('');return [notice,fn=>setGame(g=>{const result=fn(g);setNotice(result.error||result.message);return result.game;})];}
export function FameCareerPanel({game,setGame,onSocial,onRenew}){const role=fameRoles[game.job],p=game.publicCareer||{},c=game.fameContract;const [notice,run]=useCareerAction(setGame);const [approach,setApproach]=React.useState('Commercial');if(!role)return null;const actions=p.actionYear===game.year?p.actions||[]:[],blocked=!game.alive||game.jail?.yearsRemaining>0||c?.status!=='active';return <section className="enrichment-card public-career-panel"><span className="eyebrow">YOUR PUBLIC CAREER</span><h3>{game.job}</h3><p>{fameLevel(game.fame||0)} · Fame {Math.round(game.fame||0)}/100 · Craft {p.craft??30}/100 · Professional reputation {p.reputation??50}/100</p><div className="public-career-metrics"><div><small>Contract pay / year</small><b>{fmt(c?.annualSalary||game.salary||0)}</b></div><div><small>Contract status</small><b>{c?.status==='active'?`${c.yearsRemaining} years remaining`:'Renewal needed'}</b></div><div><small>Performance</small><b>{c?.performance??60}%</b></div><div><small>{role.credits}</small><b>{(p.portfolio||[]).filter(e=>e.role===game.job).length}</b></div></div><p>Choose three different activities each year. Practice improves your craft; projects build credits and recognition. Contracts pay through annual employment income, while successful projects can pay a separate bonus.</p>{notice&&<p className="enrichment-notice" role="status">{notice}</p>}<label>Project approach<select aria-label="Project approach" value={approach} onChange={e=>setApproach(e.target.value)}><option>Independent</option><option>Commercial</option><option>Prestige</option></select></label><p>Independent projects cost less. Prestige projects cost more and are harder to land, but can bring greater recognition.</p><div className="enrichment-actions">{[['practice',role.practice,350],['project',role.project,Math.round(role.cost*(approach==='Independent'?.6:approach==='Prestige'?1.5:1))],['publicity','Give a press interview',750],['network','Meet industry collaborators',250],['rest','Take a recovery break',0]].map(([a,label,cost])=><button key={a} disabled={blocked||actions.includes(a)||actions.length>=3} onClick={()=>run(g=>fameCareerAction(g,a,approach))}>{label}<small>{actions.includes(a)?'Completed this year':cost?fmt(cost):'Rest and wellbeing'}</small></button>)}</div><p>{actions.length}/3 activities completed this year.</p><div className="enrichment-actions">{onRenew&&<button disabled={!game.alive||game.jail?.yearsRemaining>0} onClick={onRenew}>Discuss contract renewal</button>}<button onClick={onSocial}>Open Social Media<small>Your fame, reputation and public appearances shape your audience.</small></button></div>{(p.portfolio||[]).filter(e=>e.role===game.job).slice(0,8).map(e=><article className="public-career-credit" key={e.id}><b>{e.title}</b><small>Age {e.age} · {e.approach} · {e.status} · rating {e.rating}/100</small>{e.bonus>0&&<span>Project bonus {fmt(e.bonus)}</span>}</article>)}</section>;}
export function SportsActivityPanel({game,setGame,onSocial}){
 const s=enrichmentState(game).sports;const [notice,run]=useCareerAction(setGame);if(!s||s.stage==='Retired')return null;
 const actions=s.actionYear===game.year?s.actions||[]:[],blocked=!game.alive||game.jail?.yearsRemaining>0,injured=s.injuredUntil>game.year,completed=actions.includes('competition'),latest=s.competitions?.[0];const emoji={Football:'⚽',Basketball:'🏀',Tennis:'🎾',Track:'👟'}[s.sport]||'🏅';
 return <section className="sports-club-activities"><div className="sports-section-heading"><div><span className="sports-kicker">LIVE THE SPORT</span><h3>Inside the clubhouse</h3></div><span className="sports-activity-count">{actions.length}/3 activities</span></div>
 {game.fameContract?.sports&&<div className="sports-contract-ribbon"><Handshake size={22}/><div><small>YOUR CLUB CONTRACT</small><b>{fmt(game.fameContract.annualSalary||game.salary)} <span>/ year</span></b><p>{game.fameContract.status==='active'?`${game.fameContract.yearsRemaining} seasons remaining`:'Renewal needed'} · Performance {game.fameContract.performance}%</p></div></div>}
 <article className="sports-matchday"><div className="sports-matchday-top"><span>✦ {completed?'MATCH REPORT':'MATCH DAY'}</span><span>{s.stage==='Professional'?'LEAGUE FIXTURE':'LOCAL CIRCUIT'}</span></div><div className="sports-matchday-body"><span className="sports-match-ball" aria-hidden="true">{emoji}</span><div><h4>{completed&&latest?latest.result==='Won'?'A result to celebrate.':'Come back stronger.':injured?'Your comeback starts here.':'Time to make your mark.'}</h4><p>{completed&&latest?`Performance ${latest.score}/100 · ${latest.injury?'An injury cut the celebration short.':'The final whistle is in your history.'}`:injured?'Recover with your physiotherapist before returning to competition.':s.stage==='Professional'?'Your club is counting on you. Bring your training to the big stage.':'Take your training into competition and show what you can do.'}</p></div></div><button disabled={blocked||completed||actions.length>=3||injured} onClick={()=>run(g=>sportsCareerAction(g,'competition'))}>{completed?'Fixture completed this year':s.stage==='Professional'?'Play a league fixture':'Enter a local competition'}<ChevronRight size={18}/></button></article>
 <div className="sports-training-focus"><label>Training focus<select aria-label="Training focus" value={s.focus||'Technique'} disabled={blocked} onChange={e=>{const focus=e.target.value;run(g=>sportsCareerAction(g,'focus',focus));}}>{['Technique','Fitness','Teamwork'].map(n=><option key={n}>{n}</option>)}</select></label><p>{s.focus==='Fitness'?'Build stamina, conditioning and a body that can go the distance.':s.focus==='Teamwork'?'Read the game, support your teammates and lift your contract performance.':'Sharpen your technique and build the skill that gets scouts watching.'}</p></div>
 {notice&&<p className="enrichment-notice" role="status">{notice}</p>}
 <div className="sports-club-action-grid">{[['rehab','Work with a physiotherapist',game.age<18?'School support':'$600 · recovery and fitness',HeartPulse,'recovery'],['tryout','Attend a club tryout','$250 · age 18+ and skill 50',Users,'scouting'],['renew','Negotiate with your club','Renew your deal. Plan your next chapter.',Handshake,'contract'],['media','Give a sports interview','Age 16+ · let supporters hear your story',Mic,'media']].map(([a,label,detail,Icon,tone])=><button className={`sports-club-action ${tone}`} key={a} disabled={blocked||actions.includes(a)||actions.length>=3||(a==='renew'&&!game.fameContract?.sports)} onClick={()=>run(g=>sportsCareerAction(g,a))}><span className="sports-action-icon"><Icon size={22}/></span><span><b>{label}</b><small>{actions.includes(a)?'✓ Completed this year':detail}</small></span><ChevronRight size={17}/></button>)}</div>
 <aside className="sports-coach-note"><span aria-hidden="true">📋</span><p><b>From the touchline</b>{injured?'You cannot rush a comeback. Recover first; the season will still be there.':s.skill<60?'Keep working on your skill. At 60, scouts can start sending yearly offers.':s.fitness<50?'Your conditioning needs some attention. Recovery work can put you back in a stronger position.':'You have put in the work. Compete, stay fit, and be ready when a club comes calling.'}</p></aside>
 {onSocial&&<button className="sports-supporters-link" onClick={onSocial}><span aria-hidden="true">📣</span><span>Open Social Media · connect with supporters<small>{fameLevel(game.fame||0)} · Fame {Math.round(game.fame||0)}/100</small></span><ArrowIcon/></button>}
 {(s.competitions||[]).length>0&&<div className="sports-results"><div className="sports-section-heading"><h3>From the final whistle</h3><Trophy size={18}/></div>{s.competitions.slice(0,6).map((e,i)=><article className={`sports-result ${e.result==='Won'?'won':'lost'}`} key={`${e.year}-${i}`}><span className="sports-result-stamp">{e.result==='Won'?'W':'L'}</span><div><b>{e.result==='Won'?'Victory':'Learning experience'}</b><small>Age {e.age} · {e.year} · {e.injury?'Injury sustained':'Finished healthy'}</small></div><div className="sports-result-score"><b>{e.score}</b><small>PERFORMANCE</small></div></article>)}</div>}
 </section>;
}
function ArrowIcon(){return <ChevronRight size={18}/>;}
