import {spend} from './futurePlanning.js';
import {enrichmentState,enrich,note,success,failure,clamp} from './enrichmentCore.js';
export const sportsTitles={Football:'Professional Football Athlete',Basketball:'Professional Basketball Athlete',Tennis:'Professional Tennis Athlete',Track:'Professional Track Athlete'};
const oldSports={'Professional Footballer':'Football','Professional Basketball Player':'Basketball'};
export const fameRoles={
 'Screen Actor':{skill:'Charisma',project:'Audition & film a role',practice:'Acting workshop',credits:'Film credits',cost:1200},
 'Recording Musician':{skill:'Music',project:'Record & release a single',practice:'Vocal & instrument rehearsal',credits:'Music releases',cost:1800},
 'Film Director':{skill:'Technology',project:'Pitch & direct a film',practice:'Directing & production workshop',credits:'Directed films',cost:3500},
 'Music Label Executive':{skill:'Charisma',project:'Scout an artist & launch a release',practice:'Artist development workshop',credits:'Artist campaigns',cost:2500},
 'Music Producer':{skill:'Music',project:'Produce a recording session',practice:'Studio production workshop',credits:'Production credits',cost:1500},
 'Stand-up Comedian':{skill:'Charisma',project:'Write & perform a touring set',practice:'Rehearse at an open mic',credits:'Comedy shows',cost:600}
};
export const isSportsJob=title=>!!oldSports[title]||Object.values(sportsTitles).includes(title);
export const isFameJob=title=>isSportsJob(title)||!!fameRoles[title];
export function publicCareerReview(g,result){if(!isFameJob(g.job))return result;const year=g.year+1,entry={year,age:g.age+1,role:g.job,salaryIncome:result.salaryIncome,performance:result.fameContract?.performance??60,contractStatus:result.fameContract?.status||'active'};return {...result,careerYears:(g.careerYears||0)+1,publicCareer:{...g.publicCareer,annualReviews:[entry,...(g.publicCareer?.annualReviews||[])]}};}
export function signFameContract(g,job,salary,years,renewal=false){if(!g.alive||g.jail?.yearsRemaining>0||!fameRoles[job.title])return failure(g,'You must be living, free to work and signing a fame role.');const minimum=['Screen Actor','Recording Musician','Stand-up Comedian'].includes(job.title)?13:16;if(g.age<minimum||g.educationStudy||g.educationStatus==='enrolled')return failure(g,'Finish full-time studies and meet the role’s minimum age before signing.');if(renewal?g.job!==job.title||g.fameContract?.signedYear===g.year:!!g.job)return failure(g,renewal?'Your contract has already been signed this year, or you have left this role.':'Leave your current job before signing another contract.');if(!Number.isFinite(salary)||salary<=0||!Number.isInteger(years)||years<1||years>5)return failure(g,'Choose a valid salary and a contract of one to five years.');const next={...g,job:job.title,salary,career:job.category||'Premium · Fame',careerYears:renewal?g.careerYears||0:0,fame:clamp((g.fame||0)+(renewal?0:job.fame||0)),fameContract:{status:'active',annualSalary:salary,yearsRemaining:years,performance:renewal?g.fameContract?.performance??60:65,signedYear:g.year,negotiated:salary>job.salary}};return success(next,`${renewal?'Renewal':'Contract'} signed: ${years} years at $${salary.toLocaleString()} per year.`,'Fame contract','📝');}
export function normalizePublicCareer(g){if(!isSportsJob(g.job))return g;const sport=oldSports[g.job]||Object.keys(sportsTitles).find(s=>sportsTitles[s]===g.job),saved=enrichmentState(g).sports;const contract=g.fameContract||{status:'active',annualSalary:g.salary||0,yearsRemaining:2,performance:65,signedYear:g.year};if(saved?.sport===sport&&saved.stage==='Professional'&&g.job===sportsTitles[sport]&&contract.sports)return g;return enrich({...g,job:sportsTitles[sport],fameContract:{...contract,sports:true}},'sports',{...saved,sport,skill:saved?.skill??contract.performance??65,fitness:saved?.fitness??75,stage:'Professional',club:saved?.club||'Current club',injuredUntil:saved?.injuredUntil||0,offers:saved?.offers||[],history:saved?.history||[]});}
const careerState=g=>({reputation:50,craft:30,portfolio:[],history:[],...g.publicCareer,actions:g.publicCareer?.actionYear===g.year?g.publicCareer.actions||[]:[]});
export function fameCareerAction(g,action,approach='Commercial',random=Math.random){const role=fameRoles[g.job],c=g.fameContract;const minimum=['Screen Actor','Recording Musician','Stand-up Comedian'].includes(g.job)?13:16;if(!g.alive||g.age<minimum||g.jail?.yearsRemaining>0||!role||c?.status!=='active')return failure(g,'You need an active fame contract and must be free to work.');const p=careerState(g);if(p.actions.includes(action)||p.actions.length>=3)return failure(g,'Choose up to three different career actions each year.');if(!['practice','project','publicity','network','rest'].includes(action))return failure(g,'Choose a career action.');if(!['Independent','Commercial','Prestige'].includes(approach))return failure(g,'Choose a project approach.');const factor=approach==='Independent'?.6:approach==='Prestige'?1.5:1;const cost=action==='practice'?350:action==='project'?Math.round(role.cost*factor):action==='publicity'?750:action==='network'?250:0;let next=cost?spend(g,cost,`${g.job} · ${action}`):g;if(!next)return failure(g,`This action costs $${cost.toLocaleString()}.`);let craft=p.craft,rep=p.reputation,performance=c.performance??60,fame=g.fame||0,portfolio=p.portfolio,message='';
 if(action==='practice'){craft=clamp(craft+8);performance=clamp(performance+6);next={...next,skills:{...g.skills,[role.skill]:clamp((g.skills?.[role.skill]||10)+5)}};message=`${role.practice} improved your craft and contract performance.`;}
 if(action==='project'){const chance=Math.max(.12,Math.min(.92,.3+craft*.003+performance*.002+rep*.001-(approach==='Prestige'?.12:0)));const won=random()<chance;const rating=clamp(Math.round(craft*.35+performance*.4+random()*25));const bonus=won?Math.round((c.annualSalary||g.salary||0)*.025*factor):0;fame=clamp(fame+(won?(approach==='Prestige'?7:4):-2));rep=clamp(rep+(won?6:-4));performance=clamp(performance+(won?5:-3));const entry={id:`project-${g.year}-${g.job}`,year:g.year,age:g.age,role:g.job,title:role.project,approach,rating,status:won?'Successful':'Underperformed',bonus};portfolio=[entry,...portfolio];if(bonus)next={...next,money:(next.money||0)+bonus,lifetimeIncome:(next.lifetimeIncome||0)+bonus,transactions:[{year:g.year,age:g.age,label:`${g.job} project bonus`,amount:bonus},...(next.transactions||[])]};message=`Your ${approach.toLowerCase()} project ${won?'connected with audiences':'underperformed'}. Critics rated it ${rating}/100.${bonus?` You earned a $${bonus.toLocaleString()} project bonus.`:''}`;}
 if(action==='publicity'){const respectful=random()<.85;fame=clamp(fame+(respectful?3:-4));rep=clamp(rep+(respectful?3:-6));message=respectful?'Your interview introduced your work to new audiences. Public accounts gain followers as your fame grows.':'A careless interview answer drew criticism and damaged your reputation.';}
 if(action==='network'){rep=clamp(rep+5);performance=clamp(performance+2);message='You met collaborators and strengthened your professional reputation.';}
 if(action==='rest'){performance=clamp(performance+3);next={...next,stats:{...next.stats,health:clamp((next.stats?.health||50)+3),happiness:clamp((next.stats?.happiness||50)+4)},realism:next.realism?{...next.realism,burnout:Math.max(0,(next.realism.burnout||0)-10)}:next.realism};message='A break helped your wellbeing and gave you perspective for your next project.';}
 next={...next,fame,fameContract:{...c,performance},publicCareer:{...p,role:g.job,craft,reputation:rep,portfolio,actionYear:g.year,actions:[...p.actions,action],history:[{year:g.year,age:g.age,action,message},...p.history]}};return success(next,message,'Fame career','⭐');}
export function sportsCareerAction(input,action,value,random=Math.random){const g=normalizePublicCareer(input),s=enrichmentState(g).sports;if(!g.alive||!s||s.stage==='Retired'||g.jail?.yearsRemaining>0)return failure(input,'You need an active sporting career and must be free to participate.');const actions=s.actionYear===g.year?s.actions||[]:[];if(action!=='focus'&&(actions.includes(action)||actions.length>=3))return failure(input,'Choose up to three different sports activities per year.');if(!['competition','rehab','tryout','renew','focus','media'].includes(action))return failure(input,'Choose a sports activity.');let next=g,updated=s,message='';
 if(action==='focus'){if(!['Technique','Fitness','Teamwork'].includes(value))return failure(input,'Choose a training focus.');return success(enrich(g,'sports',{...s,focus:value}),`Your training now focuses on ${value.toLowerCase()}.`,'Sports preparation','🏅');}
 if(action==='rehab'){if(s.injuredUntil<=g.year&&s.fitness>=95)return failure(input,'Your fitness is already excellent.');next=spend(g,g.age<18?0:600,'Sports rehabilitation');if(!next)return failure(input,'Rehabilitation costs $600.');updated={...s,fitness:clamp(s.fitness+15),injuredUntil:Math.max(g.year,s.injuredUntil-1)};message='Your physiotherapist helped you recover fitness and return safely to training.';}
 if(action==='competition'){if(s.injuredUntil>g.year)return failure(input,'Recover from your injury before competing.');const score=Math.round(s.skill*.55+s.fitness*.25+random()*20),won=score>=65;const injury=random()<.05;updated={...s,fitness:clamp(s.fitness-5),injuredUntil:injury?g.year+1:s.injuredUntil,competitions:[{year:g.year,age:g.age,score,result:won?'Won':'Lost',injury},...(s.competitions||[])]};next={...next,fame:clamp((next.fame||0)+(won?(s.stage==='Professional'?5:2):0)),...(g.fameContract?.sports?{fameContract:{...g.fameContract,performance:clamp((g.fameContract.performance||60)+(won?5:-3))}}:{})};message=`You ${won?'won':'lost'} your ${s.stage==='Professional'?'league fixture':'local competition'} with a performance score of ${score}/100.${injury?' You sustained an injury and need recovery.':''}`;}
 if(action==='tryout'){if(g.age<18||g.age>=38||s.skill<50||s.injuredUntil>g.year)return failure(input,'Tryouts need a healthy adult athlete under 38 with skill 50.');next=spend(g,250,'Club scouting combine');if(!next)return failure(input,'The scouting combine costs $250.');const won=random()<Math.min(.9,.2+s.skill*.005+s.fitness*.002);updated=won?{...s,offers:[{id:`tryout-${g.year}`,club:`${g.country} Sporting Club`,salary:Math.round(18000+s.skill*s.skill*12),years:3,expires:g.year+1},...(s.offers||[]).filter(o=>o.expires>=g.year)]}:s;message=won?'A scout offered a contract. Review the salary and choose whether to sign or transfer.':'Scouts passed this time. Improve your technique and fitness before your next tryout.';}
 if(action==='renew'){if(!g.fameContract?.sports||s.stage!=='Professional'||g.age>=38)return failure(input,'Renewals are for professional athletes under 38.');const performance=g.fameContract.performance??60;const accepted=random()<Math.max(.1,Math.min(.95,.2+performance*.007));if(accepted){const salary=Math.round((g.fameContract.annualSalary||g.salary||18000)*(performance>=75?1.12:performance<45?.85:1));next={...next,salary,fameContract:{...g.fameContract,status:'active',annualSalary:salary,yearsRemaining:3,signedYear:g.year}};message=`Your club renewed your contract for three seasons at $${salary.toLocaleString()} per year.`;}else message='Your club declined to renew. Your existing contract terms still apply; try another club.';}
 if(action==='media'){if(g.age<16)return failure(input,'Sports media appearances open at 16.');next={...next,fame:clamp((g.fame||0)+2)};message='You shared your sporting story in an interview. Growing fame helps your public social media accounts attract followers.';}
 updated={...updated,actionYear:g.year,actions:[...actions,action]};return success(enrich(next,'sports',updated),message,'Sports career','🏅');}
