import {simulationSettings} from './simulationSettings.js';
import {recordJobChance} from './criminalConsequences.js';
import {advanceNpcEconomy} from './npcEconomy.js';
import {funds,spend,insuredExpense,insuredQuote} from './futurePlanning.js';
import {countryBudgets} from './lifeSystems.js';
import {formatMoney} from './money.js';

const clamp=n=>Math.max(0,Math.min(100,n));
const hash=s=>[...String(s)].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7);
const log=(g,text,tag='Daily life',icon='📖')=>({...g,log:[{year:g.year,age:g.age,text,tag,icon},...(g.log||[])]});
export const interests=['music','technology','art','sport','nature','business'];
export const goals=['Family','Career','Adventure','Stability'];
export const housingOptions={family:{name:'Family home',rentFactor:0,quality:55,commute:4},shared:{name:'Shared apartment',rentFactor:.35,quality:50,commute:6},apartment:{name:'Private apartment',rentFactor:.65,quality:65,commute:4},suburban:{name:'Suburban house',rentFactor:1,quality:80,commute:8}};
export const careOptions={none:{name:'No arranged care',hours:0,cost:0},visits:{name:'Weekly visits',hours:4,cost:0},home:{name:'Care at home',hours:12,cost:1200},professional:{name:'Professional home care',hours:2,cost:7000},residential:{name:'Residential care',hours:1,cost:18000}};
export const healthDefinitions={hypertension:{name:'Hypertension',cost:600,drain:4,minAge:40},arthritis:{name:'Arthritis',cost:900,drain:4,minAge:55},diabetes:{name:'Type 2 diabetes',cost:1200,drain:5,minAge:35},injury:{name:'Recovering injury',cost:450,drain:3,minAge:0}};
export function normalizeRealism(g){
 const saved=g.realism||{};
 return {...g,realism:{energy:80,stress:20,burnout:0,mobility:Math.max(15,100-Math.max(0,(g.age||0)-60)*1.5),goal:'Family',diet:'Balanced',exercise:'Moderate',conditions:[],reputation:50,promises:[],memories:[],carePlans:{},housingArrears:0,careArrears:0,...saved,
  schedule:{sleep:8,study:6,hobbies:6,social:6,exercise:3,...saved.schedule},
  career:{performance:55,history:[],...saved.career},
  housing:{...startingHousing(g),...saved.housing},
  economy:{phase:'Stable',inflation:.025,priceIndex:1,unemployment:.05,housingIndex:1,history:[],...saved.economy}
 }};
}
export function weeklySchedule(input){const g=normalizeRealism(input),r=g.realism,s=r.schedule;const school=g.age>=5&&g.age<18||g.educationStatus==='enrolled'||Boolean(g.educationStudy)||g.educationStatus==='university'?30:0;const work=g.job&&!g.retired&&!g.jail? (r.career.plan==='leave'?0:r.career.plan==='part-time'?24:40):g.age>=18&&g.companies?.some(c=>!c.professionalManagerSalary)&&!g.retired?35:0;const parenting=(g.children||[]).filter(c=>c.alive!==false&&c.age<18&&c.custody!=='Other parent').reduce((n,c)=>n+(c.age<6?12:5),0);const commute=school||work&&!r.career.remote?r.housing.commute??housingOptions[r.housing.type]?.commute??4:0;const care=Object.values(r.carePlans).reduce((n,p)=>n+(careOptions[p.type]?.hours||0),0);const values={Sleep:(Number(s.sleep)||8)*7,Work:work,School:school,Commuting:commute,'Business management':g.companies?.length&&g.job&&g.job!=='Founder & CEO'?12:0,Parenting:parenting,Caregiving:care,Studying:s.study||0,Hobbies:s.hobbies||0,Relationships:s.social||0,Exercise:s.exercise||0,'Essential chores':14};const total=Object.values(values).reduce((n,v)=>n+v,0);return {values,total,free:168-total,overload:Math.max(0,total-168)};}
export function setSchedule(g,key,value){if(!g.alive||!['sleep','study','hobbies','social','exercise'].includes(key))return g;const max=key==='sleep'?10:30,min=key==='sleep'?4:0;const r=normalizeRealism(g).realism;return {...g,realism:{...r,schedule:{...r.schedule,[key]:Math.max(min,Math.min(max,Number(value)||min))}}};}
export function setRoutine(g,key,value){if(!g.alive||!({diet:['Balanced','Nutritious','Convenience'],exercise:['Rest','Moderate','Active'],goal:goals,work:['Standard','part-time','leave']}[key]||[]).includes(value))return g;const r=normalizeRealism(g).realism;return {...g,realism:key==='work'?{...r,career:{...r.career,plan:value==='Standard'?null:value}}:{...r,[key]:value}};}
export function workingRate(g){const plan=g.realism?.career?.plan;return (plan==='leave'?0:plan==='part-time'?.6:1)*(g.fameContract?.sports&&g.enrichment?.sports?.injuredUntil>g.year?.5:1);}
export function recordConsequence(g,choice,event){const r=normalizeRealism(g).realism;const effects=choice.effects||{};let delta=Math.sign(effects.careerReputation||0)*2;if(event?.key==='university-integrity'&&effects.universityStanding<0)delta=-6;if(event?.key==='university-lab-practical'&&effects.universityStanding<0)delta=-5;if(!delta)return g;return {...g,realism:{...r,reputation:clamp(r.reputation+delta),memories:[{key:`consequence-${event.key}-${g.year}`,year:g.year,text:`${event.title}: ${choice.label}`},...r.memories].slice(0,100)}};}
export function prepareChildChoices(g){return {...g,children:(g.children||[]).map(p=>{if(p.alive===false||p.age<18||p.ownEducationChoice)return p;const child=personState(p,g),plan=g.educationPlans?.[p.id];const own=child.interest==='technology'||(p.smarts??55)>=70?'University':child.interest==='sport'||child.interest==='nature'?'Vocational':'Work';const choice=plan&&child.autonomy<65&&(p.closeness??50)>=55?plan.path:own;return {...child,ownEducationChoice:choice,decisionYear:g.year};})};}
export function exertActivity(g,title){const r=normalizeRealism(g).realism,rest=/rest|wellness|care of yourself/i.test(title);return {...g,realism:{...r,energy:clamp(r.energy+(rest?8:-4)),stress:clamp(r.stress+(rest?-4:weeklySchedule(g).overload>0?2:0))}};}
export function startingHousing(g){const asset=(g.assets||[]).find(a=>a.id===g.livingArrangement?.assetId&&a.category==='Homes'&&!a.rentedOut);return asset?{type:asset.status==='owned'?'owned':'asset',assetId:asset.id,sourceAssetId:asset.id,country:g.country,quality:70,commute:5}:{type:'family',country:g.country,quality:55};}
export function surgeryRecovery(g,complication){const r=normalizeRealism(g).realism;return {...r,conditions:[...r.conditions,{id:`surgery-${g.year}`,type:'injury',severity:complication?50:15,remaining:complication?2:1,managed:!complication,treatmentYear:complication?null:g.year}],energy:clamp(r.energy-15)};}
export function mortgageQuote(g){const r=normalizeRealism(g).realism;const price=Math.round((countryBudgets[g.country]?.[0]||8000)*18*r.economy.housingIndex),down=Math.round(price*.2),principal=price-down,apr=.055+(r.economy.phase==='Recession'?.01:0);const monthlyPayment=Math.ceil(principal*apr/12/(1-Math.pow(1+apr/12,-300)));const reason=!g.alive?'This life has ended.':g.age<18?'Available at age 18.':r.housing.purchaseYear===g.year?'You already bought a home this year.':(g.creditScore??680)<620?'Requires a credit score of 620.':funds(g)<down?`Save ${formatMoney(down-funds(g))} more for the down payment.`:Math.max(0,g.salary||0)*.35<monthlyPayment*12?'Mortgage payments would exceed 35% of your annual salary.':null;return {price,down,principal,apr,monthlyPayment,reason};}
export function employmentBonus(g){const r=normalizeRealism(g).realism;return (r.reputation-50)*.001-r.economy.unemployment*.4-r.burnout*.001;}
export function prepareInterview(g,job){if(!g.alive||g.job||g.pendingInterview)return g;return log({...g,pendingInterview:{job:{...job,salary:Math.round(job.salary*(g.realism?.economy?.priceIndex||1)*(g.realism?.economy?.phase==='Expansion'?1.08:g.realism?.economy?.phase==='Recession'?.94:1))},year:g.year}},`You were shortlisted for ${job.title}. Complete your interview in Work life.`,'Interview','💼');}
export function completeInterview(g,answer,rng=Math.random){if(!g.pendingInterview||!g.alive||g.job)return g;if(g.pendingInterview.year!==g.year)return log({...g,pendingInterview:null},'The interview invitation expired. Apply for a current opening.','Interview expired','💼');const r=normalizeRealism(g).realism,job=g.pendingInterview.job;const chance=recordJobChance(g,Math.max(.1,Math.min(.94,.48+(g.skills?.Charisma||0)*.002+(g.skills?.Discipline||0)*.001+employmentBonus(g)+(answer==='examples'?.15:answer==='honest'?.08:-.15))));const hired=rng()<chance;return log({...g,pendingInterview:null,...(hired?{job:job.title,salary:job.salary,career:job.category,careerYears:0,fameContract:null}:{}),realism:{...r,reputation:clamp(r.reputation+(answer==='exaggerate'?-4:1)),career:{...r.career,role:hired?job.title:r.career.role,probation:hired,performance:hired?55:r.career.performance,workFriend:hired?'New colleague':r.career.workFriend,history:[{year:g.year,role:job.title,outcome:hired?'Hired on probation':'Interview declined'},...(r.career.history||[])].slice(0,30)}}},hired?`Your interview for ${job.title} succeeded. Your first year is probation; annual salary ${formatMoney(job.salary)}.`:`The ${job.title} interview did not result in an offer.${g.criminalRecord?.length?' Your background check substantially reduced your chances.':''} Your preparation still gave you useful experience.`,'Interview result','💼');}
export function workAction(g,action){if(!g.alive||!g.job)return g;const r=normalizeRealism(g).realism;if(r.career.actionYear===g.year)return g;const valid=['feedback','mentor','network','change'];if(!valid.includes(action))return g;const career={...r.career,actionYear:g.year};if(action==='change'){career.history=[{year:g.year,role:g.job,outcome:'Left to change career'},...(career.history||[])];return log({...g,job:null,salary:0,career:'Career transition',careerYears:0,realism:{...r,career:{...career,role:null,probation:false}}},'You left your role to pursue a career change. Apply for a new role; qualifications and skills still matter.','Career change','🧭');}career.performance=clamp((career.performance||55)+(action==='feedback'?8:action==='mentor'?6:2));career.workFriend=action==='network'?'Trusted colleague':career.workFriend;return log({...g,careerReputation:clamp((g.careerReputation||0)+2),realism:{...r,career,reputation:clamp(r.reputation+2)}},action==='feedback'?'You requested feedback and agreed on a performance improvement plan.':action==='mentor'?'You worked with a mentor to develop skills for your next role.':'You made time for a colleague and built a stronger workplace friendship.','Work life','💼');}
const personState=(p,g)=>({...p,trust:p.trust??65,compatibility:p.compatibility??45+hash(p.id||p.name)%45,sharedGoal:p.sharedGoal||goals[hash(p.id||p.name)%goals.length],autonomy:p.autonomy??50,interest:p.interest||interests[hash(p.id||p.name)%interests.length]});
const people=g=>[...(g.family?.parents||[]),...(g.family?.siblings||[]),...(g.children||[]),...(g.friends||[]),...(g.partner?[g.partner]:[])];
export function relationshipDetails(p,g){return personState(p,g);}
export function canCoparent(g,id){return (g.children||[]).some(c=>c.age<18&&c.alive!==false)&&(g.partner?.id===id||(g.divorceObligations||[]).some(o=>o.formerSpouseId===id)||(g.childSupportOrders||[]).some(o=>o.otherParentId===id&&(g.children||[]).some(c=>c.id===o.childId&&c.age<18&&c.alive!==false)));}
function mapPerson(g,id,fn){return {...g,partner:g.partner?.id===id?fn(g.partner):g.partner,children:(g.children||[]).map(p=>p.id===id?fn(p):p),friends:(g.friends||[]).map(p=>p.id===id?fn(p):p),family:{...g.family,parents:(g.family?.parents||[]).map(p=>p.id===id?fn(p):p),siblings:(g.family?.siblings||[]).map(p=>p.id===id?fn(p):p)}};}
export function relationshipAction(g,id,action){const found=people(g).find(p=>p.id===id&&p.alive!==false);if(!g.alive||!found||!['talk','counselling','promise','argue','support','pressure','coparent'].includes(action))return g;if(found.country&&found.country!==(g.educationStudy?.country||g.country)&&!(g.activeVisit?.personId===id&&g.activeVisit.year===g.year)&&['counselling','coparent'].includes(action))return g;const r=normalizeRealism(g).realism;const key=`${id}-${action}`;if(r.memories.some(m=>m.key===key&&m.year===g.year))return g;if(action==='coparent'&&!canCoparent(g,id)||['support','pressure'].includes(action)&&!(g.children||[]).some(c=>c.id===id))return g;let paid=g;if(action==='counselling'){paid=spend(g,180,'Relationship counselling');if(!paid)return g;}const p=personState(found,g);const bond=action==='argue'?-10:action==='pressure'?-7:action==='counselling'?9:6;const trust=action==='argue'?-8:action==='pressure'?-5:action==='promise'?0:5;const promises=[...r.promises];if(action==='promise')promises.push({id:`promise-${id}-${g.year}`,personId:id,name:p.name,year:g.year,deadline:g.year+1,status:'pending'});if(['talk','support','coparent'].includes(action))for(let i=0;i<promises.length;i++)if(promises[i].personId===id&&promises[i].status==='pending')promises[i]={...promises[i],status:'fulfilled'};const message=action==='promise'?`You promised ${p.name} time and support. Talk, support their interests or co-parent before next year to keep it.`:action==='support'?`You supported ${p.name}'s interest in ${p.interest}, even if it differs from your plans.`:action==='pressure'?`You pressured ${p.name} to follow your preferred path. Their trust and independence suffered.`:action==='argue'?`An argument with ${p.name} hurt trust. A later conversation or counselling may repair the relationship.`:action==='coparent'?`You and ${p.name} agreed on routines and expenses for the children.`:action==='counselling'?`You and ${p.name} used counselling to discuss recurring disagreements.`:`You listened to ${p.name}'s hopes for ${p.sharedGoal.toLowerCase()} and made time to reconnect.`;let next=mapPerson(paid,id,old=>({...personState(old,g),closeness:clamp((old.closeness??50)+bond),trust:clamp(p.trust+trust),autonomy:clamp(p.autonomy+(action==='support'?8:action==='pressure'?-10:0)),memory:[...(old.memory||[]),{year:g.year,age:g.age,action,detail:message}],memories:[...(old.memories||[]),message].slice(-10)}));next.realism={...r,promises,stress:clamp(r.stress+(action==='argue'?6:action==='counselling'?-6:0)),reputation:clamp(r.reputation+(action==='argue'||action==='pressure'?-2:action==='promise'?0:1)),memories:[{key,year:g.year,text:message},...r.memories].slice(0,100)};return log(next,message,'Relationship memory','💛');}
export function chooseCare(g,id,type){const p=people(g).find(p=>p.id===id&&p.alive!==false&&p.age>=65);if(!g.alive||g.age<18||!p||!careOptions[type])return g;const r=normalizeRealism(g).realism;return log({...g,realism:{...r,carePlans:{...r.carePlans,[id]:{type,name:p.name}}}},`You arranged ${careOptions[type].name.toLowerCase()} for ${p.name}. Costs and time are reviewed each year.`,'Family care','🤝');}
export function housingQuote(g,type){const r=normalizeRealism(g).realism,option=housingOptions[type];if(g.educationStatus==='enrolled'&&['Campus residence','Shared student apartment'].includes(g.universityHousing))return 0;const base=countryBudgets[g.country]?.[0]||8000;return option?Math.round(base*option.rentFactor*r.economy.priceIndex*r.economy.housingIndex*simulationSettings(g).cost*({Budget:.8,Balanced:1,Family:1.2,Premium:1.55}[g.enrichment?.housing?.neighbourhood]||1)):0;}
export function moveHome(g,type,assetId){if(!g.alive||g.age<18)return g;const r=normalizeRealism(g).realism;const asset=(g.assets||[]).find(a=>a.id===assetId&&a.status==='owned'&&a.category==='Homes'&&!a.rentedOut);if(type==='owned'&&!asset||type!=='owned'&&!housingOptions[type])return g;if(type==='family'&&!(g.family?.parents||[]).some(p=>p.alive!==false))return g;const cost=type==='family'?0:300;const paid=cost?spend(g,cost,'Moving costs'):g;if(!paid)return g;return log({...paid,livingArrangement:type==='owned'?{type:'buy',assetId}:null,realism:{...r,housing:{type,assetId:type==='owned'?assetId:null,country:g.country,quality:asset?Math.min(95,55+Math.log10(Math.max(1,asset.value))*5):housingOptions[type].quality,commute:asset?6:housingOptions[type].commute,condition:asset?.condition??100,changedYear:g.year}}},`You moved into ${asset?.name||housingOptions[type].name}. ${type==='owned'?'Existing asset upkeep and loan repayments continue.':`Estimated annual rent: ${formatMoney(housingQuote(g,type))}.`}`,'Home','🏠');}
export function buyStarterHome(g){if(!g.alive||g.age<18)return g;const r=normalizeRealism(g).realism;if(r.housing.purchaseYear===g.year)return g;const {price,down,principal,apr,monthlyPayment,reason}=mortgageQuote(g);if(reason)return g;const paid=spend(g,down,'Home down payment');const id=`home-${g.characterId||g.name}-${g.year}`;const asset={id,name:'Family starter home',category:'Homes',kind:'House',status:'owned',value:price,condition:100,monthlyCost:Math.round(price*.01/12),depreciation:0};const loan={id:`mortgage-${id}`,purpose:'Home mortgage',assetId:id,principal,balance:principal,apr,termMonths:300,monthlyPayment,monthsPaid:0,status:'active'};return log({...paid,assets:[asset,...(g.assets||[])],loans:[loan,...(g.loans||[])],livingArrangement:{type:'buy',assetId:id},realism:{...r,housing:{type:'owned',assetId:id,country:g.country,quality:75,condition:100,commute:6,purchaseYear:g.year}}},`You bought a home for ${formatMoney(price)} with ${formatMoney(down)} down. Your 25-year mortgage payment is ${formatMoney(monthlyPayment)} per month; annual upkeep is separate.`,'Mortgage','🏠');}
export function repairHome(g){const r=normalizeRealism(g).realism,h=r.housing;if(!g.alive||h.repairYear===g.year||h.type!=='owned')return g;const asset=(g.assets||[]).find(a=>a.id===h.assetId&&a.status==='owned');if(!asset)return g;const cost=Math.max(250,Math.round(asset.value*.005));const paid=spend(g,cost,'Home maintenance');if(!paid)return g;return log({...paid,assets:(paid.assets||[]).map(a=>a.id===h.assetId?{...a,condition:clamp((a.condition??100)+15)}:a),realism:{...r,housing:{...h,condition:clamp((asset.condition??100)+15),repairYear:g.year,quality:clamp(h.quality+3)}}},'You repaired your home, improving its condition and comfort.','Home maintenance','🔧');}
export function treatPersistent(g,id){const r=normalizeRealism(g).realism,c=r.conditions.find(c=>c.id===id),def=healthDefinitions[c?.type];if(!g.alive||!c||!def||c.treatmentYear===g.year)return g;const quote=insuredQuote(g,def.cost,'health');if(funds(g)<quote.userCost)return g;const paid=insuredExpense(g,def.cost,'health',null,`${def.name} care`);return log({...paid,stats:{...paid.stats,health:clamp(paid.stats.health+3)},realism:{...r,conditions:r.conditions.map(old=>old.id===id?{...old,treatmentYear:g.year,severity:Math.max(10,old.severity-10),managed:true}:old)}} ,`Your ${def.name.toLowerCase()} care plan was renewed. ${c.type==='injury'?'Recovery continues.':'The condition remains persistent, but treatment reduces its impact.'}`,'Ongoing treatment','🩺');}
const eventDeck=[{id:'relocation',title:'A relocation opportunity',text:'An opportunity in another neighbourhood could improve your prospects, but moving takes money and disrupts routines.',choices:[{id:'move',label:'Move for the opportunity',cost:1800,reputation:3,happiness:3,career:6,relocation:true},{id:'stay',label:'Keep your local support network',happiness:2,trust:2}]},{id:'accident',title:'An unexpected accident',text:'A minor accident has left you injured. Recovery and treatment will take time.',choices:[{id:'care',label:'Get care and rest',cost:450,medical:true,health:3,stress:-5,recovery:1},{id:'push',label:'Keep going without treatment',health:-5,stress:8,recovery:2}]},{id:'emergency',title:'A family emergency',text:'A family member needs practical support urgently. You must decide how to fit it around your own obligations.',choices:[{id:'help',label:'Help in person',health:-1,trust:6,stress:4,reputation:3},{id:'fund',label:'Pay for practical assistance',cost:600,trust:4,reputation:2},{id:'decline',label:'Explain that you cannot help',trust:-3,stress:2}]},{id:'setback',title:'An unexpected household expense',text:'An essential appliance has failed. A replacement would restore comfort, but your budget is already committed.',choices:[{id:'replace',label:'Replace it',cost:700,happiness:2},{id:'repair',label:'Choose a basic repair',cost:180,happiness:-1},{id:'wait',label:'Wait and save up',happiness:-4,stress:4}]}];
export function resolveRealEvent(g,id){const r=normalizeRealism(g).realism,event=r.event,choice=event?.choices.find(c=>c.id===id);if(!g.alive||!choice)return g;let paid=g;if(choice.cost){const cost=choice.medical?insuredQuote(g,choice.cost,'health').userCost:choice.cost;if(funds(g)<cost)return g;paid=choice.medical?insuredExpense(g,choice.cost,'health',null,'Accident treatment'):spend(g,choice.cost,event.title);}const conditions=[...r.conditions];if(choice.recovery)conditions.push({id:`injury-${g.year}`,type:'injury',severity:30,remaining:choice.recovery,managed:!!choice.medical,treatmentYear:choice.medical?g.year:null});let next={...paid,stats:{...paid.stats,health:clamp(paid.stats.health+(choice.health||0)),happiness:clamp(paid.stats.happiness+(choice.happiness||0))},realism:{...r,event:null,conditions,stress:clamp(r.stress+(choice.stress||0)),reputation:clamp(r.reputation+(choice.reputation||0)),career:{...r.career,performance:clamp((r.career.performance||55)+(choice.career||0))},eventHistory:[{id:event.id,title:event.title,choice:choice.label,year:g.year},...(r.eventHistory||[])].slice(0,40)}};if(choice.relocation){next={...next,livingArrangement:null,universityHousing:next.educationStatus==='enrolled'?'Commute from home':next.universityHousing,friends:(next.friends||[]).map(p=>({...p,closeness:clamp((p.closeness??50)-4)})),realism:{...next.realism,housing:{type:'shared',country:next.country,quality:65,commute:3,neighbourhood:'New district',changedYear:next.year}}};}if(choice.trust)for(const p of people(next).filter(p=>p.alive!==false&&p.role!=='Friend'))next=mapPerson(next,p.id,p=>({...p,trust:clamp((p.trust??65)+choice.trust),closeness:clamp((p.closeness??50)+choice.trust)}));return log(next,`${event.title}: ${choice.label}. The decision changed your well-being and family circumstances.`,'Life decision','🧭');}

function charge(g,due,label,field){due=Math.max(0,Math.round(due));const r=g.realism,total=due+(r[field]||0),amount=Math.min(funds(g),total);const paid=amount?spend(g,amount,label):g;return {...paid,realism:{...r,[field]:total-amount}};}
export function advanceRealism(input,rng=Math.random){if(!input.alive||input.realism?.processedYear===input.year)return input;let g=normalizeRealism(input),r=g.realism;const previousJob=r.career.role;const cycle=rng(),phase=input.worldLife?.preparedYear===input.year?(['Recession','Expansion'].includes(input.worldLife.market)?input.worldLife.market:'Stable'):cycle<.16?'Recession':cycle>.82?'Expansion':'Stable';const inflation=phase==='Expansion'?.045:phase==='Recession'?.012:.025;const index=r.economy.priceIndex*(1+inflation),housingIndex=Math.max(.6,r.economy.housingIndex*(phase==='Recession'?.94:phase==='Expansion'?1.07:1.025));r={...r,processedYear:g.year,economy:{...r.economy,phase,inflation,priceIndex:index,housingIndex,unemployment:phase==='Recession'?.11:phase==='Expansion'?.035:.055,history:[{year:g.year,phase,inflation},...(r.economy.history||[])].slice(0,40)}};g={...g,realism:r,assets:(g.assets||[]).map(a=>a.category==='Homes'&&a.status==='owned'?{...a,value:Math.round(a.value*(housingIndex/(input.realism?.economy?.housingIndex||1)))}:a),companies:(g.companies||[]).map(c=>({...c,performance:clamp((c.performance||50)+(phase==='Recession'?-5:phase==='Expansion'?3:0))}))};
if(g.livingArrangement?.assetId&&g.livingArrangement.assetId!==r.housing.sourceAssetId&&g.livingArrangement.assetId!==r.housing.assetId){r={...r,housing:startingHousing(g)};g={...g,realism:r};}
// Disappearing or sold residences return to a tenancy; property upkeep is handled by the existing asset engine.
if(['owned','asset'].includes(r.housing.type)&&!(g.assets||[]).some(a=>a.id===r.housing.assetId&&!a.rentedOut)||r.housing.type==='family'&&g.age>=18&&!(g.family?.parents||[]).some(p=>p.alive!==false)||r.housing.country!==g.country){r={...r,housing:{type:'shared',country:g.country,quality:50,commute:6}};g={...g,realism:r};g=log(g,'Your household changed. You arranged a shared apartment and now pay annual rent.','Housing change','🏠');}
const carePlans={};for(const [id,plan] of Object.entries(r.carePlans)){const p=people(g).find(p=>p.id===id&&p.alive!==false);if(p)carePlans[id]=plan;}r={...g.realism,carePlans};g={...g,realism:r};const schedule=weeklySchedule(g);const sleep=r.schedule.sleep;const stress=clamp(r.stress+(schedule.overload*.7)+(sleep<7?8:-4)+(r.housing.quality<45?5:0)-(r.schedule.hobbies>=4?3:0)-(r.schedule.exercise>=3?2:0));const energy=clamp(85-schedule.overload*.9-(8-sleep)*7-stress*.25);const burnout=clamp(r.burnout+(stress>70?12:stress>50?4:-8));const mobility=clamp(r.mobility-(g.age>=75?3:g.age>=60?1:0));r={...r,stress,energy,burnout,mobility};g={...g,realism:r,stats:{...g.stats,health:clamp(g.stats.health+(sleep>=7?1:-3)+(r.diet==='Nutritious'?2:r.diet==='Convenience'?-2:0)+(r.exercise==='Active'&&r.schedule.exercise>=3?2:r.exercise==='Rest'?-1:0)-(burnout>=65?3:0)-(mobility<40?1:0)),happiness:clamp(g.stats.happiness+(r.schedule.hobbies>=4?2:0)+(r.housing.quality>=75?1:r.housing.quality<55?-1:0)-(stress>=60?4:0))},skills:{...g.skills,Discipline:clamp((g.skills?.Discipline||10)+(r.schedule.study>=6&&energy>=35?1:0))}};
const conditions=r.conditions.map(c=>({...c}));for(const [type,def] of Object.entries(healthDefinitions)){if(type==='injury'||conditions.some(c=>c.type===type)||g.age<def.minAge)continue;const risk=.012+(g.age-def.minAge)*.0008+(g.stats.health<50?.025:0)+(r.diet==='Convenience'?.015:0);if(rng()<risk){conditions.push({id:`${type}-${g.year}`,type,severity:35,diagnosedYear:g.year,managed:false});g=log(g,`A clinic identified ${def.name.toLowerCase()}. Review ongoing care in Health & care.`,'Persistent condition','🩺');}}
let healthLoss=(g.healthConditions||[]).filter(c=>c.diagnosed).reduce((n,c)=>n+Math.min(3,Number(c.severity)||1),0);for(const c of conditions){const def=healthDefinitions[c.type];if(!def)continue;const managed=c.treatmentYear===g.year||c.treatmentYear===g.year-1;healthLoss+=managed?1:def.drain;if(!managed)c.severity=clamp(c.severity+4);c.managed=managed;if(c.type==='injury')c.remaining=Math.max(0,(c.remaining||1)-1);}g={...g,stats:{...g.stats,health:clamp(g.stats.health-healthLoss)},realism:{...g.realism,conditions:conditions.filter(c=>c.type!=='injury'||c.remaining>0)}};
const annualRent=g.age>=18&&!['owned','asset'].includes(r.housing.type)?housingQuote(g,r.housing.type):0;const beforeRent=(g.money||0)+(g.bankBalance||0);g=charge(g,annualRent,'Annual rent','housingArrears');g={...g,realism:{...g.realism,lastHousingCost:Math.min(annualRent,beforeRent)}};const careCost=Object.values(carePlans).reduce((n,p)=>n+(careOptions[p.type]?.cost||0)*index,0);g=charge(g,careCost,'Family caregiving','careArrears');const fullyPaid=g.realism.careArrears===0;for(const p of g.family?.parents||[]){if(p.alive===false||p.age<65)continue;const plan=carePlans[p.id];const supported=plan&&plan.type!=='none'&&fullyPaid;g=mapPerson(g,p.id,old=>({...old,health:clamp((old.health??70)-(old.age>=80?4:2)+(supported?2:0)),careNeed:old.age>=80?'High':'Moderate',closeness:clamp((old.closeness??50)+(supported?2:-1))}));}
const publicActs=Math.min(5,Math.floor(Math.max(0,(g.lifetimeDonations||0)-(g.realism.donationsSeen||0))/1000));const offenses=Math.max(0,(g.criminalRecord||[]).length-(g.realism.offensesSeen||0));g={...g,realism:{...g.realism,reputation:clamp(g.realism.reputation+publicActs-offenses*8),donationsSeen:g.lifetimeDonations||0,offensesSeen:(g.criminalRecord||[]).length}};
const updatedPeople=p=>{if(p.alive===false)return p;const person=personState(p,g),aligned=!r.goal||r.goal===person.sharedGoal;const contact=r.schedule.social>=4&&energy>=25;return {...person,closeness:clamp((person.closeness??50)+(contact?1:-3)+(aligned?1:-1)+(person.compatibility>=75?1:person.compatibility<55?-1:0)),trust:clamp(person.trust+(stress>75?-3:contact?1:0))};};g={...g,partner:g.partner?updatedPeople(g.partner):null,friends:(g.friends||[]).map(updatedPeople),children:(g.children||[]).map(p=>{if(p.alive===false)return p;const child=updatedPeople(p),interest=child.interest;const progress=clamp((child.ambitionProgress||0)+(child.autonomy>=50?7:3));const adult=p.age>=18;const decision=adult?(progress>=60?`Pursuing a career in ${interest}`:`Exploring ${interest} and education options`):p.age>=12?`Developing ${interest} interests and friendships`:`Discovering ${interest}`;return {...child,ambitionProgress:progress,ownDecision:decision,personalCareer:child.familyEmployment?child.personalCareer:adult&&child.ownEducationChoice==='Work'?`${interest} trainee`:child.personalCareer,personalWealth:child.personalWealth||0,friendCount:Math.min(12,(p.friendCount||0)+(rng()<.5?1:0)),independent:adult,personalWellbeing:clamp((p.personalWellbeing??70)+(child.autonomy>=50?1:-2))};})};
const promises=g.realism.promises.map(p=>p.status==='pending'&&!people(g).some(person=>person.id===p.personId&&person.alive!==false)?{...p,status:'unavailable'}:p.status==='pending'&&g.year>=p.deadline?{...p,status:'broken'}:p);const broken=promises.filter(p=>p.status==='broken'&&!g.realism.promises.some(old=>old.id===p.id&&old.status==='broken'));for(const p of broken){g=mapPerson(g,p.personId,person=>({...person,trust:clamp((person.trust??65)-8),closeness:clamp((person.closeness??50)-5)}));g=log(g,`You did not keep your promise to ${p.name}. They remember the disappointment.`,'Broken promise','💔');}r={...g.realism,promises,reputation:clamp(g.realism.reputation-broken.length*3)};
if(g.job&&!g.retired&&!g.jail&&workingRate(g)>0&&g.job!=='Founder & CEO'&&g.job!==g.politicalOffice){const newRole=previousJob!==g.job;let career={...r.career,role:g.job,probation:r.career.probation||false,performance:clamp((r.career.performance||55)+(g.skills?.Discipline||0)*.04+(energy>=55?3:-5)-(burnout>=60?8:0)),history:r.career.history||[]};const layoff=rng()<(phase==='Recession'?.09:.015);const failed=career.probation&&career.performance<35;if(layoff||failed){const oldJob=g.job;const severance=layoff?Math.round((g.salary||0)/6):0;g={...g,bankBalance:(g.bankBalance||0)+severance,lifetimeIncome:(g.lifetimeIncome||0)+severance,transactions:severance?[{label:'Redundancy payment',amount:severance,age:g.age},...(g.transactions||[])]:g.transactions,job:null,salary:0,career:'Seeking employment',careerYears:0,fameContract:g.fameContract?{...g.fameContract,status:'terminated'}:null};career={...career,role:null,probation:false,history:[{year:g.year,role:oldJob,outcome:layoff?'Laid off':'Probation ended'},...career.history]};g=log(g,`${layoff?'Your employer reduced staffing':'You did not pass probation'} and your ${oldJob} role ended at year-end. This year’s earned pay remains yours${severance?`; severance paid ${formatMoney(severance)}`:''}. Explore job offers in Career.`,'Employment ended','💼');}else{career={...career,probation:false,history:[{year:g.year,role:g.job,outcome:`Performance review: ${Math.round(career.performance)}/100`},...career.history].slice(0,30)};g=log(g,`Your annual review scored ${Math.round(career.performance)}/100.${r.career.probation?' You passed probation.':''}${burnout>=65?' Burnout is affecting your performance. Adjust your schedule.':''}`,'Performance review','💼');}r={...r,career};}
if(!r.event&&g.age>=16&&rng()<.28){const eligible=eventDeck.filter(e=>e.id!=='emergency'||people(g).some(p=>p.alive!==false));const event=eligible[Math.floor(rng()*eligible.length)%eligible.length];r={...r,event:{...event,year:g.year}};g=log(g,`${event.title}. Open Real Life to choose how to respond.`,'Unexpected event','🧭');}g={...g,realism:r};return advanceNpcEconomy(log(g,`${phase} economy: inflation ${(inflation*100).toFixed(1)}%, unemployment ${(r.economy.unemployment*100).toFixed(1)}%. Weekly commitments ${Math.round(schedule.total)}/168 hours; energy ${Math.round(energy)}, stress ${Math.round(stress)}.`, 'Yearly circumstances','🌍'));}
export function generationRealism(g,child){const r=normalizeRealism({...g,realism:undefined}).realism;return {pendingInterview:null,realism:{...r,economy:g.realism?.economy||r.economy,goal:child.sharedGoal||'Family',reputation:50,housing:child.age<18?{type:'family',country:g.country,quality:55}:{type:'shared',country:g.country,quality:50,commute:6}}};}
