// USD game budgets and simplified tax bands. Dubai is a UAE city, not a country.
const rows=[['United Arab Emirates','🇦🇪',18000,0,.09],['Saudi Arabia','🇸🇦',12000,0,.20],['Qatar','🇶🇦',16000,0,.10],['Kuwait','🇰🇼',14000,0,.15],['Bahrain','🇧🇭',12000,0,0],['Oman','🇴🇲',11000,0,.15],['Jordan','🇯🇴',6500,.20,.20],['Lebanon','🇱🇧',6500,.20,.17],['Syria','🇸🇾',3000,.15,.22],['Iraq','🇮🇶',4500,.15,.15],['Iran','🇮🇷',4500,.25,.25],['Israel','🇮🇱',17000,.35,.23],['Palestine','🇵🇸',4000,.15,.15],['Yemen','🇾🇪',2500,.15,.20],['Turkey','🇹🇷',7000,.30,.25],['Cyprus','🇨🇾',12000,.25,.15]];
export const middleEastCountries=rows.map(([name,flag])=>({name,flag,names:name==='Israel'?['Noa','Daniel','Yael','Ariel']:name==='Turkey'?['Deniz','Elif','Emre','Zeynep']:name==='Iran'?['Sara','Arman','Nima','Leila']:name==='Cyprus'?['Andreas','Eleni','Maria','Nikos']:['Layla','Omar','Noor','Amir','Fatima','Yusuf'],cities:name==='United Arab Emirates'?['Dubai','Abu Dhabi','Sharjah']:[]}));
export const middleEastNames=Object.fromEntries(middleEastCountries.map(c=>[c.name,{first:c.names,last:c.name==='Turkey'?['Yilmaz','Kaya']:c.name==='Israel'?['Cohen','Levi']:c.name==='Iran'?['Ahmadi','Rezaei']:c.name==='Cyprus'?['Georgiou','Ioannou']:['Hassan','Khalil','Mansour','Nasser']} ]));
export const middleEastSchools=Object.fromEntries(rows.map(([name])=>[name,[{name:'Primary school',start:6,end:11},{name:'Middle school',start:12,end:14},{name:'Secondary school',start:15,end:17}]]));
export const regionalBudgets=Object.fromEntries(rows.map(([name,,cost,rate])=>[name,[cost,rate]]));
export const regionalCorporateRates=Object.fromEntries(rows.map(([name,,,,rate])=>[name,rate]));
export function regionalIncomeTax(g,income){if(!regionalBudgets[g.country])return null;if(['United Arab Emirates','Saudi Arabia','Qatar','Kuwait','Bahrain'].includes(g.country))return 0;if(g.country==='Oman')return g.year>=2028?Math.round(Math.max(0,income-109200)*.05):0;const rate=regionalBudgets[g.country][1],taxable=Math.max(0,income-10000);return Math.round(Math.min(taxable,30000)*rate*.5+Math.max(0,taxable-30000)*rate);}
export function regionalCompanyTax(country,profit){if(!regionalCorporateRates[country])return 0;return Math.round(Math.max(0,profit-(country==='United Arab Emirates'?102110:0))*regionalCorporateRates[country]);}
