import React from 'react';
import {ArrowUpRight,Trophy,Activity,Dumbbell,HeartPulse,Flag,Users,Shield,ChevronRight} from 'lucide-react';
import {enrichmentState,hash} from './enrichmentCore.js';
import {enrichmentAction} from './lifeEnrichment.js';
import {SportsActivityPanel} from './PublicCareerPanels.jsx';
import {useFeedbackNotice} from './OutcomeFeedback.jsx';
import {formatMoney} from './money.js';
import './sports-team.css';
const sports={Football:{icon:'⚽',accent:'#56e7a0',dark:'#123f38',label:'The beautiful game',description:'Find your touch. Earn your place. Play for the badge.'},Basketball:{icon:'🏀',accent:'#ffb272',dark:'#4f293c',label:'Own the court',description:'Build your game, chase the roster, make every possession count.'},Tennis:{icon:'🎾',accent:'#d6ed75',dark:'#33472b',label:'Find your winning edge',description:'A stronger serve. A sharper return. Your next breakthrough.'},Track:{icon:'👟',accent:'#96c4ff',dark:'#273d62',label:'Chase your personal best',description:'Put in the work and turn discipline into a finish-line moment.'}};
const palettes=[['#56e7a0','#123f38'],['#ffb272','#4f293c'],['#96c4ff','#273d62'],['#d6ed75','#33472b'],['#d3b4ff','#3c2e60']];
function PitchArt({sport}){return <svg className="sports-pitch-art" viewBox="0 0 300 240" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="2"><rect x="34" y="20" width="232" height="200" rx="4"/>{sport==='Football'?<><path d="M34 120h232M110 20v40h80V20M110 220v-40h80v40"/><circle cx="150" cy="120" r="31"/></>:sport==='Basketball'?<><path d="M34 120h232M105 20v43h90V20M105 220v-43h90v43"/><circle cx="150" cy="120" r="25"/><path d="M62 20a88 88 0 0 0 176 0M62 220a88 88 0 0 1 176 0"/></>:sport==='Tennis'?<><path d="M34 120h232M58 20v200M242 20v200M58 72h184M58 168h184M150 72v96"/></>:<>{[0,1,2,3].map(i=><rect key={i} x={54+i*13} y={34+i*13} width={192-i*26} height={172-i*26} rx={66-i*9}/>)}<path d="M150 120v90"/></>}</g></svg>;}
export function TeamBadge({name,sport,small=false}){const initials=name.split(/\s+/).filter(Boolean).map(w=>w[0]).slice(0,3).join('').toUpperCase();return <span className={`sports-team-badge ${small?'small':''}`} aria-label={`${name} club badge`}><Shield aria-hidden="true"/><span>{sports[sport]?.icon||'🏅'}</span><b>{initials}</b></span>;}
export default function SportsTeamScreen({game,setGame,onSocial}){const s=enrichmentState(game).sports;const [notice,setNotice]=useFeedbackNotice('');const run=(action,value)=>setGame(g=>{const result=enrichmentAction(g,action,value);setNotice(result.error||result.message);return result.game;});const kind=sports[s?.sport]||sports.Football,club=s?.club||(s?.stage==='School team'?`${game.country} School Team`:`${game.country} Community Club`),palette=s?.club?palettes[hash(s.club)%palettes.length]:[kind.accent,kind.dark],style={'--team-accent':palette[0],'--team-dark':palette[1]};const records=s?.competitions||[],season=records.filter(e=>e.year===game.year),wins=season.filter(e=>e.result==='Won').length,losses=season.filter(e=>e.result==='Lost').length,injured=(s?.injuredUntil||0)>game.year,blocked=!game.alive||game.jail?.yearsRemaining>0,offers=(s?.offers||[]).filter(o=>o.expires>=game.year);return <div className="sports-team-screen" style={style}>
 {!s?<><header className="sports-discovery-hero"><span className="sports-kicker">YOUR NEXT CHAPTER</span><h2>Every great career<br/>starts somewhere.</h2><p>Pick your sport. Find your team. Build a name worth cheering for.</p><div className="sports-discovery-icons" aria-hidden="true">⚽ 🏀 🎾 👟</div></header><div className="sports-section-heading"><h3>Find your sport</h3><span>Teams open at ages 8–25</span></div><div className="sports-choice-grid">{Object.entries(sports).map(([name,info])=><button className="sports-choice" key={name} style={{'--choice-accent':info.accent,'--choice-dark':info.dark}} disabled={blocked||game.age<8||game.age>25} onClick={()=>run('sport-join',name)} aria-label={`${name} · Join a team`}><PitchArt sport={name}/><span className="sports-choice-icon">{info.icon}</span><small>{info.label}</small><h3>{name}</h3><p>{info.description}</p><span className="sports-choice-link">Join a team <ArrowUpRight size={18}/></span></button>)}</div><p className="sports-path-note"><Flag size={18}/> School team → amateur club → professional contract. Train, compete, and give scouts a reason to notice you.</p></>:<>
 <header className="sports-club-hero"><PitchArt sport={s.sport}/><div className="sports-hero-top"><span className="sports-kicker">{s.stage==='Professional'?'THE CLUBHOUSE':s.stage==='Retired'?'YOUR SPORTING LEGACY':'THE NEXT GENERATION'}</span><span className="sports-season-pill">{game.year} SEASON</span></div><div className="sports-club-identity"><TeamBadge name={club} sport={s.sport}/><div><span className="sports-club-location">{game.country} · {s.sport}</span><h2>{club}</h2><p>{s.stage==='Professional'?'Play for the badge. Build your legacy.':s.stage==='Retired'?'The final whistle never erases your story.':'Big dreams. Small beginnings. Your team.'}</p></div></div><div className="sports-hero-bottom"><span className="sports-status"><i/>{s.stage}</span><span>{injured?'🩹 On the road to recovery':'✦ Ready for the next challenge'}</span></div></header>
 <section className="sports-season-strip" aria-label="Season record"><div><span>PLAYED</span><b>{season.length}</b></div><div><span>WINS</span><b>{wins}</b></div><div><span>LOSSES</span><b>{losses}</b></div><div><span>CAREER EVENTS</span><b>{records.length}</b></div></section>
 <section className="sports-athlete-card"><div className="sports-section-heading"><div><span className="sports-kicker">PLAYER PROFILE</span><h3>{s.sport} · {s.stage}</h3></div><span className={`sports-fitness-pill ${injured?'injured':''}`}><HeartPulse size={15}/>{injured?'Recovering':'Fit to play'}</span></div><p className="sports-athlete-name">{game.name}<span>{s.focus||'Technique'} training</span></p><div className="sports-attribute-grid">{[['Skill',s.skill,Dumbbell],['Fitness',s.fitness,Activity],['Performance',game.fameContract?.sports?game.fameContract.performance:records[0]?.score,Flag]].map(([label,value,Icon])=><div key={label}><div><Icon size={16}/><span>{label}</span><b>{value==null?'—':Math.round(value)}</b></div><div className="sports-attribute-track"><i style={{width:`${Math.max(0,Math.min(100,value||0))}%`}}/></div></div>)}</div>{s.stage!=='Retired'&&<button className="sports-training-button" disabled={blocked||injured||s.trainingYear===game.year} onClick={()=>run('sport-train')}><Dumbbell size={20}/><span>Train with a coach<small>{s.trainingYear===game.year?'Session complete · come back next year':injured?'Recover before returning to training':game.age<18?'Your next school training session':'Build your game · $400 per session'}</small></span><ChevronRight size={19}/></button>}</section>
 <SportsActivityPanel game={game} setGame={setGame} onSocial={onSocial}/>
 {s.stage!=='Retired'&&<section className="sports-transfer-section"><div className="sports-section-heading"><div><span className="sports-kicker">THE NEXT MOVE</span><h3>Club offers</h3></div><span className="sports-offer-count">{offers.length} open</span></div>{offers.length?offers.map(o=><article className="sports-offer-card" key={o.id}><div className="sports-offer-identity"><TeamBadge name={o.club} sport={s.sport} small/><div><small>SCOUTING OFFER</small><h4>{o.club}</h4><span>Valid through {o.expires}</span></div></div><div className="sports-offer-terms"><div><small>Annual pay</small><b>{fmtMoney(o.salary)}</b></div><div><small>Contract length</small><b>{o.years} seasons</b></div></div><button disabled={blocked||injured} onClick={()=>run('sport-sign',o.id)}>Sign or transfer to this club <ArrowUpRight size={18}/></button></article>):<div className="sports-scout-empty"><Users size={26}/><div><b>Give the scouts something to talk about.</b><p>Build your skill to 60 for yearly scouting offers, or attend a tryout from age 18 at skill 50. Your next opportunity could be one good performance away.</p></div></div>}</section>}
 <section className="sports-legacy-note"><Trophy size={21}/><div><b>{s.stage==='Retired'?'A career to remember':'Your story is still being written.'}</b><p>{records.length?`${records.filter(e=>e.result==='Won').length} wins across ${records.length} competitions. Your results live on in your career history.`:'Your first competition will start your match history. Training and real results shape your journey.'}</p>{s.stage!=='Retired'&&<button disabled={blocked} onClick={()=>run('sport-retire')}>Retire from competition</button>}</div></section>
 </>}{notice&&<p className="enrichment-notice sports-feedback" role="status">{notice}</p>}
 </div>;}
const fmtMoney=formatMoney;
