import {EstateLifePanel} from './EnrichmentScreens.jsx';
import {LifeHero} from './LifeScreenUI.jsx';
import {useFeedbackNotice} from './OutcomeFeedback.jsx';
import React,{useState} from 'react';
import {defaultWill,willRecipients,validateWill} from './estate.js';
import {formatMoney} from './money.js';
export default function WillPlanner({game,setGame,netWorth,onClose}){
 const [draft,setDraft]=useState(()=>game.will?{...game.will,beneficiaries:game.will.beneficiaries.map(p=>({...p}))}:defaultWill(game));const [notice,setNotice]=useFeedbackNotice('');
 const recipients=willRecipients(game);const total=draft.beneficiaries.reduce((sum,p)=>sum+(Number(p.percent)||0),0);
 const toggle=person=>setDraft(d=>({...d,beneficiaries:d.beneficiaries.some(p=>p.id===person.id)?d.beneficiaries.filter(p=>p.id!==person.id):[...d.beneficiaries,{...person,percent:0}]}));
 const save=()=>{const error=validateWill(draft,game);if(error){setNotice(error);return;}setGame(g=>({...g,will:{...draft,beneficiaries:draft.beneficiaries.map(p=>({...p,percent:Number(p.percent)})),signedYear:g.year,signedAge:g.age},log:[{year:g.year,age:g.age,text:`You ${g.will?'updated':'wrote'} your will: ${draft.beneficiaries.map(p=>`${p.name} ${p.percent}%`).join(', ')}.`,tag:'Estate planning',icon:'📜'},...(g.log||[])]}));onClose();};
 return <div className="dialog-backdrop family-modal-backdrop" onClick={onClose}><section className="confirm-dialog family-modal will-modal" role="dialog" aria-modal="true" aria-labelledby="will-title" onClick={e=>e.stopPropagation()}><button className="purchase-close" aria-label="Close will" onClick={onClose}>×</button><div id="will-title"><LifeHero icon="📜" title="Your last will" description="Choose who inherits, appoint someone you trust and leave a message for your family." badge="Estate planning"/></div><div className="life-metrics"><div><small>Estimated net estate</small><b>{formatMoney(Math.max(0,netWorth))}</b></div><div><small>Beneficiaries selected</small><b>{draft.beneficiaries.length}</b></div></div>
 {notice&&<div className="system-notice" role="status">{notice}</div>}
 <h3>Choose beneficiaries</h3><div className="will-beneficiaries">{recipients.map(person=>{const allocation=draft.beneficiaries.find(p=>p.id===person.id);return <div className="will-beneficiary" key={person.id}><label><input type="checkbox" checked={!!allocation} onChange={()=>toggle(person)}/><span><b>{person.name}</b><small>{person.role}</small></span></label>{allocation&&<label className="will-share"><input aria-label={`${person.name} share`} type="number" min="1" max="100" value={allocation.percent} onChange={e=>setDraft(d=>({...d,beneficiaries:d.beneficiaries.map(p=>p.id===person.id?{...p,percent:e.target.value}:p)}))}/><span>%</span></label>}</div>;})}</div>
 <div className={`will-total ${total===100?'valid':''}`}>Allocated: {total}% / 100%<button onClick={()=>setDraft(d=>{const count=d.beneficiaries.length;if(!count)return d;const share=Math.floor(100/count);return {...d,beneficiaries:d.beneficiaries.map((p,i)=>({...p,percent:share+(i===0?100-share*count:0)}))};})}>Split equally</button></div>
 <div className="social-form-grid"><label>Executor<select value={draft.executor||''} onChange={e=>setDraft(d=>({...d,executor:e.target.value}))}><option value="">Independent estate administrator</option>{recipients.filter(p=>p.id!=='charity'&&p.age>=18).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Guardian for minor children<input value={draft.guardian||''} maxLength={80} placeholder="Optional guardian name" onChange={e=>setDraft(d=>({...d,guardian:e.target.value}))}/></label></div>
 <label className="social-compose">Personal message<textarea maxLength={500} value={draft.message||''} placeholder="Leave a message for your family" onChange={e=>setDraft(d=>({...d,message:e.target.value}))}/></label><p>During succession, debts are settled and the chosen child receives their stated cash share. Nominated family businesses pass directly to their designated heir instead of being sold. Other beneficiaries receive their shares outside your playable estate.</p>
 <EstateLifePanel game={game} setGame={setGame}/><div className="family-confirm-actions"><button onClick={onClose}>Cancel</button><button className="confirm-new" disabled={total!==100||game.age<18||!game.alive} onClick={save}>Sign & save will</button></div></section></div>;
}
